src/screens/ModelPage.js
- add distribution option for x-axis
=> resolves #14

src/App.js, src/assets/theme/palette.js, src/components/AppBar/AppBar.js, src/components/AppBar/AppBar.style.js, src/components/Map/Map.js, src/screens/FAQ/FAQ.js, src/screens/FAQ/FAQ.style.js, src/screens/HomePage.js, src/screens/ModelPage.js
=> Add FAQ tab

src/components/Footer/Footer.js
Close #52 and will make @JaniceZdankus's English teacher happy ;)
=> Modifying Who's to whose

.gitignore, package-lock.json, src/components/AppBar/AppBar.js, src/components/AppBar/AppBar.style.js, src/components/AppBar/Burger.js, src/components/AppBar/MobileMenu.js
=> resolves #54

src/components/Footer/Footer.js
=> typo in getting involved

src/components/EndorsementCard/EndorsementCard.js, src/components/EndorsementCard/EndorsementCard.style.js, src/screens/Endorsements/Endorsements.js, src/screens/Endorsements/Endorsements.style.js, src/utils/constants.js
- use material ui grid components
- update css styles
=> resolves #58

src/components/AppBar/AppBar.js, src/components/AppBar/MobileMenu.js
fixes https://github.com/covid-projections/covid-projections/issues/67
=> update menu tab for map from 'Data' to 'Map'

src/components/EndorsementCard/EndorsementCard.style.js, src/components/Footer/Footer.js, src/enums/endorsers.js, src/screens/Endorsements/Endorsements.js, src/screens/Endorsements/Endorsements.style.js
- add new endorsers
- fix styling
- remove unused styles
=> resolve #78

src/components/AppBar/AppBar.js, src/components/EndorsementCard/EndorsementCard.js, src/screens/About/About.js, src/screens/Endorsements/Endorsements.js, src/screens/FAQ/FAQ.js
- update setPanelIdx
- fix some react warnings
=> resolves #81

src/components/AppBar/AppBar.js, src/screens/ModelPage/ModelPage.js
**If no state selected and sharing from app bar**
> See a forecast for how long each US state has until COVID-19 overwhelms hospitals and how interventions could flatten the curve:
**If state is selected, both app bar and model share text**
> This is the point of no return for intervention to prevent ${locationName}'s hospital system from being overloaded by Coronavirus:
=> Updated share text in app bar and on model page

src/enums/team.js
=> Updating a couple of bios

src/enums/team.js, src/screens/About/About.js
=> update about us content changes

src/components/Chart/Chart.js, src/screens/ModelPage/ModelPage.js
- update predicted outcome title
- add back last updated
=> resolves #119

src/components/AppBar/AppBar.style.js
=> Keep selected tab red when not focused

package.json, src/components/AppBar/AppBar.js, src/components/Chart/Chart.js, src/components/Footer/Footer.js, src/components/Map/Map.js, src/components/Newsletter/Newsletter.js, src/screens/About/About.js, src/screens/Endorsements/Endorsements.js, src/screens/Endorsements/Endorsements.style.js, src/screens/FAQ/FAQ.js, src/screens/HomePage/HomePage.js, src/screens/ModelPage/ModelPage.js, yarn.lock
I removed a bunch of unused imports and one unused dependency. I also fixed a few link attributes and one iframe attribute according to recommendations.
=> Cleanup some of the warnings from CRA

.dockerignore, Dockerfile, Dockerfile.test, cypress.json, cypress/fixtures/example.json, cypress/integration/homepage.js, cypress/plugins/index.js, cypress/support/commands.js, cypress/support/index.js, docker-compose.yml
This pull request addresses
* Starting Basic Cypress Framework
* Docker container for spinning up main web application
* Docker container for cypress dependencies
* Docker Compose for spinning up main web application w/tests
* Basic Sanity UI Test
#87 
TODO
* Travis CI runs automated test on any PR
=> Address starting cypress testing framework w/  basic sanity test

src/screens/HomePage/HomePage.js
=> Add Newsletter Component to home page

src/screens/HomePage/HomePage.js
- moves newsletter below map on homepage
- content updated in mailjet
=> resolves #152

src/components/Newsletter/Newsletter.js
- had to update the widget as edits in mailjet were not working
=> resolves #165

src/screens/ModelPage/ModelPage.js
=> Define ONE_HUNDRED_DAYS more clearly (and minor refactor).

src/screens/About/About.js
=> Updated Jobs + Added Descriptions

src/screens/ModelPage/ModelPage.js, src/utils/model.js
Prepares us for switchover to python generated models
=> Refactor / simplify dataloading

src/components/Header/Header.js, src/components/Header/Header.style.js
=> Slim header

src/screens/About/About.js
please approve me :) 
@mikelehen @zjrosen1
=> Updated Jobs Available

src/enums/team.js, src/screens/About/About.js, src/screens/Endorsements/Endorsements.js, src/screens/Endorsements/Endorsements.style.js, src/utils/model.js
fixes https://github.com/covid-projections/covid-projections/issues/174 (plus some linting)
=> Add mail link to endorsement page

src/components/Chart/Chart.js, src/components/Chart/Chart.style.js, src/components/Status/Status.js, src/enums/interventions.js, src/screens/ModelPage/CallToAction/CallToAction.js
Closes #209 ‚ should wait until #207 is merged (and then I'll adjust the variable names to match the changes there as well)
=> Renamed No Action to Limited Action

src/screens/About/About.js
=> Removing GC Job

src/screens/About/About.js
=> Add Private Kit: Safe Paths to About page

src/screens/ModelPage/ModelPage.js
Closes #238 , uses a pure html tooltip
=> Added detail to update time

src/components/Charts/Chart.js, src/components/Charts/ModelChart.js, src/components/Charts/ModelChart.style.js, src/screens/ModelPage/ModelPage.js, src/screens/ModelPage/ModelPage.style.js
- moves chart header into chart component
- pulls out highcharts chart into seperate component
=> update charts folder structure

src/components/Charts/ModelChart.js
#251 should read hospital beds per zach rosen.
=> fix: update tooltip text

src/App.js, src/components/Footer/Footer.js, src/screens/Terms/Terms.js, src/screens/Terms/Terms.style.js
Per Dani, here is the initial commit of the Terms of Use. Privacy policy to follow shortly.
=> Initial commit of Terms of Use

src/enums/team.js
Changed the team enum to have proper description of Ellie's role
=> updating ellie's blurb

src/components/AppBar/AppBar.js, src/components/AppBar/AppBar.style.js, src/components/AppBar/MobileMenu.js
Would appreciate some help on how to remove the red style over `Blog` after you click on it:
=> Adding a link to the blog

package.json, src/App.js, src/assets/data/interventions.json, src/components/Charts/ModelChart.js, src/screens/CompareModels/CompareModels.js, src/screens/CompareModels/CompareModels.style.js, src/screens/ModelPage/ModelPage.js, src/utils/model.js, yarn.lock
Merge pull request #276 from covid-projections/mikelehen-compare-model
=> Add a /compare page for testing / debugging model data.

cypress/integration/ModelPage_spec.js, package.json, public/index.html, src/screens/ModelPage/ModelPage.js, yarn.lock
=> feat: dynamic title & description on ModelPage

src/screens/Endorsements/Endorsements.style.js, src/screens/ModelPage/ModelPage.style.js, src/screens/ModelPage/ShareModelBlock/ShareModelBlock.js
- Fixes the text size and display for social media share buttons on mobile
- Evens up the padding on the endorsement quote
=> Fix model page social media share buttons on mobile

src/components/AppBar/AppBar.js
little fix just to make the logo clickable
=> Make logo in header clickable

src/screens/CompareModels/CompareModels.js
fixes https://github.com/covid-projections/covid-projections/issues/298
=> Refresh model comparisons on enter

src/components/AppBar/AppBar.js, src/screens/ModelPage/ShareModelBlock/ShareModelBlock.js
Hacked this together to start getting some data. LMK if anything should adjust, thanks!
=> add GA tag for sharing on FB/Twitter

src/screens/ModelPage/ModelPage.js
Adding: "No cases have been reported or no data exists for {selectedCounty.county}, {selectedCounty.state_code}"
=> Update blank state text

src/screens/About/About.js
=> Updated Job Posts

src/screens/ModelPage/ModelPage.js
Was still pointing at the Google Doc, changing to PDF
@mikelehen @zjrosen1 please merge when you have a moment
=> Replacing an old assumptions doc link

src/enums/team.js
Removing a team member who asked not to be listed
=> Remove contrib

.gitignore, DEV_README.md
just a beginning of a dev readme for clarity of process. CC
=> adding a v basic readme for running dev

src/screens/Embed/Embed.style.js
Removes the scrollbar for many in the embed
=> Remove overflow-y for no scrollbar

public/scripts/embed.js
Broken dynamic script to load widget; this fixes it
=> Embed script href fix

src/components/MapSelectors/GlobalSelector.js
Per this issue:
https://github.com/covid-projections/covid-projections/issues/397
=> update placeholder text to add city prompt

public/scripts/embed.js, src/App.js, src/components/StateHeader/StateHeader.js, src/screens/Embed/Embed.js, src/screens/ModelPage/ModelPage.js, src/utils/hooks.js, src/utils/model.js
* Available at /embed/us/county/53033 or /embed/us/wa/county/king_county
* EMBED share link works on county pages.
* embed.js updated to accept data-fips-id widgets.
* Fixes #418.
=> County Embeds

src/components/Footer/Footer.js
=> Update footer links to match AppBar links

public/index.html, scripts/what-the-fips/fix.js, scripts/what-the-fips/index.js, scripts/what-the-fips/read-census-counties.js, src/assets/theme/palette.js, src/components/Newsletter/Newsletter.js, src/components/Newsletter/Newsletter.style.js, src/screens/Endorsements/Endorsements.js, src/screens/FAQ/FAQ.js, src/screens/HomePage/HomePage.js, src/screens/ModelPage/ModelPage.js
Swaps out our email provider to be CreateSend.
It's hooked up so state / county are populated automatically depending on which page you're on.
=> Integreate with createsend

src/components/Newsletter/Newsletter.js
add GA event for conversion goal @Jtensminger
=> add email subscribe event

src/components/ShareBlock/ShareBlock.js
=> Add missing default share text

src/components/Charts/ModelChart.js, src/components/Charts/ModelChart.style.js, src/components/ShareBlock/ShareBlock.js, src/components/ShareBlock/ShareBlock.style.js, src/components/ShareBlock/ShareModelBlock.js, src/screens/Embed/ChartsTab.js, src/screens/Embed/Embed.js, src/screens/Embed/Embed.style.js, src/screens/Embed/EmbedFooter.js, src/screens/Embed/ProjectionsTab.js
=> Embed: Chart and Share drawer

src/components/Charts/ModelChart.js, src/components/Charts/ModelChart.style.js
[See for yourself.
](https://covid-projections-git-ap-fix-flag.covidactnow.now.sh/us/in/county/vigo_county)
=> Fix flag cutoff

src/components/Map/Map.js
It looks like #430 includes this and other fixes, but in case we just want this so that the tests can stop failing on all the other PRs, feel free to use it.
=> Lint fix for a bunch of open PRs

scripts/calculated_interventions/index.js, scripts/models/projections.js, src/components/Charts/ModelChart.style.js, src/components/StateHeader/StateHeader.js, src/models/Projections.js, src/screens/ModelPage/CallToAction/CallToAction.js, src/screens/ModelPage/ModelPage.js
- rename getInterventionColor to getThresholdInterventionLevel
- fix worst case overwhelmed over 8 weeks plot line color
=> append lax policy to overwhelmed plot line

src/components/Charts/ModelChart.js, src/components/Charts/ModelChart.style.js, src/models/Projections.js
=> update overwhelmed plot line text

src/assets/theme/palette.js, src/components/Charts/ModelChart.js, src/components/Header/HomePageHeader.style.js, src/screens/Endorsements/Endorsements.style.js
Assuming all the greenish highlights that were `#07d180` are supposed to match the green in the logo, which is `#00d07d`.
Closes #360.
=> Update green highlights to match logo. Closes #360

src/components/ShareBlock/EmbedPreview.js, src/components/ShareBlock/EmbedPreview.style.js, src/components/ShareBlock/ShareBlock.tsx, src/components/ShareBlock/ShareModelBlock.js, src/screens/ModelPage/ModelPage.js, src/utils/hooks.tsx
Scrolls in mobile, but lets you preview the embed beforehand
From an embed itself:
=> Embed Preview

src/components/Charts/ModelChart.js, src/screens/ModelPage/Outcomes/Outcomes.js
Forgot to update the table with the new string.
=> update copy on table as well

src/components/Map/USACountyMap.js
=> Fix coloring collision for counties with state-like names (.e.g. Nevada County, CA)

src/screens/About/About.style.tsx, src/screens/About/About.tsx
=> bigger logo

src/models/Projection.ts
* Use "ms since epoch" as x-axis instead of Date objects. Highcharts seems to
accept either for our existing chart, and seems to require "ms since epoch"
for the area-range chart we're using for rt.
* Trim ICU Utilization data to the present (don't show projections).
cc/ @pnavarrc
=> Tweaks to phase 3 datasets.

src/components/LocationPage/ChartsHolder.tsx
This is minimal, but a starting point for iteration (we need to deal with missing data, tweak the end date for charts, etc.).
=> Add Pablo's charts to ChartsHolder, plumbing in the API datasets.

src/components/Charts/utils.ts, src/components/LocationPage/ChartsHolder.tsx, src/enums/zones.ts, src/models/Projection.ts
A few misc. TODOs left, but otherwise done.  Can be merged as-is to keep things moving, or I can make revisions tomorrow.
=> Add copy text above charts.

src/assets/theme/palette.tsx, src/components/LocationPage/ChartsHolder.tsx, src/components/LocationPage/LocationPageHeader.js, src/components/LocationPage/LocationPageHeader.style.js, src/components/SignalStatus/SignalStatus.style.tsx, src/components/SignalStatus/SignalStatus.tsx, src/components/SummaryStats/SummaryStat.style.tsx, src/components/SummaryStats/SummaryStat.tsx, src/components/SummaryStats/SummaryStats.style.tsx, src/components/SummaryStats/SummaryStats.tsx, src/enums/status.ts
From @adpirz:
**Mobile**
**Embeds**
=> [WIP] Adding the stats boxes

src/enums/team.js, src/screens/About/About.tsx
=> Update to team bios and add missing header

src/models/Projection.ts
Okay, this looks a lot better, I think.
---
A more interesting example (I don't know what is up with Oklahoma!).
=> Add 7-day rolling average to test positive rate.

src/components/CountyMap/CountyMap.js, src/components/CountyMap/CountyMap.style.js
=> Fix #579: Split county map into two layers and outline selected county in the second one.

src/components/ClaimStateBlock/ClaimStateBlock.js, src/components/Footer/Footer.tsx, src/components/Header/SearchHeader.style.tsx, src/components/LocationPage/LocationPageHeader.style.js, src/components/MapSelectors/GlobalSelector.style.js
=> Ux polish for header and search bar

src/components/Header/HomePageHeader.tsx
I think this will change again in the future, but I had the pr before i realized it would
=> Updating the home page copy

src/components/Header/HomePageHeader.tsx, src/components/LocationPage/ChartsHolder.tsx
=> removing the jk chart description

src/components/Charts/ModelChart.style.js, src/components/Charts/ZoneChart.style.js
Josh asked for a final update for the font-size of the axes and beds annotation
=> font-size adjustments for axes and beds

src/App.css, src/assets/theme/palette.tsx, src/components/Charts/ModelChart.js, src/components/Charts/ModelChart.style.js, src/components/ClaimStateBlock/ClaimStateBlock.js, src/components/ClaimStateBlock/ClaimStateBlock.style.js, src/components/Disclaimer/Disclaimer.style.tsx, src/components/Disclaimer/Disclaimer.tsx, src/components/LocationPage/ChartsHolder.tsx, src/screens/Resources/Resources.tsx
- Adds metrics definitions
- Improved claim state UX
- Copy tweaks
=> Adds metrics definitions, improved claim state UX, and copy tweaks

src/components/ClaimStateBlock/ClaimStateBlock.style.js, src/components/LocationPage/ChartsHolder.tsx, src/components/ShareBlock/EmbedPreview.style.js
adds the share component to the bottom of the page
=> Adding back in the share component

cypress/integration/ModelPage_spec.js, src/screens/Contact/Contact.tsx, src/screens/ModelPage/ModelPage.js, src/screens/Resources/Resources.tsx
@schlosser updating the job descriptions + putting a link at the top of the contact us page to the FAQ.
Please run the contact us one locally if you can to check the styles came out right.
=> Jt jds update

cypress/integration/ModelPage_spec.js, public/index.html, src/components/Charts/ModelChart.js, src/components/ClaimStateBlock/ClaimStateBlock.js, src/components/Disclaimer/Disclaimer.style.tsx, src/components/Disclaimer/Disclaimer.tsx, src/components/Header/HomePageHeader.tsx, src/components/LocationPage/ChartsHolder.style.tsx, src/components/LocationPage/ChartsHolder.tsx, src/components/LocationPage/LocationPageHeader.js, src/components/Map/Map.js, src/components/ShareBlock/ShareBlock.tsx, src/components/ShareBlock/ShareModelBlock.js, src/components/SummaryStats/SummaryStats.style.tsx, src/components/SummaryStats/SummaryStats.tsx, src/enums/zones.ts, src/screens/About/About.tsx, src/screens/Contact/Contact.tsx, src/screens/HomePage/CriteriaExplanation/CriteriaExplanation.style.tsx, src/screens/HomePage/CriteriaExplanation/CriteriaExplanation.tsx, src/screens/HomePage/HomePage.js, src/screens/ModelPage/ModelPage.js, src/screens/Resources/Resources.tsx
Still a few more things needed but majority of changes from webapp text doc.
=> Lots of copy updates

public/index.html
as shown in https://developers.facebook.com/docs/sharing/webmasters/
and similarly https://www.drupal.org/project/metatag/issues/2457555
=> Update open graph image type

src/utils/model.js
=> Make sure last updated date isn't in the future.

src/components/ClaimStateBlock/ClaimStateBlock.js, src/components/LocationPage/ChartsHolder.tsx, src/components/LocationPage/NoCountyDetail.tsx, src/utils/index.ts
* Also refactored out a getFormattedCountyName() helper function.
Fixes #658
=> Fix county name in ClaimStateBlock.

src/models/Projection.ts
Without this, 25 states have gaps.  With it, none do.
We can undo this if/when https://github.com/covid-projections/covid-data-model/issues/340 gets fixed.
=> Interpolate gaps of 1-2 datapoints in the rt series charts.

src/components/Map/Map.js
This reverts commit 720dad03709d6053377f37b7298c6c5d1cf6735b.
=> Revert "Clickety click"

src/components/LocationPage/ChartsHolder.tsx
just noticed that we weren't formatting numbers here. #680
=> adding in commas to ICU numbers

src/components/Header/HomePageHeader.style.tsx, src/components/Header/HomePageHeader.tsx, src/components/Map/Map.js, src/components/Map/Map.style.js, src/screens/HomePage/CriteriaExplanation/CriteriaExplanation.style.tsx, src/screens/HomePage/HomePage.js
Puts them above the fold on mobile, and cleans up the homepage header.
=> Homepage criteria

src/components/LocationPage/ChartsHolder.tsx
=> New copy on model page

src/enums/team.js
=> JKT title change

src/screens/About/About.tsx
=> about page updates

src/components/AppBar/AppBar.tsx, src/components/Footer/Footer.tsx
To make the blog feel part of our site!
=> Nav links to blog open in same tab

src/api/index.ts, src/assets/data/data_url.json, src/components/LocationPage/ChartsHolder.tsx, src/components/LocationPage/constants.ts, src/enums/zones.ts, src/models/Projection.ts
Adds the ICU headroom calculation based off of conversations. Note that this uses Nevada's actuals (which are a little sparse). This also dramatically reduces the ICU metric.
=> Adding ICU headroom calculation

src/models/Projection.ts
fill both the timeseries and the actualTimeseries and the dates with every single date from timeseries day by day
=> padding all the datasets

src/models/Projection.ts, src/screens/Embed/Embed.js, src/utils/model.js
https://trello.com/c/g44w2D1c/54-stop-all-use-of-v0-api
@ghop02 If you do me the favor of reviewing this, you can have the honor of deleting execute_summaries on the backend. 😛
=> Stop using /case_summary/ API endpoints in favor of API v1.

src/components/AppBar/AppBar.style.tsx, src/components/ClaimStateBlock/ClaimStateBlock.style.js, src/components/Header/SearchHeader.style.tsx, src/components/LocationPage/ChartsHolder.style.tsx, src/components/LocationPage/NoCountyDetail.style.tsx, src/components/Outcomes/Outcomes.style.js, src/components/ShareBlock/ShareBlock.style.tsx
Try printing the model page! it will be less janky
=> better @media(print) rules

package.json, yarn.lock
https://trello.com/c/gQdgpH03/86-set-up-git-hook-for-linting
=> Set up husky pre-commit hook to fix formatting / lint on staged files before committing.

src/components/AppBar/AppBar.style.tsx, src/components/Charts/ZoneChart.style.js, src/components/LocationPage/ChartsHolder.style.tsx
when printing!
It's like, kinda nice now!
=> @media print: fix chart size and app bar

src/screens/About/About.tsx
From https://trello.com/b/pPyaxWaK/copy
=> About page updates from Anna

src/common/metrics/case_growth.ts, src/common/metrics/hospitalizations.ts, src/common/metrics/positive_rate.ts, src/components/LocationPage/ChartsHolder.tsx
- Moves chart disclaimer copy out of ChartsHolder component and into common/metrics
=> Move chart disclaimer copy

public/index.html, src/common/metrics/contact_tracing.ts, src/components/Disclaimer/Disclaimer.tsx, src/components/LocationPage/ChartsHolder.tsx, src/screens/HomePage/CriteriaExplanation/CriteriaExplanation.tsx
The DISCLAIMERs are a bit messy, will be easier to clean up once merged.
=> contact tracing copy, fix google fonts

src/common/metrics/contact_tracing.ts, src/components/Charts/zoneUtils.js, src/components/SummaryStats/SummaryStats.style.tsx
- make the text show up in the share widget
- remove 48hrs from the title
- change the tooltip
- update the threshold 
- center align the metrics
=> threshold tweaks from max + lil UX fixes + fixing the share

src/screens/internal/ShareImage/ShareImage.style.ts, src/screens/internal/ShareImage/ShareImage.tsx
- Edits sharecard image scale to fit contact tracing
=> Sharecard Image Fix

src/components/Charts/ChartICUHeadroom.tsx, src/components/Charts/ChartPositiveTestRate.tsx, src/components/Charts/ChartZones.tsx, src/components/Charts/index.tsx, src/components/LocationPage/ChartsHolder.tsx, src/screens/internal/AllStates/AllStates.js
Please review this after #790
NOTE: #790 needs to be merged first, and then we need to change the base branch to `develop` in this PR
=> Chart Remake - ICU Utilization

src/components/Charts/ChartContactTracing.tsx, src/components/Charts/index.tsx, src/components/LocationPage/ChartsHolder.tsx
Review after #816 - rebase once #816 is merged
=> Chart Remake - Contact Tracing

src/common/metric.ts, src/common/metrics/future_projection.ts, src/components/Charts/MetricChart.tsx, src/components/Charts/index.tsx, src/screens/internal/AllStates/AllStates.js, src/screens/internal/CompareModels/CompareModels.js
* Used for /compare and /all and will be used in my share charts pages.
* Not used in ChartsHolder yet because it'd require additional refactoring to make it worthwhile.
=> Create MetricChart helper component and use it in a few places.

src/common/metric.ts, src/common/models/Projection.ts, src/common/models/Projections.ts
This makes some of the chart sharing code cleaner.
=> Add getMetricValue() and ALL_METRICS helpers.

.github/workflows/update-snapshot.yml
this should add the qa and raw qa to the output of the slack message
=> adding the raw data qa and qa links to the github action slack message

src/common/metrics/case_growth.ts, src/components/Disclaimer/Disclaimer.tsx, src/components/LocationPage/ChartsHolder.tsx, src/screens/About/About.tsx
Cards currently in "implemented" here: https://trello.com/b/pPyaxWaK/copy
=> about page copy and footer tweaks

src/common/utils/makeChartShareQuote.js, src/components/AppBar/AppBar.tsx, src/components/LocationPage/SocialButtons.js, src/components/ShareBlock/ShareBlock.tsx, src/components/ShareBlock/ShareModelBlock.js
- Updates share copy for footer links
- Updates share copy for hospitalization projections chart
=> Share Copy Updates

src/common/team.js
Quick typo changed connected to Issue.
Fixes #791
=> Updated Max's Bio Typo via About Page

src/common/models/Projections.ts
See https://trello.com/c/ybqacRAN
=> Disable ICU metric in Montana's overall alarm level score.

src/screens/HomePage/CriteriaExplanation/CriteriaExplanation.tsx
Per https://trello.com/c/L81yb97f/16-retitling-indicator-1-on-the-homeoage
=> homepage criteria update

src/common/metrics/positive_rate.ts
updates test positive percent to use same decimal as summary status test
positive percent
=> resolves #707

src/components/Disclaimer/Disclaimer.tsx
- Adds: (for contact tracing data, we partner with testandtrace.com)
=> Copy update: chart disclaimer

src/components/Charts/ChartFutureHospitalization.tsx
From https://covidactnow.slack.com/archives/C0110QQAPJA/p1591317144123700
=> Fix the copy of the hospitalizations tooltip

package.json, src/common/locations.ts, src/components/LocationPage/NewLocationPageHeader.tsx, src/components/Newsletter/Newsletter.js, src/components/Newsletter/Newsletter.style.tsx, src/components/ShareBlock/ShareBlock.tsx
some trickery to get the form to work right, but allow users to sign up to different states/counties
=> allow users to sign to email list for alerts or to generic newsletter

src/components/Disclaimer/Disclaimer.tsx, src/components/LocationPage/ChartsHolder.tsx
- Makes disclaimer copy change apply only to contact tracing chart
=> Chart footer copy update

src/App.js, src/screens/HomePage/HomePage.js
if you link to /alert from the homepage it will take you to the alert signup section
=> adding a scroll to alert sign up

src/App.js, src/screens/HomePage/HomePage.js
* adding a scroll to alert sign up
Co-authored-by: Susan Goldblatt <sgoldblatt@Susans-MacBook-Pro.local>
=> adding a scroll to alert sign up (#923)

src/common/models/Projection.ts
Adjust decomp based on new analysis, pending a more dynamic decomp factor
=> Adjust decomp factor from 30% to 25%

src/common/models/Projection.ts
Final tweaks to temporary static decomp %s
=> Final tweaks to decomp

src/common/team.js, src/screens/About/About.style.tsx, src/screens/About/About.tsx, src/screens/About/TeamTable/TeamTable.style.tsx, src/screens/About/TeamTable/TeamTable.tsx
- Adds new About page layout with 'alumni' vs 'active' team lists and 'additional advisors' list
=> About Page Layout

src/common/team.js
- Fixes incorrect linkedin link
=> About Page Fix

src/screens/Contact/Contact.tsx
=> Updating Donation Link

src/components/LocationPage/ShareButtons.style.js
- Fixes centering of share icons
- Fixes width of share buttons so chart-header-text is now accessible/highlight-able
=> Share Buttons Fixes

src/components/Newsletter/Newsletter.js
This just fixes some warnings on development, some element properties need to be translated when using JSX, see https://reactjs.org/docs/dom-elements.html
=> Fix some react warnings on the newsletter component

src/common/metrics/hospitalizations.ts, src/components/Disclaimer/Disclaimer.tsx
Chart disclaimer href + ICU status copy update
=> Copy updates

src/api/schema/CANPredictionTimeseriesRow.d.ts, src/api/schema/CovidActNowCountiesTimeseries.d.ts, src/api/schema/CovidActNowStatesTimeseries.d.ts, src/common/metrics/contact_tracing.ts, src/common/models/Projection.ts
- Adds case density metrics (currentCaseDensityByCases, currentCaseDensityByDeaths) and calculations (calcCaseDensityByCases, calcCaseDensityByDeaths) into Projection.ts
=> Prevalence metric calculations

package.json, patches/createsend-node+0.8.2.patch, scripts/alert_emails/send_emails.ts, yarn.lock
The good news is it works.
The bad news is I had to use patch-package to patch the createsend-node package since it doesn't expose the response headers. 🤮
=> Add rate limiting handling to email alerts.

src/components/Newsletter/Newsletter.js
check the length before writing
=> if there are no locations don't write to firestore

src/common/metrics/location_summary.ts
- Removes 'herd immunity' language
=> Copy update

src/components/ShareBlock/EmbedPreview.style.js
- Adds quick fix to make sure embed's close-icon is always accessible
=> Quick fix - Embed close icon

scripts/alert_emails/readme.md
is this the things you need to be helpful?
=> adding more readme

scripts/alert_emails/send_emails.ts
moves the invalid emails as we run into them and places them into a different location. We could just delete them, but idk i got anxious.
=> move invalid emails out of firestore

src/screens/HomePage/CriteriaExplanation/CriteriaExplanation.tsx
- Updates Rt indicator copy on homepage
=> Rt Copy Change

src/common/models/ICUHeadroom.ts
This fixes an issue when CMDC and CCM have different ICU bed capacities.  We want to prefer CMDC since it is likely more up-to-date and because it should match up with the patient actuals we get from CMDC.
=> ICU Headroom: Use ICUBeds.capacity from the timeseries if it exists.

src/common/metrics/case_density.ts, src/common/models/Projection.ts, src/components/Charts/ChartCaseDensity.tsx, src/components/Charts/MetricChart.tsx, src/components/LocationPage/ChartsHolder.tsx
Small fixes for the case density chart
- Removed the uncertainty intervals (from the tooltip too)
- Adjusted the x-axis (the labels are not inside the charting area)
- Added an annotation for the current value to match the other charts
=> Prevalence - small chart fixes

src/common/models/Projections.ts
As proposed in https://docs.google.com/document/d/13a8K9O3X9KxgCXDBlVy2B_3XVVSuxpT7nSLonzvPEGQ/edit#
=> Green incidence gets you a green overall threat score.

public/index.html, src/components/Charts/ChartCaseDensity.tsx
Forgot to add keys to the zone annotations and removed a comma on the `index.html` template that was causing a warning as well.
=> Prevalence - minor dev fixes

src/common/metrics/case_density.ts
Change the upper limit for the CRITICAL level from 100 → `Infinity`.
=> Prevalence - Fix CRITICAL upperLimit

src/components/SummaryStats/SummaryStats.tsx
Update the summary stats component to include case density.
=> Prevalence - update summary stats

src/components/Header/HomePageHeader.tsx, src/components/SummaryStats/SummaryStats.style.tsx
a teensy style tweak to the header stats
=> Misc header fixes

src/components/LocationPage/LocationPageHeader.tsx
Changing from feedback form to email for issues with county data [Trello](https://trello.com/c/2hMkthct/277-change-see-something-wrong-please-let-us-know-which-currently-takes-users-to-a-google-form-that-is-hard-to-use-instead-lets-just)
=> County feedback change

src/common/metric.ts, src/common/metrics/case_density.ts, src/components/Disclaimer/Disclaimer.tsx, src/screens/HomePage/Announcements/Announcements.tsx, src/screens/HomePage/CriteriaExplanation/CriteriaExplanation.tsx
=> case incidence: copy update

src/components/LocationPage/ChartsHolder.tsx, src/components/LocationPage/LocationPageHeader.style.tsx, src/components/LocationPage/LocationPageHeader.tsx, src/screens/HomePage/Announcements/Announcements.tsx
- Removes todos that are no longer relevant
=> Remove TODOs

src/components/LocationPage/ChartBlock.tsx, src/components/LocationPage/ChartsHolder.style.tsx, src/components/LocationPage/LocationPageHeader.style.tsx
- Updates case density chart header to include "per 100k population"
=> Chart Header Update

src/components/LocationPage/ChartsHolder.tsx
from [Slack](https://covidactnow.slack.com/archives/C0177KERT89/p1595397535093000)
added a TODO to implement the proper fix later
=> case incidence: fix the scroll position for the share button

src/components/Disclaimer/Disclaimer.tsx
I assume this was an oversight and not intentional?
=> Link Harvard key indicators framework.

src/screens/HomePage/CriteriaExplanation/CriteriaExplanation.tsx
=> Updating homepage text to remove 'deaths'

src/common/metrics/case_density.ts, src/common/metrics/location_summary.ts
Misc. copy tweaks per edits in the webapp doc
=> Copy edits

src/components/LocationPage/LocationPageHeader.tsx
- Opens 'learn more' link in new tab
=> Header link fix

scripts/alert_emails/generate_daily_alerts.ts
Note the rest of the pipeline probably won't handle this yet (we need to verify the new images Josh created are set up, etc.)
=> Alerts: Include locations that changed from unknown in the generated alerts.json.

src/common/firebase.ts, src/components/Newsletter/Newsletter.js, src/screens/AlertUnsubscribe/AlertUnsubscribe.tsx
We were importing Firebase directly from 2 components, this PR fixes that and imports the "lean" Firebase from `common/firebase` instead.
=> fix firebase warnings - use more granular firebase import

src/screens/Contact/Contact.tsx
hopefully getting more people to donate!
=> updating donation text

src/common/models/Projection.ts
I noticed some issues while investigating #1152 and looking at Keweenaw County, MI which has had exactly 2 cases. One on 6/10 and one on 7/14.
Before:
Issues:
1. When we saw the very first case (after all null data points), we calculated a "7-day" average of 1 case/day because it was the only data point, and then it quickly plummeted to 1/2 case, 1/3 case, 1/4 case, etc. as we picked up more non-null data points in the average. I decided to backfill the null cases data points with zeros which also makes the graph match the rough timeline of our other graphs (March to now).
2. When cases went from 0=>1 or 1=>2 we considered the prior long stream of 0's or 1's to be a "gap" in the cumulatives, and tried to smooth it, which accidentally moved the new cases backwards in time. I added a …
=> Two data smoothing fixes to improve small county data.

src/screens/Resources/Resources.tsx
Updated the copy of the section _COVID Response Simulator_ following [Web Copy · Resources](https://docs.google.com/document/d/1_0EfCj0IHDqz4uWR-vX64XfDy36SNhNthd-bQIq9hHI/edit#)
=> update copy on resources

src/components/Compare/Compare.style.tsx, src/components/Compare/CompareMain.tsx, src/components/Compare/CompareTable.tsx, src/components/Compare/CompareTableRow.tsx, src/components/Compare/LocationTable.style.tsx, src/components/Compare/LocationTable.tsx
- Pin the current county
- Fixes the scrolling bar going all the way through the table header in modal
TODO (separate PR)
- Do not scroll when not in modal
- Fix the style (table border, modal size, etc)
=> WIP - Compare Fix scroll issues

src/screens/Contact/Contact.tsx
[Trello 351](https://trello.com/c/PPGnj6mi/351-implement-copy-changes-in-web-copy-contact-us) - Update the copy on the _Contact us_ page.
- [Web Copy // Contact us](https://docs.google.com/document/d/1YlX4zY9O5WeRvYg54Cc-pPRg7v9ZNADQjEP_-59WD4o/edit?ts=5f28a37c&pli=1#)
- The JD for the internship positions might not be finalized, I will get confirmation before merging, but that is not blocking to review.
=> copy update: contact us page

src/common/utils/compare.ts
- updates getStatesArr and getCountiesArr utils
=> Compare build fix

src/components/Compare/ModalCompare.tsx
- Fixes bug that made keystrokes undetectable after closing modal
=> Compare: keyboard bug fix

src/components/Compare/LocationTable.style.tsx, src/components/Compare/LocationTable.tsx
Remove some duplicated styles on the compare component
=> compare: cleanup duplicated styles

src/common/utils/compare.ts, src/components/Compare/Compare.style.tsx, src/components/Compare/CompareTable.tsx
- Generates state-specific disclaimer copy
[Mocks](https://www.figma.com/file/CypfjFVRBhsC3vArhoIPq1/County-tables?node-id=318%3A18515)
Todo:
=> Compare disclaimer copy

src/components/LocationPage/LocationPageHeader.style.tsx, src/components/LocationPage/LocationPageHeader.tsx, src/components/SummaryStats/LocationHeaderStats.tsx, src/screens/HomePage/CriteriaExplanation/CriteriaExplanation.tsx
https://trello.com/c/MiXZaYyU/359-remove-the-new-cases-has-been-added-prompt-on-location-pages
=> Remove "New key indicator added" update notification.

src/components/Compare/Compare.style.tsx, src/components/Compare/CompareTable.tsx, src/components/Compare/CompareTableRow.tsx, src/components/Compare/HeaderCell.tsx, src/components/Compare/LocationTable.style.tsx, src/components/Compare/LocationTable.tsx, src/components/Compare/ModalCompare.tsx
[Mocks - Fast Follows](https://www.figma.com/file/CypfjFVRBhsC3vArhoIPq1/County-tables?node-id=318%3A18515)
=> Compare tweaks

src/components/Explore/Explore.style.ts, src/components/Explore/ExploreChart.tsx
=> explore: add grid lines

src/common/metrics/contact_tracing.tsx, src/screens/HomePage/CriteriaExplanation/CriteriaExplanation.tsx
https://trello.com/c/lsXDEij8/361-implement-step-1-of-the-tracing-and-testing-prd
=> Implement initial changes to contact tracer metric copy.

src/common/metrics/contact_tracing.tsx, src/screens/HomePage/CriteriaExplanation/CriteriaExplanation.tsx
https://trello.com/c/lsXDEij8/361-implement-step-1-of-the-tracing-and-testing-prd
=> Deploy contact tracing copy changes. (#1261)

src/components/Explore/Explore.style.ts, src/components/Explore/Explore.tsx, src/components/Explore/Legend.tsx, src/components/Explore/SeriesChart.tsx, src/components/Explore/interfaces.ts, src/components/Explore/utils.ts
This PR adds the legend component for Explore. I added the legend by type with the series because they are related elements (the style of the series should match the style of the legend items), not sure if that's the best approach.
=> explore: legend component

src/screens/HomePage/Announcements/Announcements.tsx
This PR updates the copy of the announcement for the Puerto Rico launch.
=> update announcement - Puerto Rico launch

src/common/models/Projection.ts, src/components/Charts/ChartCaseDensity.tsx, src/components/Charts/Tooltip.style.ts, src/components/Charts/Tooltip.tsx
Addresses https://trello.com/c/O9nRsq19/358-implement-new-new-cases-tool-tip
=> Deploy: Enhance Daily New Cases Tooltip (#1300)

scripts/alert_emails/template.html
=> Show 'RISK INCREASED' / 'RISK DECREASED' as appropriate in email alerts instead of just `NEW RISK SCORE'.

scripts/generate_index_pages.ts
=> remove duplicated section in the code

src/common/colors.js, src/components/Charts/Charts.style.ts, src/components/Explore/Explore.style.ts, src/components/Explore/ExploreChart.tsx, src/components/Explore/SeriesChart.tsx, src/screens/internal/ShareImage/ExploreChartImage.tsx
- Updates color of grid+axis
- Updates opacity of bars in share image chart
=> explore: misc UX fixes

src/components/Charts/Charts.style.ts, src/components/Explore/Explore.style.ts, src/components/Explore/Explore.tsx, src/components/Explore/ExploreChart.tsx, src/components/Explore/utils.ts, src/components/LocationPage/ChartsHolder.tsx
- Add the today marker
- Remove missing data at the end of the series
- center the legend
- spacing fixes
- move the message for future hospitalizations chart below explore
=> explore: misc fixes

src/components/Charts/ChartCaseDensity.tsx, src/components/Charts/ChartContactTracing.tsx, src/components/Charts/ChartICUHeadroom.tsx, src/components/Charts/ChartPositiveTestRate.tsx, src/components/Charts/ChartRt.tsx, src/components/Charts/ChartZones.tsx, src/components/Charts/Tooltip.style.ts, src/components/Charts/Tooltip.tsx, src/components/MapSelectors/GlobalSelector.js
This PR edits tool tips according to the following: https://www.figma.com/file/kQGQ5qsDh7ir4MhjMM20Tl/5th-metric?node-id=108%3A3574
=> Edit tooltips

src/components/LocationPage/ChartsHolder.tsx
We are disabling explore until Monday to polish some details.
=> disable explore

src/common/utils/compare.ts
- Replaces urban/rural with metro/non-metro
=> Compare: copy change

src/common/models/ICUHeadroom.ts, src/common/models/Projection.ts
https://trello.com/c/B6Z1kW8o/
=> Disable ICU / Hospitalization charts for TN counties.

src/common/data/colleges_by_fips.json, src/common/locations.ts, src/common/utils/compare.ts, src/components/Compare/Compare.style.tsx, src/components/Compare/CompareMain.tsx, src/components/Compare/CompareTable.tsx, src/components/Compare/CompareTableRow.tsx, src/components/Compare/Filters.tsx, src/components/Compare/ModalCompare.tsx, src/components/Compare/ModalFaq.style.tsx, src/components/Compare/ModalFaq.tsx
- Adds college tag to counties in which the full-time-student enrollment is at least 5% of the fips population
- Adds FAQ modal to compare
To do:
=> compare: college tag

src/App.js, src/components/Compare/CompareMain.tsx, src/components/LocationPage/ChartsHolder.tsx, src/screens/HomePage/HomePage.js
This just adds the route and scrolling support.  Working on the query params stuff still, but figured I could break up the PRs.
=> Add support for scrolling to the compare table via /compare route.

src/screens/HomePage/CriteriaExplanation/CriteriaExplanation.tsx
Updates 2 'key indicator' names on homepage, per edits requested in Webapp doc
=> Copy change

src/common/locations.ts, src/components/AutocompleteLocations/AutocompleteLocations.tsx, src/components/Explore/Explore.style.ts, src/components/Explore/Explore.tsx, src/components/Explore/ExploreChart.tsx, src/components/Explore/LocationSelector.style.ts, src/components/Explore/LocationSelector.tsx, src/components/Explore/MultipleLocationsChart.tsx, src/components/Explore/utils.ts, src/components/LocationPage/ChartsHolder.tsx, src/components/Map/USACountyMap.js
- Addresses todos in ['to fix' list](https://paper.dropbox.com/doc/CAN-Explore--A7XpRu5CTc2KZpwRT96hIb0fAg-RIlOIJkMWHcX0AmXQA5PW)
Still left todo:
=> explore v2: misc TODOs

src/components/LocationPage/ChartsHolder.tsx, src/components/LocationPage/LocationPageHeader.style.tsx, src/components/LocationPage/LocationPageHeader.tsx
- Adds 'updates' section back into location-page header with explore v2 announcement
=> Header announcement: explore v2

src/screens/HomePage/Announcements/Announcements.tsx
A couple updates from steph now that we have the mariana islands blog post
=> updating northern mariana islands announcement

src/components/Compare/CompareMain.tsx
[fixes this issue](https://github.com/covid-projections/covid-projections/issues/1494)
=> compare: fix state bug

src/screens/HomePage/HomePage.js
- Removes unused imports from Homepage.js
=> Fixes lint error

src/common/utils/tracking.ts, src/components/AppBar/AppBar.tsx, src/components/Compare/CompareTable.tsx, src/components/Explore/Explore.tsx, src/components/ShareBlock/ShareBlock.tsx, src/components/ShareButtons/CopyLinkButton.js, src/components/ShareButtons/ShareButtonGroup.tsx
- [Analytics Help: About Events](https://support.google.com/analytics/answer/1033068#)
- [Measure Google Analytics Events](https://developers.google.com/analytics/devguides/collection/gtagjs/events)
=> analytics: instrument tracking

src/components/Banner/VoteBanner.tsx
- Updates vote by mail redirect link
=> Vote banner edit

src/common/locations.ts
We deleted a function that was needed to send the email alerts
=> fix email alert script 

src/screens/Resources/Resources.tsx
Adds updated copy to the API section on the resources page per [feedback](https://www.dropbox.com/scl/fi/9435oqxvdjh1uciyqazy6/-API-v2-Feedback.paper?dl=0&rlkey=oyisp30b4fmjp04jrdhqhtjvw)
=> Update api resources section

public/index.html, src/components/Analytics/PageviewTracker.tsx, src/components/Analytics/utils.ts, src/components/Compare/CompareTable.tsx, src/components/Compare/HeaderCell.tsx, src/components/Compare/LocationTable.tsx
- Add tracking for sorting and opening modals on Compare
- Restore the `titleCase: false` option (GA is case sensitive - I removed this option thinking that GA would consolidate the events)
- Remove the Full Story script
=> analytics: track sort and modal events for compare

src/common/models/Projection.ts
Removes some more unused projection code - will make it easier to move over to new API
=> Removing projection uses

package.json, src/components/Analytics/index.ts, src/components/Analytics/utils.ts, src/components/AppBar/AppBar.style.tsx, src/components/AppBar/AppBar.tsx, src/components/AppBar/DonateButton.tsx, src/components/AppBar/SocialIcons.tsx, yarn.lock
- Replaces social icons with donate button in AppBar
- Pulls social-icon code out into SocialIcons.tsx to add back in at a later time
=> Donate button

src/components/Compare/CompareTableRow.tsx, src/components/Compare/LocationTable.tsx, src/screens/HomePage/HomePageThermometer.tsx
We had some components without key for their children
=> add keys to some elements to reduce warnings

public/admin/config.yml
- Sets designated content entry branch in cms config
=> CMS: set branch

package.json, yarn.lock
=> Update material UI core version

src/common/utils/recommend.ts, src/components/Recommend/index.ts
This PR only adds the structure of the functions so it's not blocking while we implement the components.
=> add utility functions to get recommendations

src/App.js, src/common/urls.ts, src/components/LocationPage/ChartsHolder.tsx, src/components/Recommend/Recommend.style.tsx, src/components/Recommend/Recommend.tsx, src/components/ShareButtons/FacebookShareButton.tsx, src/components/ShareButtons/ShareButtons.style.tsx, src/components/ShareButtons/TwitterShareButton.tsx, src/components/ShareButtons/index.ts, src/components/SmallShareButtons/SmallShareButtons.style.tsx, src/components/SmallShareButtons/SmallShareButtons.tsx, src/components/SmallShareButtons/index.ts
- Adds share buttons, share URL, /recommends route, scrollTo, more styling
=> Recommends: inline cont.

src/components/Dialog/Dialog.tsx, src/components/Dialog/LockBodyScroll.tsx, src/components/Recommend/Recommend.tsx, src/components/Recommend/RecommendModal.tsx, src/components/Recommend/RecommendTabs.tsx
- The dialog closes on <kbd>esc</kbd> and when clicking the backdrop
- The close button shows the pointer when hovering
- The dialog locks body scroll
- analytics: track selecting tabs
- analytics: track opening the sources modal
=> recommend: several fixes for the modal component

src/components/Recommend/Recommend.tsx
=> recommend: add the modal for the feedback form

src/screens/Terms/Terms.tsx
* Update terms
* UPdate last updated datae
=> Deploy updated terms

src/common/utils/recommend.ts, src/components/LocationPage/ChartsHolder.tsx
Todo: decide on share quote/behavior for locations with level unknown
=> Recommends: share quote

src/components/MapSelectors/datasets/us_states_dataset_01_02_2020.json
Per [requested updates](https://trello.com/c/6fpWpJPX/467-correct-population-totals-for-cnmi)
=> Fixing northern mariana islands population

src/components/LocationPage/ChartsHolder.tsx, src/components/Recommend/Recommend.style.tsx, src/components/Recommend/Recommend.tsx
- Replaces feedback modal with external link
- Removes recommendations for counties
- Adds tracking for feedback button
=> Recommends edits

src/common/models/Projection.ts, src/components/Explore/utils.ts
* Always set last value to current value even if value is null
* Filter out any null values from explore series
=> Update daily calculations + drop all nulls from explore series (#1689)

src/common/utils/recommend.ts, src/components/Dialog/Dialog.style.ts, src/components/Dialog/Dialog.tsx, src/components/LocationPage/ChartsHolder.tsx, src/components/Recommend/Recommend.tsx, src/components/Recommend/RecommendModal.style.ts, src/components/Recommend/RecommendModal.tsx
- Adds location/level-specific copy to the modal (at the end of each source description)
- Removes set height/scroll from descriptions containers in mobile modal
- Solves for gaps/white-space between recommendations
- Other misc style edits
=> Recommends: modal edits cont.

src/components/Compare/CompareTable.tsx
=> Deploy fix for compare crash on homepage.

public/admin/config.yml
- Points branch in config.yml back to `cms-content-entry` (now incl. all current recommends copy + learn config)
=> CMS branch edit

src/components/Recommend/Recommend.style.tsx
fixes this [icon sizing issue seen on firefox](https://www.dropbox.com/s/a5me8plgcldzof0/Screen%20Shot%202020-10-19%20at%2012.05.11%20PM.png?dl=0)
=> Recommends icon size fix

src/screens/Learn/Faq/Faq.tsx
We need to confirm the final URL and meta with the team before shipping, this just puts the code in place for it
=> learn: add faq page meta tags

src/components/Breadcrumbs/Breadcrumbs.style.ts, src/components/Breadcrumbs/Breadcrumbs.tsx, src/components/Breadcrumbs/index.ts, src/screens/Learn/Faq/Faq.style.tsx, src/screens/Learn/Faq/Faq.tsx
- Implement breadcrumbs component
- Adjust spacing
=> implement breadcrumbs component

src/components/SharedComponents/Accordion.style.tsx
- padding and alignment for the accordion component
=> learn: small styling fixes

src/common/utils/recommend.ts
for consistency + my sanity :)
follow up to #1756
=> Re-names variable

src/assets/theme/sizes.tsx, src/components/AppBar/MobileMenu.tsx, src/components/AppBar/NavBar.style.ts, src/components/AppBar/NavBar.tsx
- Adds to desktop+mobile navbars
=> Adds learn to navbars

package.json, scripts/cms/check-internal-links.ts, yarn.lock
```sh
$ ./node_modules/.bin/ts-node-script ./scripts/cms/check-internal-links.ts
```
=> implement a script to validate glossary links

src/components/Markdown/MarkdownLink.tsx, src/components/Markdown/utils.ts
Fixes internal links on the markdown component
=> fix custom link component on markdown

src/components/Analytics/utils.ts, src/screens/Learn/Glossary/Glossary.tsx
Adds tracking for when users expand glossary terms.
=> analytics: track expanding glossary terms

src/components/SharedComponents/Accordion.style.tsx, src/screens/Learn/Learn.style.tsx
- Adds spacing between paragraphs
=> Markdown style edit

cypress/integration/ModelPage_spec.js, src/screens/HomePage/HomePage.js, src/screens/LocationPage/utils.ts
[Trello Card](https://trello.com/c/FWFg5otu/542-update-page-meta-tags-oct-28) - Meta tag update
The requested changes are on yellow in the [Meta Descriptions](https://docs.google.com/document/d/1I1TY45EzPIW6dUAwb6HqULV1MWYsbU3cAWxz49ixmH0/edit) doc and copied to Trello.
=> update the home and location pages title and description

src/common/colors.js, src/components/Compare/Compare.style.tsx, src/components/Compare/ModalFaq.style.tsx, src/components/Compare/ModalFaq.tsx, src/components/Explore/Explore.style.ts, src/components/LocationPage/LocationPageHeader.style.tsx, src/components/SharedComponents/Accordion.style.tsx, src/components/SharedComponents/Accordion.tsx, src/screens/Learn/Landing/SectionButton.style.tsx
- Update the color of the expand icon for the accordion component
- Increase the padding for the CTA button on the learn landing page
=> learn: style fixes

src/components/Breadcrumbs/Breadcrumbs.style.ts, src/components/Breadcrumbs/Breadcrumbs.tsx, src/screens/Learn/Faq/Faq.tsx, src/screens/Learn/Glossary/Glossary.tsx
Update the breadcrumbs component to show only the parent level. [Figma](https://www.figma.com/file/ak4c25AkVqwVcg2GzjQ3JB/Learn-%26-Products?node-id=218%3A4573)
=> learn: update the breadcrumbs

src/App.js
`/learn/case-studies` → `/case-studies`
=> update the base url for case studies

src/components/Markdown/Markdown.style.ts, src/components/Markdown/MarkdownContent.tsx, src/components/Markdown/index.ts, src/components/SharedComponents/Accordion.style.tsx, src/components/SharedComponents/Accordion.tsx, src/screens/Learn/CaseStudies/CaseStudy.style.ts, src/screens/Learn/CaseStudies/CaseStudy.tsx, src/screens/Learn/Landing/Landing.tsx, src/screens/Learn/Learn.style.tsx
Updates the styles of the case study (singular) page, and updates the accordion styles.
=> case studies - styling

src/components/Banner/VoteBanner.style.tsx, src/components/Banner/VoteBanner.tsx, src/components/ElectionCountdown/ElectionCountdown.tsx, src/screens/HomePage/HomePage.js, src/screens/HomePage/HomePage.style.js
Adds banner that will appear when election countdown hits zero
=> Election day banner

src/screens/Learn/CaseStudies/CaseStudy.style.ts, src/screens/Learn/CaseStudies/CaseStudyCard.tsx, src/screens/Learn/Learn.style.tsx
- Add the logo to the case study cards
- Minor styling updates
=> case studies: add logo to case study card

src/screens/HomePage/HomePage.js, src/screens/HomePage/HomePage.style.js
Removes election day banner + reinstates donate banner
=> Banner swap

scripts/alert_emails/template.html
[Trello](https://trello.com/c/Cm0vZo44/549-alert-emails-add-copy-to-indicate-the-frequency-of-the-emails) - Add copy to indicate the frequency of email alerts
This PR adds a note telling users that we only send email alerts on Mondays and Thursdays (users email us asking why sometimes it doesn't work). I sent myself a test email, this is what it looks like:
=> update the alert email copy

src/cms-content/learn/learn-case-studies.json
Cherry-picks @amandafass commit with case studies edits to uncouple it from products content entry
=> Case studies copy update

src/components/MapSelectors/GlobalSelector.js
[trello item](https://trello.com/c/TfH1UiqD/572-search-dropdown-doesnt-populate-with-state-counties-using-new-url-format)
=> Fix search bar bug

src/screens/HomePage/HomePage.js
[Trello](https://trello.com/c/tjlvvdep/575-update-home-page-meta-tag-description) - Update home page description meta tag
=> update home page meta tag description

src/cms-content/learn/learn-faq.json, src/cms-content/learn/learn-landing.json
Cherry-picks 2 of @KarenCheney 's commits from #1882 that are being blocked by learn:products work
=> FAQ copy changes

src/cms-content/donate/donate-page.json
[trello](https://trello.com/c/Fp9Hpud5/579-update-the-donation-copy-to-ask-for-a-minimum-amount-when-donating-by-check) - Update the donation copy for check donations
=> update copy for donations by check

src/components/Header/HomePageHeader.tsx, src/screens/HomePage/CriteriaExplanation/CriteriaExplanation.tsx
Changes instances of 'indicator' to 'metric' on the homepage
=> Homepage copy edit

.storybook/main.js, .storybook/preview-head.html, .storybook/preview.js, package.json, src/assets/theme/index.tsx, src/components/Button/Button.stories.mdx, src/components/Button/Button.style.ts, src/components/Compare/CompareTable.tsx, src/components/LocationPage/ChartBlock.tsx, src/components/Recommend/Recommend.style.tsx, src/components/Recommend/Recommend.tsx, src/components/Typography/Typography.stories.mdx, src/components/Typography/Typography.style.ts, src/components/Typography/index.ts, src/screens/HomePage/Announcements/Announcements.style.tsx, src/screens/HomePage/Announcements/Announcements.tsx, src/screens/HomePage/CriteriaExplanation/CriteriaExplanation.style.tsx, src/screens/HomePage/CriteriaExplanation/CriteriaExplanation.tsx, src/screens/HomePage/HomePage.style.js, yarn.lock
This PR configures the component library and centralizes the high-level styling elements. This is intended to be a starting point, so it doesn't include all the variables and components that we will need. There are two main things implemented here:
- Create high-level elements on the theme (besides the low-level variables from Material UI)
- Setup Storybook with the accessibility add-on
The Material UI theme offers low-level variables for styling, but those variables are not always easy to interpret or use. The Material UI theme variables are applied to all the Material UI components, so attempting to change those variables might break some components.
The idea is to keep the `theme` as the central place to define common styling primitives, but to add convenience variables so they can be …
=> component library setup

src/components/LocationPage/LocationPageHeader.tsx
It matches a bit better what we want to communicate
=> rename announcement -> alert

scripts/alert_emails/template.html
https://trello.com/c/ejdEJAFW/627-update-email-footer-to-include-5th-level-language
=> Update 4-color to 5-color in alert emails.

src/App.js, src/components/AppBar/MobileMenu.tsx, src/components/AppBar/NavBar.tsx, src/components/Footer/Footer.tsx, src/screens/Learn/Articles/ArticlesLanding.tsx, src/screens/Learn/CaseStudies/CaseStudiesLanding.tsx, src/screens/Learn/Faq/Faq.tsx, src/screens/Learn/Glossary/Glossary.tsx, src/screens/Learn/Landing/Landing.tsx
Switches 'explained' back to 'learn'
=> Learn rename

src/components/SharedComponents/SwitchComponent.stories.mdx, src/components/storybook.tsx
not the ideal solution, but it works for now.
=> add isModal to the Switch story

src/components/LocationPage/LocationPageHeader.style.tsx, src/components/LocationPage/LocationPageHeader.tsx, src/components/Thermometer/ThermometerImage.stories.mdx, src/components/Thermometer/ThermometerImage.style.ts, src/components/Thermometer/ThermometerImage.tsx, src/components/Thermometer/index.ts
- Move the location page thermometer to `components/Thermometer`
- Adds the component to Storybook
- Add the correct `role` and `aria-label`
=> add the thermometer image component to Storybook

cypress/integration/ModelPage_spec.js, src/screens/HomePage/HomePage.js, src/screens/LocationPage/utils.ts
See https://trello.com/c/B7F7ElPZ/615-seo-general-meta-descriptions-changes
=> update home and location meta tags

public/admin/config.yml, src/cms-content/learn/index.ts, src/cms-content/learn/learn-case-studies.json, src/screens/Learn/CaseStudies/CaseStudiesLanding.tsx
- Adds a boolean toggle in the CMS for hiding individual case studies
=> Add ability to hide case studies

src/components/Header/HomePageHeader.style.tsx, src/components/Header/HomePageHeader.tsx
SEO: Tweak homepage to include "map" and last updated date.
=> Deploy SEO: Tweak homepage to include "map" and last updated in header. (#2054)

src/components/LocationPage/LocationPageHeader.style.tsx, src/components/LocationPage/LocationPageHeader.tsx
From Igor - change the color of the alert icon to red, and adjusts the vertical alignment a bit
=> change the color of the alert icon

src/components/Header/HomePageHeader.style.tsx, src/components/Header/HomePageHeader.tsx
Homepage h1 title updates per Gaia, Josh, Igor, Debbie, etc. :-)
https://trello.com/c/Mh9nZ0jG/625-seo-homepage-set-up-the-map-to-be-recognizable-by-google
=> Update homepage h1 title.

src/common/metrics/case_density.tsx
[Trello item](https://trello.com/c/anDkf4ya/550-daily-new-cases-reactive-copy-updates)
=> Daily new cases chart copy update

package.json, scripts/cbsa/README.md, scripts/cbsa/mar2020.csv, scripts/cbsa/parse-metro-areas.ts, src/common/data/msa-data.json
Split the PR of parsing and adding MSAs to the region API into parsing only and addressing the feedback for #2083
=> implement a script to parse metro areas

src/common/regions/index.ts, src/common/regions/region_db.ts, src/common/regions/region_hooks.ts, src/common/regions/regions.test.ts, src/components/LocationPage/ChartsHolder.tsx, src/components/LocationPage/LocationPageHeader.tsx
* Splits up the existing regions file into a few separate files
* adds a few hooks for easily accessing regions from url params
* convert simple functions to properties on `Region` object
=> Refactoring regions

src/common/utils/makeChartShareQuote.ts, src/components/LocationPage/ChartBlock.tsx, src/components/LocationPage/ChartsHolder.tsx, src/components/LocationPage/ShareButtons.tsx, src/components/Newsletter/Newsletter.js, src/components/ShareBlock/ShareBlock.tsx, src/components/ShareBlock/ShareModelBlock.tsx
This pushes regions into the share section.  I've tested locally and it seems to work, but may need a closer set of eyes on this
=> Share buttons with regions

src/components/AppBar/NavBar.style.ts
[Trello](https://trello.com/c/gMWVkWUO/643-make-desktop-navbar-tabs-more-specifically-the-green-underline-on-select-behave-the-same-as-when-blog-is-selected-alignment-of-t)
=> Small fix to navbar tabs

src/App.js, src/common/regions/region_db.ts, src/common/regions/region_hooks.ts, src/screens/LocationPage/LocationRouter.tsx
This adds future support for the url segment in the route params
=> Add metro location url segment

src/screens/HomePage/Announcements/Announcements.style.tsx, src/screens/HomePage/Announcements/Announcements.tsx, src/screens/HomePage/Announcements/index.ts, src/screens/HomePage/HomePage.js
From Slack (Debbie) - Adding the CES announcement
=> update announcement (CES)

src/components/RegionMap/MetroAreaMap.tsx
=> zoom out to give context to where metro is

src/components/Compare/ModalFaq.tsx
The subheader read "Frequenlty asked questions", should be "Frequently asked questions".
=> Correct typo in ModalFaq.tsx

src/common/utils/index.ts, src/components/AutocompleteLocations/AutocompleteRegions.tsx, src/components/AutocompleteLocations/index.ts, src/components/Newsletter/Newsletter.js, src/components/Newsletter/utils.ts
- Update the `Newsletter` component to use `AutocompleteRegions`
- Changed the component to use `setState` instead of using class attributes to store state
- Moved the email validation logic to a more reusable place
- Subscribe to alerts to one or more locations
- Check that you are actually subscribed on Firebase (dev)
=> update the alert email signup form to support MSA

src/common/utils/index.ts, src/components/AutocompleteLocations/AutocompleteRegions.tsx, src/components/AutocompleteLocations/index.ts, src/components/Newsletter/Newsletter.js, src/components/Newsletter/utils.ts
Merges the existing email alert changes into develop
=> Update email alert with regions

src/screens/internal/ShareImage/ExploreChartExportImage.tsx, src/screens/internal/ShareImage/ExploreChartImage.tsx
This fixes the type issue for explore share image generation. I wasn't actually able to test locally, but properly adding types brought up the type issues that are causing the mismatch
=> Fix type issue for explore share images

src/screens/internal/ShareImage/ExploreChartExportImage.tsx, src/screens/internal/ShareImage/ExploreChartImage.tsx
=> Fix explore chart image

src/common/colors.js, src/common/location_summaries.ts, src/common/utils/compare.ts, src/components/Compare/CompareMain.tsx, src/components/Compare/CompareTable.tsx, src/components/Compare/Filters.style.tsx, src/components/Compare/Filters.tsx, src/components/Compare/HomepageSlider.style.tsx, src/components/Compare/HomepageSlider.tsx, src/components/Compare/LocationTable.tsx, src/components/Compare/ModalCompare.tsx, src/components/Search/SearchAutocomplete.tsx
=> Homepage compare with MSAs

src/screens/HomePage/utils.ts
Remove an unused function that was using 'common/locations'
=> remove unused function

src/common/utils/compare.ts
=> Change MSA compare label

src/components/Compare/CompareTable.tsx, src/components/Explore/Explore.tsx, src/components/LocationPage/ChartBlock.tsx, src/components/LocationPage/ChartsHolder.style.tsx
[Trello item](https://trello.com/c/b3HkNl1i/491-seo-update-the-location-page-to-use-the-correct-markup)
=> Use h2 for location page sections

scripts/generate_index_pages.ts, src/common/regions/index.ts, src/common/regions/region_db.ts, src/common/regions/utils.ts, src/components/Explore/Explore.tsx, src/components/Explore/utils.ts, src/components/Header/SearchHeader.tsx, src/components/Search/SearchAutocomplete.stories.tsx, src/components/Search/index.ts, src/components/Search/utils.ts, src/screens/HomePage/HomePage.js
- Centralized the logic with the global location search
=> add metros to explore location search

src/common/regions/regions.test.ts, src/common/regions/regions_data.ts, src/common/regions/types.ts, src/components/LocationPage/Notifications.tsx
- It add states to the `MetroArea` class
- Enables exposure notification alert if the metro area belongs in a state where that's enabled
=> show exposure notifications for metro areas in states where enabled

scripts/generate_index_pages.ts, src/screens/internal/ShareImage/ShareImage.tsx
This adds metros to the share image urls and generates metro level index files.
=> Add share image urls + index page generation

src/components/Search/utils.ts
[Trello item](https://trello.com/c/ZsEajpR0/705-search-in-metro-branch-from-district-of-columbia-is-broken)
=> Search bar fix (DC)

src/App.js
Adds a missing route for explore sharing
=> Fix metro area explore share url

src/common/regions/region_hooks.ts, src/components/LocationPage/ChartsHolder.tsx, src/components/LocationPage/LocationPageHeader.tsx, src/screens/LocationPage/LocationRouter.tsx
Removes the barely used RegionContext
=> remove regions context

src/screens/HomePage/HomePage.js
[Trello](https://trello.com/c/vM3aLOYZ/700-update-our-page-title-to-match-our-h1-on-the-homepage)
=> Update homepage title

src/components/ShareBlock/ShareBlock.tsx, src/components/SocialLocationPreview/SocialLocationPreview.tsx
[Trello](https://trello.com/c/J8l4yBHK/650-bonus-change-homepage-share-image-to-show-the-county-map)
[Test link](https://covid-projections-git-casulin-share-image-county-map.covidactnow.now.sh/internal/share-image/)
=> Change homepage share image to show county map

package.json, src/cms-content/learn/index.ts, src/screens/Learn/Faq/Faq.tsx, src/screens/Learn/Faq/FaqStructuredData.tsx, yarn.lock
[Trello](https://trello.com/c/n43p1uU9/661-seo-implement-structured-data-on-our-homepage-to-help-google-see-the-map)
Implements [structured data](https://developers.google.com/search/docs/data-types/faqpage) to our FAQ. Going to monitor over the next few days to see if this is picked up by google!
=> FAQ structured data (SEO)

src/screens/HomePage/utils.ts
[Trello](https://trello.com/c/gs1vKXWO/726-update-explore-presets-to-the-5-largest-metro-areas)
=> Update explore presets to 5 largest metros

src/components/LocationPage/LocationPageHeading.tsx
[Trello ticket](https://trello.com/c/bpBsjxWI/724-on-metro-pages-change-title-from-name-metro-area-state-abbr-to-name-metro-area-state-abbr)
=> Edits metro header casing

package.json, yarn.lock
It looks like we are not using axios anymore, removing!
=> remove the axios library

src/components/Compare/CompareMain.tsx
- Show metros by default in the homepage
- Sort metro areas by population (larger population first)
=> update compare in the homepage to show metro areas

src/screens/HomePage/HomePage.tsx, src/screens/HomePage/HomepageStructuredData.tsx, src/screens/Learn/Faq/FaqStructuredData.tsx
[Trello item](https://trello.com/c/n43p1uU9/661-seo-implement-structured-data-on-our-homepage-to-help-google-see-the-map)
Adds [ImageObject](https://schema.org/ImageObject) schema type with map URL to homepage
=> SEO: structured data pt. 2

src/api/schema/AggregateRegionSummary.d.ts, src/api/schema/AggregateRegionSummaryWithTimeseries.d.ts, src/api/schema/RegionSummary.d.ts, src/api/schema/RegionSummaryWithTimeseries.d.ts, src/cms-content/learn/learn-faq.json, src/cms-content/learn/metric-explainers.json, src/common/metrics/location_summary.ts, src/screens/Learn/MetricExplainer/ThermometerIntro.tsx
Edits per chat in #can-cms channel: updates thermometer copy and corresponding copy in learn (metric explainers + FAQ)
=> Thermometer edits (/level description edits)

src/App.js, src/components/AppBar/NavBar.tsx, src/screens/Learn/Explained/ExplainedLanding.tsx, src/screens/Learn/Explained/ExplainedRouter.tsx, src/screens/Learn/Updates/UpdatesLanding.tsx, src/screens/Learn/Updates/UpdatesRouter.tsx
from [Slack](https://covidactnow.slack.com/archives/C01KD1FAX08/p1610659621012100?thread_ts=1610639153.003100&cid=C01KD1FAX08)
=> update /explained and /updates metatags

.github/workflows/ci.yml, cypress/integration/ModelPage_spec.js, package.json, src/common/regions/regions.test.ts
- Fixed the unit tests for region
- Updated the URL on the Cypress tests to use the canonical URL
- Add unit tests to the CI workflow
=> add unit tests to ci and update cypress tests

src/components/Compare/CompareMain.tsx
[Trello](https://trello.com/c/rM1VqsO8/767-change-the-compare-table-on-location-pages-to-be-default-population-sorted)
=> Default compare sort

src/screens/HomePage/HomepageStructuredData.tsx
=> Homepage structured data, cont.

src/common/hooks/useGeolocation.ts, src/common/ip-api.ts, src/common/regions/utils.ts, src/components/Header/SearchHeader.tsx, src/screens/LocationPage/LocationPage.tsx
- Geolocates only on homepage
- Upgrades our use of ip-api to pro (unlimited lookups)
=> Geolocation updates

src/common/metrics/vaccinations.tsx
Based on the current state of the copy from [Vaccination Copy](https://docs.google.com/document/d/14d2VfKcl0eqTYUyvuEzR0-cxb95tmdARJ7rceaRwAvg/edit#)
=> update the copy for vaccinations (part 1)

src/common/hooks/useGeolocation.ts, src/common/ip-api.ts, src/common/regions/utils.ts, src/components/Header/SearchHeader.tsx, src/screens/LocationPage/LocationPage.tsx
- Adds `useGeolocation` back into location pages (since we now have unlimited lookups)
- Re-orders geolocated regions (metro, county, state)
=> Geolocation updates, cont.

src/screens/HomePage/Toggle/Toggle.stories.tsx, src/screens/HomePage/Toggle/Toggle.style.tsx, src/screens/HomePage/Toggle/Toggle.tsx
[Mocks](https://www.figma.com/file/JGqemgZwlG9e5DQbZpdKgy/Homepage-Above-the-fold?node-id=52%3A3710) - updated counties/states toggle
=> Updated homepage toggle

src/components/Compare/Compare.style.tsx, src/components/Compare/CompareTableRow.tsx, src/components/RegionItem/RegionItem.stories.tsx, src/components/RegionItem/RegionItem.style.tsx, src/components/RegionItem/RegionItem.tsx, src/components/SharedComponents/StyledRegionName/StyledRegionName.style.tsx, src/components/SharedComponents/StyledRegionName/StyledRegionName.tsx, src/components/SharedComponents/index.tsx
[Mocks](https://www.figma.com/file/JGqemgZwlG9e5DQbZpdKgy/Homepage-Above-the-fold?node-id=10%3A4741)
For use on the homepage to link to user's geolocated regions
=> Region link item

src/components/LocationPage/ChartBlock.tsx, src/components/SummaryStats/LocationHeaderStats.tsx
Replace the _Beta_ tag with _New Indicator_
=> update the vaccination tag to be "new"

src/screens/HomePage/HomePage.tsx
This PR adjusts the homepage meta tags and page description.
=> Adjust homepage meta

src/common/hooks/index.ts, src/common/hooks/useGeolocation.ts, src/common/hooks/useGeolocationInExplore.ts, src/common/regions/utils.ts, src/screens/HomePage/HomePage.tsx, src/screens/HomePage/utils.ts
[Trello item](https://trello.com/c/idum9uby/821-make-explore-reflect-the-users-location)
=> Geolocation in homepage explore

src/components/Compare/CompareTableRow.tsx, src/components/RegionItem/RegionItem.style.tsx, src/components/RegionItem/RegionItemSkeleton.tsx, src/components/RegionItem/SkeletonItem.stories.tsx, src/components/SharedComponents/StyledRegionName/StyledRegionName.style.tsx, src/components/SharedComponents/StyledRegionName/StyledRegionName.tsx
- Adds skeleton for region item on homepage
- Edits region item hover state per figma updates
=> Region item loading state

src/components/PageContent/PageContent.tsx, src/components/ShareBlock/EmbedPreview.tsx
[Trello](https://trello.com/c/xelBy2yp/594-footer-embed-link-bug)
=> Fix broken embed link

src/common/utils/compare.ts, src/components/Search/NewMenuItem/NewMenuItem.stories.tsx, src/components/Search/NewMenuItem/NewMenuItem.style.tsx, src/components/Search/NewMenuItem/NewMenuItem.tsx, src/components/SharedComponents/StyledRegionName/StyledRegionName.tsx
[Figma mocks](https://www.figma.com/file/JGqemgZwlG9e5DQbZpdKgy/Homepage-Above-the-fold?node-id=68%3A98)
=> New search menu item

src/common/colors.js, src/components/VaccinationBlock/VaccinationBlock.stories.tsx, src/components/VaccinationBlock/VaccinationBlock.style.ts, src/components/VaccinationBlock/VaccinationBlock.tsx, src/components/VaccinationBlock/index.ts, src/components/VaccinationBlock/utils.ts
Implement the vaccination block component - [mocks](https://www.figma.com/file/8BG3s3peEdA2LsaHsnZtm3/CAN-Vaccinate?node-id=1%3A387). 
Note that there are some components that look different (the buttons are missing the arrow) and some pending items, but it would be good to merge this to avoid blocking the integration with vaccine data.
=> implement vaccination block component

src/components/VaccinationBlock/LinkButton.tsx, src/components/VaccinationBlock/VaccinationBlock.style.ts, src/components/VaccinationBlock/VaccinationBlock.tsx
Add the chevron icon + tracking for clicks
=> vaccinations: button fixes + analytics

public/admin/config.yml, src/cms-content/vaccines/index.ts, src/cms-content/vaccines/msa.json, src/components/RegionVaccinationBlock/VaccinationBlock.tsx
This adds in the metro data from the google sheet. seems to work in the storybook widget!
=> adding in metro data

src/common/utils/recommend.ts, src/components/Recommend/Recommend.tsx, src/components/Recommend/RecommendModal.style.ts, src/components/Recommend/RecommendModal.tsx
Removes hghi/school related content from inline recommendations content + recommendations sources and methodology modal
=> Recommendations update: remove hghi as source

src/components/RegionVaccinationBlock/FeedbackBox.tsx, src/components/RegionVaccinationBlock/Header.tsx, src/components/RegionVaccinationBlock/StateVaccinationBlock.tsx, src/components/RegionVaccinationBlock/VaccinationBlock.tsx, src/components/RegionVaccinationBlock/utils.ts
Update the copy of the vaccination block to match the new copy (see the [Mocks](https://www.figma.com/file/8BG3s3peEdA2LsaHsnZtm3/CAN-Vaccinate?node-id=0%3A1) under "new"). I also updated the feedback form using the link from the [Phase 2 paper doc](https://www.dropbox.com/scl/fi/3iq9uzrtvmjpdi71qd6wq/-Phase-2-Launch-Plan.paper?dl=0&rlkey=gou6giiggng27u8m7eboalc53)
=> update the vaccination copy and feedback link

src/components/RegionVaccinationBlock/RegionVaccinationBlock.style.ts, src/components/RegionVaccinationBlock/StateVaccionationBlock.style.ts
Fixed the styling issues that Josh outlined in the [paper doc](https://www.dropbox.com/scl/fi/3iq9uzrtvmjpdi71qd6wq/_-Phase-2-Launch-Plan.paper?dl=0&rlkey=gou6giiggng27u8m7eboalc53#:uid=034192475567309122198418&h2=Notes-from-Josh)
=> vaccination: styling fixes

src/common/hooks/useGeolocation.ts, src/screens/HomePage/HomePage.tsx, src/screens/LocationPage/LocationPage.tsx
Adds a loading state to be used in new homepage UI
=> Add loading state to useGeolocation

src/cms-content/vaccines/county.json
My script to import the dataset didn't match county name with CA - this fixes it
=> fix county fips for CA vaccine data

src/cms-content/vaccines/state.json, src/components/RegionVaccinationBlock/RegionVaccinationBlock.tsx
=> Minor vaccination launch tweaks

src/common/metrics/positive_rate.tsx, src/common/metrics/vaccinations.tsx, src/common/models/Projection.ts, src/common/models/Projections.ts, src/components/Disclaimer/Disclaimer.tsx
Remove date from disclaimer
Add note to CT 
Fix vaccine ratio/pct mixup (#2646) …
=> Changes in develop

src/common/models/ProjectionsPair.ts, src/screens/internal/CompareSnapshots/CompareSnapshots.tsx
* Changes "States & Interesting Counties" into "States & Interesting Regions" and includes metros now.
* Adds the state (list) to the label of metros in compare.
* Clean up some code.
=> Compare Snapshots: Add metros to "States & Interesting Regions" list.

src/assets/theme/customStyleBlocks/getSearchAutocompleteStyles.ts, src/components/Dialog/LockBodyScroll.tsx, src/components/Search/Homepage/HomepageSearchAutocomplete.style.tsx, src/components/Search/Homepage/HomepageSearchAutocomplete.tsx
[Figma](https://www.figma.com/file/JGqemgZwlG9e5DQbZpdKgy/Homepage-Above-the-fold?node-id=68%3A98)
=> Mobile search bar update

package.json, scripts/alert_emails/email-service.ts, scripts/vaccination_alerts/README.md, scripts/vaccination_alerts/generate-users-to-email.ts, scripts/vaccination_alerts/generate-vaccine-alerts-info.ts, scripts/vaccination_alerts/utils.ts, yarn.lock
As I was going through the code, I restructured the existing functions a bit in a way that made slightly more sense to me - lmk if you like this approach!
=> Refactoring generate users to email

.github/workflows/send-test-vaccination-alert.yml
Implements a GitHub workflow to send vaccination alerts to a single email to make testing easier.
=> vaccination alerts: implement workflow to test alerts

src/common/metrics/vaccinations.tsx, src/common/models/Projection.ts
=> Add vaccine dose distribution copy.

src/components/LinkButton/LinkButton.tsx, src/components/LocationPage/LocationPageHeader.style.tsx, src/components/LocationPage/Notifications.tsx, src/screens/Learn/Glossary/Glossary.tsx
Pulling in some console warnings that @schamp fixed in https://github.com/covid-projections/covid-projections/pull/2739.
=> Fix some console warnings.

src/common/metrics/hospitalizations.tsx
https://sentry.io/organizations/covidactnow/issues/2153102723/
=> Fix crash on counties with zero ICU beds.

public/admin/config.yml, src/App.js, src/cms-content/learn/about-our-alerts.json, src/cms-content/learn/index.ts, src/cms-content/learn/learn-landing.json, src/screens/Learn/Alerts/Alerts.tsx
CMS config + UI for the [about our alerts section in this doc](https://docs.google.com/document/d/1OLD-3B1Pv4715BRU9ALjc900JhmggJUaSMU1qpNexrM/edit?ts=602c42e7#heading=h.2rhc67tm8djd)
=> Learn alerts section into CMS config

src/components/VaccinationEligibilityBlock/VaccinationEligibilityBlock.stories.tsx, src/components/VaccinationEligibilityBlock/VaccinationEligibilityBlock.style.ts, src/components/VaccinationEligibilityBlock/VaccinationEligibilityBlock.tsx, src/components/VaccinationEligibilityBlock/index.ts, src/components/VaccinationEligibilityBlock/utils.ts
Implement the `VaccinationEligibilityBlock` component and the utility function to parse the vaccination information and links.
=> vaccinations: implement info block container with basic info

package.json, scripts/vaccination_alerts/parse-vaccination-phases.ts, src/cms-content/vaccines/state-vaccine-phases.json, src/common/regions/region_db.ts
Adds in a script to refresh the CMS data with data from the spreadsheet.  In the future I'd love to automate this a bit more but it works as a cli command for now
=> Adding script to pull vaccine phases in from spreadsheet

src/components/TabsPanel/Panel.tsx, src/components/TabsPanel/TabsPanel.stories.tsx, src/components/TabsPanel/TabsPanel.style.ts, src/components/TabsPanel/TabsPanel.tsx, src/components/TabsPanel/index.ts
This component has an internal state to keep track of the selected tab, and has a handler to update external elements on tab selection (or add analytics).
=> implement TabsPanel component

src/components/TabsPanel/Panel.tsx, src/components/TabsPanel/TabsPanel.stories.tsx, src/components/TabsPanel/TabsPanel.style.ts, src/components/TabsPanel/TabsPanel.tsx, src/components/TabsPanel/index.ts, src/components/VaccinationEligibilityBlock/EligibilityPanel.tsx, src/components/VaccinationEligibilityBlock/VaccinationEligibilityBlock.style.ts, src/components/VaccinationEligibilityBlock/VaccinationEligibilityBlock.tsx, src/components/VaccinationEligibilityBlock/utils.ts
Implements the components to render the information blocks with vaccination info.
**Desktop**
**Mobile**
=> vaccination block: add the content to the info blocks + styling

package.json, yarn.lock
Might fix the deploy error, but not sure why it happened in the first place
=> Add types declaration

src/components/LocationPage/Notifications.tsx
Texas counties are starting to report cases again, but are way lower. I think we should keep them for now, add this alert, and not send out email alerts for Texas on Monday.
https://trello.com/c/TdspuIeM/952-texas-reporting-dip-winter-weather-feb-2020
=> Add Texas Alert

src/components/VaccinationEligibilityBlock/VaccinationEligibilityBlock.tsx
=> Deploy fix for states with missing vaccination info

src/cms-content/vaccines/state-vaccine-phases.json
Based on Pablo's translation of https://www.vacunatepr.com/fases-vacunacion-covid-19 and information from https://states.aarp.org/puerto-rico/covid-19-vaccine-distribution.
=> Add PR Phase Information

src/components/AppMetaTags/AppMetaTags.tsx, src/components/Footer/FooterSocialLinks.tsx, src/components/ShareButtons/CopyLinkButton.tsx
these are ones that were more independent and easier to include in a smaller group
=> convert some components to typescript

src/assets/theme/overrides/MuiSwitch.tsx
Adds focus state to MUI switch component to improve keyboard navigation
=> Switch component focus state

src/assets/theme/overrides/MuiIconButton.tsx, src/common/hooks/index.ts, src/common/hooks/useEscToClose.ts, src/components/Compare/ModalFaq.tsx, src/components/ShareButtons/ShareButtonGroup.tsx, src/components/ShareButtons/ShareButtons.style.tsx, src/components/SignupsModal/SignupsModal.tsx
- adds focus state to ShareButtonGroup for better keyboard navigation + ability to close social button popup with esc key
- adds focus state 'normalize data' + NAMC checkboxes in explore
=> Share buttons + checkbox accessibility improvements

src/common/ccvi/index.ts, src/common/colors.ts, src/components/Vulnurabilities/CcviThermometer/CcviThermometer.stories.tsx, src/components/Vulnurabilities/CcviThermometer/CcviThermometer.tsx
- Starts defining each level in `common/ccvi/index`
- Adds thermometer:
=> CCVI thermometer

src/common/ccvi/index.ts, src/components/Vulnurabilities/CcviThermometer/CcviThermometer.tsx
- Adds role + title + aria tag to thermometer svg
=> Ccvi thermometer accessibility improvements

public/admin/config.yml, src/cms-content/tooltips/ccvi-tooltips.json, src/cms-content/tooltips/index.ts
=> CCVI tooltips in cms

src/assets/images/blogIconTwoTone.tsx, src/assets/images/faqIconTwoTone.tsx, src/assets/images/mapIconTwoTone.tsx
changing how these are exported, next.js complains about it
=> export cleanup

src/components/Compare/Compare.style.tsx, src/components/Compare/CompareTableRow.tsx
=> clean up compare style

src/screens/Donate/Donate.tsx
[Trello](https://trello.com/c/0gtBoiG1/942-update-donation-campaign-to-february-10k-goal) - Update the donation embed for March 2021. I created the campaign for March instead of February since we only have 6 days to go.
**Note**: Merge on Feb 28th!
=> update the donation embed for march 2021

src/components/LocationPage/LocationPageHeader.style.tsx, src/components/LocationPage/LocationPageHeader.tsx, src/components/SummaryStats/LocationHeaderStats.tsx, src/components/SummaryStats/SummaryStats.style.tsx, src/components/SummaryStats/SummaryStats.tsx
more of these I overlooked the first time around.
=> fix style props

src/common/index.ts
part of earlier cleanup I overlooked, no longer used anywhere in the source tree
=> Remove unused REVERSED_STATES

src/components/Compare/Compare.style.tsx, src/components/Compare/CompareTableRow.tsx, src/components/Compare/ModalFaq.tsx, src/components/Compare/columns.ts
1. Adds "Vulnerability Level" to compare.
2. Tweaks paddings / margins / font size so it fits.
=> Add vulnerability to compare table.

src/common/ccvi/renderRegionDescription.tsx, src/components/Compare/ModalFaq.tsx, src/components/VulnerabilitiesBlock/FooterLinks/FooterLinks.tsx, src/components/VulnerabilitiesBlock/VulnerabilitiesBlock.style.tsx, src/components/VulnerabilitiesBlock/VulnerabilitiesBlock.tsx
- Adds special copy for least+most vulnerable states/counties/metros [per copy doc](https://docs.google.com/document/d/1svP2I63M6JUGuNAM1QoAa6IOC8Vd7uYluenRi8wT_Zk/edit?ts=603d3b25#)
- Updates content of compare FAQ modal to match copy [at bottom of this doc](https://www.dropbox.com/scl/fi/3e2punws3eqjiomhlm46r/Vulnerability-Launch-Plan-%F0%9F%9A%80.paper?dl=0&rlkey=p4fe4sfz204jhe5nydmurcdwi)
- Updates redirect for 'How the vulnerability score is calculated' link (was surgo, now learn)
To test-
Most vulnerable:
[State](https://covid-projecti-git-casulin-vulnerabilities-feedback-cont-972012.vercel.app/us/texas-tx/?s=1633574
)
[Metro](https://covid-projecti-git-casulin-vulnerabilities-feedback-cont-972012.vercel.app/us/metro/lakeland-winter-haven_fl/?s=1633574) …
=> Vulnerabilities feedback cont.

src/components/Charts/ChartVaccinations.tsx
https://trello.com/c/gEGBLp5S/983-make-the-vaccination-chart-go-above-35
=> Allow vaccine chart to grow beyond 35%.

src/components/Charts/ChartVaccinations.tsx
=> adjust the right margin for the vaccination chart

src/components/AppBar/MobileMenu.tsx, src/components/AppBar/NavBar.tsx
[Trello](https://trello.com/c/FyVpjM0W/1063-a-b-testing-hamburger-menu) - Open the hamburger menu on hover. 
Note: It doesn't close on mouse out to avoid closing it when people try to click on the last item on the list, the menu will close upon navigation or if they click the X icon. Update: we close when the mouse exits below the modal as well
=> open the hamburger menu on hover

scripts/vaccination_alerts/vaccination-alert-template-source.html, src/common/colors.ts, src/components/Compare/CompareTable.tsx, src/components/EmailAlertsForm/EmailAlertsForm.style.ts, src/components/Explore/Explore.style.ts, src/components/Recommend/RecommendModal.style.ts, src/components/VaccinationEligibilityBlock/VaccinationEligibilityBlock.style.ts
- Removes `#828282`, sets `#4f4f4f` as `GREY_4` and replaces/consolidates accordingly
=> Remove redundant gray

src/common/utils/time/time-utils.test.ts, src/common/utils/time/time-utils.ts
This PR uses moment for now to ensure the formatting function works as it should.
=> Add time formatting function and test cases

src/components/Charts/Charts.style.ts
Bumps mobile stroke-width from 2px to 2.5px
=> Chart stroke width edit

src/components/Header/SearchHeader.style.tsx, src/components/Header/SearchHeader.tsx
=> simplify structure of location page search

src/components/AppBar/DonateButton.style.ts
[Trello](https://trello.com/c/c7L8AdIc/1043-revert-donate-button-treatment) - Revert donate button treatment
I also adjusted the button container, it was super tall on mobile.
=> restore outlined donate button

src/components/Compare/CompareTable.tsx
[Trello](https://trello.com/c/EDnr5bGw/1095-up-down-sort-buttons-are-invisible-in-compare-modal-until-hover) - Fix the compare table arrow buttons
**Modal**
**Inline**
=> fix arrow buttons for compare

src/common/level.ts, src/common/metrics/location_summary.tsx, src/common/utils/recommend.ts, src/components/Recommend/Recommend.tsx, src/screens/Learn/MetricExplainer/ThermometerIntro.tsx, src/screens/LocationPage/utils.ts
https://docs.google.com/document/d/1MfsA5X6jCaWg9NsVVJdd7j6IbA17daa5aDZPOObNEn8/edit
=> Remove "outbreak" copy from website and stick to risk terminology.

src/common/colors.ts, src/common/location_summaries.ts, src/common/locations.ts
these things appear unused or unneeded elsewhere, so eliminated some and reduced the visibility of others.
=> remove unused stuff and reduce scope and visibility

scripts/alert_emails/email-service.ts
This will let us gracefully handle if we're sending risk alerts and vaccine alerts at the same time.
https://trello.com/c/X9Yc96oq/1065-allow-concurrent-sending-of-vaccine-and-alert-emails
=> Make EmailService automatically fall back to half speed on throttling errors.

src/common/data/index.ts, src/components/RegionMap/RegionMap.tsx
I noticed TypeScript's `typeof import()` syntax could help here. 😁   Only minimally tested, but seems to work.
=> Use types for topo json files.

src/common/utils/time-utils.ts
This PR creates a private getter for Luxon's time units.
=> Create time unit option getter

src/screens/internal/ShareImage/LocationShareCardImage.tsx
fix typo in the code (semicolons render when used like this)
=> remove semicolon on component

src/components/VaccinationEligibilityBlock/VaccinationEligibilityBlock.tsx
Adding Note that we only update Vaccination Eligibility info on Mondays and Thursdays
=> Add Phases Update Cadence Note

src/components/Compare/CompareMain.tsx, src/components/Compare/CompareTable.tsx, src/components/Compare/ModalCompare.tsx
[Trello](https://trello.com/c/1msDteWX/1131-navigating-from-compare-modal-needs-to-dismiss-modal)
=> Compare modal bug fix

src/cms-content/tooltips/ccvi-tooltips.json, src/components/Compare/ModalFaq.tsx, src/screens/HomePage/Announcements/Announcements.tsx
Updates outcome data in vulnerabilities tooltip, compare FAQ modal, and announcement [per vulnerabilities doc](https://www.dropbox.com/scl/fi/3e2punws3eqjiomhlm46r/Vulnerability-Launch-Plan-%F0%9F%9A%80.paper?dl=0&eid=&oref=e&rlkey=p4fe4sfz204jhe5nydmurcdwi&t=461508448093233813373361#:t=461508448093233813373361)
=> Surgo outcome update

scripts/alert_emails/generate_daily_alerts.ts, scripts/alert_emails/utils.ts, src/cms-content/articles/index.ts, src/cms-content/articles/utils.ts, src/common/urls.ts, src/common/utils/index.ts, src/common/utils/model.ts, src/common/utils/recommend.ts, src/common/utils/time-utils.test.ts, src/common/utils/time-utils.ts, src/components/Charts/utils.ts, src/components/Explore/SingleLocationChart.tsx, src/components/Explore/utils.ts, src/components/Header/HomePageHeader.tsx, src/components/LocationPage/ShareButtons.tsx, src/components/NationalText/utils.tsx, src/screens/Learn/Faq/Faq.tsx, src/screens/Learn/Glossary/Glossary.tsx, src/screens/internal/CompareSnapshots/SnapshotVersions.tsx, src/screens/internal/ShareImage/LocationShareCardImage.tsx
This PR creates two utils, get start of time util which gets the start of a timeframe based on a specified time unit, and get time difference util which calculates the difference between two points of time in the specified time unit.
=> Create start of time util and get time diff util

src/cms-content/learn/index.ts, src/common/models/Projection.ts, src/common/models/ProjectionsPair.ts, src/common/models/ProjectionsSet.ts, src/common/models/utils.ts, src/common/regions/regions_data.ts, src/common/utils/index.ts, src/screens/HomePage/utils.ts
[Trello](https://trello.com/c/1v510l7O/1078-performance-tree-shaking-lodash) - Update lodash imports to import specific methods instead of the default import
In theory this should help us reduce the bundle size, but it doesn't do much. I want to add an ESLint rule to prevent importing the default export from Lodash, but will do that on a separate PR.
Change from `develop`
```
File sizes after gzip:
392.21 KB (+37 B)  build/static/js/main.a71098cc.chunk.js
350.62 KB (-1 B)   build/static/js/6.993b4bec.chunk.js
244.53 KB          build/static/js/25.2b91f6ba.chunk.js
138.39 KB          build/static/js/24.e68a3482.chunk.js
125.61 KB          build/static/js/26.e8acb76e.chunk.js
89.13 KB           build/static/js/2.08fc3838.chunk.js
75.9 KB            build/static/js/17.e8cdd55e.chunk.js
43.59 …
```
=> import methods from lodash and remove chain

src/common/locations.ts, src/common/utils/compare.ts, src/components/Compare/Compare.style.tsx, src/components/Compare/CompareMain.tsx, src/components/Compare/CompareTable.tsx, src/components/Compare/Filters.tsx, src/components/Compare/ModalCompare.tsx
I found these to be unused when looking at performance stuff, may as well remove.
=> remove unused functions and imports

src/components/LocationPage/ChartsHolder.tsx
This PR simply experiments with focusing on the email textbox once the user clicks the "Receive alerts" button.
=> Try finding email textbox element and focusing on it

src/components/Banner/SpringSurgeBanner.tsx, src/screens/HomePage/HomePage.tsx
- Add 4 more states that have increasing hospitalizations on the recommendation of Igor.
- Add Case Language to Banner
See https://trello.com/c/P5xQ8cLZ/1190-update-banner-to-highlight-states-with-rising-case-numbers
=> Deploy updated Banner (#3211)

src/cms-content/vaccines/state-vaccine-phases.json
We are doing daily updates this week because a lot is changing.
=> Update Vaccination Eligibility Phases

src/components/InfoTooltip/InfoTooltip.tsx, src/components/InfoTooltip/Tooltip.style.tsx
=> Tooltip info icon edit

src/common/models/Projection.ts, src/common/utils/time-utils.test.ts, src/common/utils/time-utils.ts
This PR migrates moment usages in projection.ts to time utils.
=> Switch from using moment to time utils in projection.ts

src/screens/HomePage/CriteriaExplanation/CriteriaExplanation.style.tsx, src/screens/HomePage/CriteriaExplanation/CriteriaExplanation.tsx
https://trello.com/c/dR7XspeH/1116-key-metrics-homepage-link
This basically just reverts 4624665c6cf32dc58b4e38ed6f7133f861d5a8b1 and tweaks the link / text.
=> Add risk / metric explainer link to homepage.

src/components/Banner/Banner.stories.tsx, src/components/Banner/Vaccinations100M.style.ts, src/components/Banner/Vaccinations100M.tsx, src/components/Banner/index.ts, src/components/LocationPage/SocialButtons.tsx, src/screens/HomePage/HomePage.tsx
[Trello](https://trello.com/c/xF3CfeRe/1214-vaccination-homepage-takeover) - 100M vaccinations banner
**Mobile**
**Desktop**
=> banner: 100M vaccinations

src/components/Banner/Vaccinations100M.style.ts, src/components/Banner/Vaccinations100M.tsx
=> remove emoji from the banner

src/components/VaccinationEligibilityBlock/AllAdultsEligibleBlock/AllAdultsEligibleBlock.stories.tsx, src/components/VaccinationEligibilityBlock/AllAdultsEligibleBlock/AllAdultsEligibleBlock.style.tsx, src/components/VaccinationEligibilityBlock/AllAdultsEligibleBlock/AllAdultsEligibleBlock.tsx, src/components/VaccinationEligibilityBlock/VaccinationEligibilityBlock.style.ts
(Storybook only) Adds alternate vaccination eligibility component for states with all adults eligible
=> Vaccination component UI update

src/cms-content/vaccines/state-vaccine-phases.json
* Update Vaccination Phase “Vaccine Information-State”
Co-authored-by: Ryan-Fuentes <79174308+Ryan-Fuentes@users.noreply.github.com>
=> Update Vaccination Eligibility (#3289)

src/components/Experiment/Experiment.tsx, src/components/LocationPage/ChartsHolder.tsx, src/components/LocationPage/Experiment/GetAlertsButton.style.tsx, src/components/LocationPage/Experiment/GetAlertsButton.tsx, src/components/LocationPage/Experiment/LocationPageHeaderVariant.tsx, src/components/LocationPage/LocationPageHeader.tsx
[Figma mocks of mobile-only experiment variation](https://www.figma.com/file/JGqemgZwlG9e5DQbZpdKgy/Redesign?node-id=1575%3A104549)
=> Get alerts button experiment

src/components/Banner/SpringSurgeBanner.tsx, src/screens/HomePage/HomePage.tsx
=> Update homepage banner.

src/cms-content/vaccines/state-vaccine-phases.json
* Update Vaccination Phase “Vaccine Information-State”
Co-authored-by: Ryan-Fuentes <79174308+Ryan-Fuentes@users.noreply.github.com>
Co-authored-by: N-Markey <81186685+N-Markey@users.noreply.github.com>
=> Vaccination Eligibility Updates (#3306)

scripts/alert_emails/send-test-email.ts, scripts/alert_emails/template.html, scripts/alert_emails/utils.ts
I'm not bothering doing the vaccination alert emails because they aren't going to be around much longer (most states already have open eligibility and all will by April 19).
=> Add utm source data to risk alert emails.

src/common/fullstory.ts
[Trello](https://trello.com/c/0d52IfTZ/1231-increase-fullstory-sampling-to-25) - Increase FullStory sampling to 2.5% of users
=> increase FullStory sampling to 2.5%

src/assets/theme/index.tsx, src/assets/theme/megaMenu.ts, src/assets/theme/palette.tsx, src/components/Button/Button.style.ts, src/components/Footer/Footer.tsx, src/components/MenuContent/Menu.style.tsx
- Removes mostly unused `ThemeColors`
- Moves mega menu theme into main theme (instead of accessing via palette)
=> More theme cleanup

src/cms-content/vaccines/state-vaccine-phases.json
* Update Vaccination Phase “Vaccine Information-State”
Co-authored-by: Jonathan Mak <jmak@stanford.edu>
Co-authored-by: N-Markey <81186685+N-Markey@users.noreply.github.com>
Co-authored-by: Ryan-Fuentes <79174308+Ryan-Fuentes@users.noreply.github.com>
=> Update Vaccination Eligibility Information (#3332)

src/screens/internal/AllStates/AllStates.tsx
we have a `statesByFips` lookup we can use instead
=> remove regions DB dependency from AllStates

src/common/utils/recommend.ts, src/components/LocationPage/ChartsHolder.tsx, src/components/LocationPage/Recommendations.tsx
Also eliminates an unnecessary dependency on Projection data.
This simplifies some performance things and is also neater.
=> Break Recommendations out to separate file

src/components/Experiment/Experiment.tsx, src/components/LocationPage/ChartsHolder.tsx, src/components/LocationPage/LocationPageHeader.style.tsx, src/components/LocationPage/LocationPageHeader.tsx
Ships new alerts button to 100% of mobile users. Adds a new experiment-- variation A: email field auto-focused (the baseline, currently on prod), variation B: email field unfocused
=> New alerts button experiment

src/cms-content/vaccines/state-vaccine-phases.json
* Update Vaccination Phase “Vaccine Information-State”
* Update Vaccination Phase “Vaccine Information-State”
* Update Vaccination Phase “Vaccine Information-State”
Co-authored-by: Jonathan Mak <jmak@stanford.edu>
Co-authored-by: Ryan-Fuentes <79174308+Ryan-Fuentes@users.noreply.github.com>
=> Update Vaccination Eligibility Info (#3362)

src/common/metrics/vaccinations.tsx
https://trello.com/c/ocG0Ug74/1264-remove-none-of-them-deadly-from-vx-componenthttps://trello.com/c/ocG0Ug74/1264-remove-none-of-them-deadly-from-vx-component
=> Removed "None of them deadly" from Vx Component.

src/components/NewLocationPage/VaccinationProgressBar/VaccinationProgressBar.stories.tsx, src/components/NewLocationPage/VaccinationProgressBar/VaccinationProgressBar.style.tsx, src/components/NewLocationPage/VaccinationProgressBar/VaccinationProgressBar.tsx, src/components/NewLocationPage/VaccinationProgressBar/index.ts
- Uses ParentSize to make progress bar responsive 
- Renames `VaccinationsProgressBar` -> `VaccinationProgressBar`
=> Make vaccination progress bar responsive

src/screens/HomePage/HomePage.tsx
=> Homepage banner: Update rising hospitalizations states.

src/common/models/Projection.ts
This PR migrates Projection.ts file to use native JavaScript dates.
=> Convert projection.ts file to use native JavaScript dates

scripts/alert_emails/template.html, scripts/alert_emails/utils.ts
=> Add 'were you forwarded this email?' link to email alerts.

src/components/FixedAspectRatio/FixedAspectRatio.style.tsx, src/components/FixedAspectRatio/FixedAspectRatio.tsx, src/components/NewLocationPage/CountyMap/CountyMap.stories.tsx, src/components/NewLocationPage/CountyMap/CountyMap.style.tsx, src/components/NewLocationPage/CountyMap/CountyMap.tsx, src/components/NewLocationPage/CountyMap/index.ts
=> New minimap

src/components/Search/Homepage/HomepageSearchAutocomplete.tsx, src/components/Search/SearchAutocomplete.tsx
These are pretty similar, but are hard to compare because of how they're organized.  put props in the same order, and do some things the same way that seem like they should be consistent.
=> make SearchAutocomplete and HomepageSearchAutocomplete match better

src/common/hooks/index.ts, src/common/hooks/useDynamicVaccineButton.tsx, src/components/NewLocationPage/HeaderButtons/HeaderButtons.style.tsx, src/components/NewLocationPage/HeaderButtons/ShareButton.stories.tsx, src/components/NewLocationPage/HeaderButtons/ShareButton.tsx, src/components/NewLocationPage/HeaderButtons/VaccineButton.stories.tsx, src/components/NewLocationPage/HeaderButtons/VaccineButton.tsx
Find a vaccine button + share button
[Figma mocks](https://www.figma.com/file/JGqemgZwlG9e5DQbZpdKgy/Redesign?node-id=1742%3A120358)
`Location page redesign/Header Buttons` in storybook
=> New location page header buttons

src/components/Charts/ChartVaccinations.tsx, src/components/Charts/Charts.style.ts
=> adjust labels of the vaccination chart

src/components/NewLocationPage/LocationName/LocationName.stories.tsx, src/components/NewLocationPage/LocationName/LocationName.style.tsx, src/components/NewLocationPage/LocationName/LocationName.tsx, src/components/NewLocationPage/LocationName/utils.ts
This PR creates the location name block for the new location page header.
=> Create location name blocks

src/components/Banner/GetVaccinatedBanner.tsx
This PR updates the vaccination banner copy and adjusts the label on the find vaccine button.
=> Update vaccination banner

src/components/LocationPage/ChartsHolder.tsx, src/components/NewLocationPage/AboveTheFold/AboveTheFold.stories.tsx, src/components/NewLocationPage/AboveTheFold/AboveTheFold.tsx, src/components/NewLocationPage/LocationOverview/LocationOverview.stories.tsx, src/components/NewLocationPage/LocationOverview/LocationOverview.tsx, src/components/NewLocationPage/SparkLineBlock/SparkLine.tsx, src/components/NewLocationPage/SparkLineBlock/SparkLineBlock.stories.tsx, src/components/NewLocationPage/SparkLineBlock/SparkLineBlock.tsx, src/components/NewLocationPage/VaccinationProgressBarBlock/VaccinationProgressBarBlock.stories.tsx, src/components/NewLocationPage/VaccinationProgressBarBlock/VaccinationProgressBarBlock.tsx
Makes it so rendering above the fold doesn't depend entirely on projections
=> Above the fold: move fetching of projections

src/components/VaccinationEligibilityBlock/ButtonBlock.tsx
Matches language+href of button on homepage banner
=> Vaccine eligibility block button update

src/components/NewLocationPage/SparkLineBlock/SparkLine.tsx, src/components/NewLocationPage/SparkLineBlock/SparkLineBlock.tsx, src/components/NewLocationPage/SparkLineBlock/utils.ts
Uses maxY of the smoothed series only (rather than overall maxY of smoothed and raw)
=> Spark lines maxY update

src/common/colors.ts, src/components/NewLocationPage/LocationOverview/LocationOverview.style.tsx, src/components/NewLocationPage/Shared/Shared.style.tsx, src/components/NewLocationPage/SummaryStat/DesktopSummaryStat.tsx, src/components/NewLocationPage/SummaryStat/MetricSubLabel.tsx, src/components/NewLocationPage/SummaryStat/MobileSummaryStat.tsx, src/components/NewLocationPage/SummaryStat/SummaryStat.style.tsx
Instructions:
"​​text transf uppercase
​​.8rem
​​#828282 / 130,130,130
​​font weight 500
​​middle aligning the # value and subtext
​​removing line break in “1+ dose”
​​and applying this size/weight/color/etc to similar instances e.g., “PAST 30 DAYS”, “VACCINE PROGRESS”, etc."
=> Above the fold-gray subtitle edit

src/components/Header/HomePageHeader.tsx, src/components/InfoTooltip/index.tsx, src/components/NewLocationPage/LocationName/LocationName.tsx
- Edits `eg.` to `e.g.,`
- Unifies the code a little bit
=> Edits last updated tooltip

src/components/NavBar/NavLocationPage/NavLocationPage.tsx, src/components/NavBar/Search/Search.tsx, src/components/NewLocationPage/AboveTheFold/AboveTheFold.style.tsx, src/components/NewLocationPage/AboveTheFold/AboveTheFold.tsx, src/components/NewLocationPage/HeaderButtons/HeaderButtons.style.tsx, src/components/Search/Homepage/HomepageSearchAutocomplete.tsx, src/screens/LocationPage/LocationPage.tsx
- Location name as search bar placeholder text
- Spacing/alignment fixes
=> More small above the fold edits

src/components/Analytics/utils.ts, src/components/Experiment/Experiment.tsx, src/components/Footer/Footer.style.tsx, src/components/Footer/Footer.tsx, src/components/HomepageUpsell/HomepageUpsell.style.tsx, src/components/HomepageUpsell/HomepageUpsell.tsx, src/components/LocationPage/ChartsHolder.tsx, src/components/NewLocationPage/Shared/LabelWithChevron.tsx
[Trello](https://trello.com/c/qU9QWo11/1288-implement-homepage-upsell-experiment-on-location-page)
=> Homepage upsell experiment

src/components/LocationPage/ChartsHolder.tsx
Edits pixel point at which experiment is triggered
=> Homepage upsell experiment edit

src/common/ccvi/getShareQuote.ts, src/components/Compare/ModalFaq.tsx, src/components/VulnerabilitiesBlock/FooterLinks/FooterLinks.tsx, src/components/VulnerabilitiesBlock/VulnerabilitiesBlock.tsx, src/screens/HomePage/Announcements/Announcements.tsx
This PR updates copies pertaining to the vulnerability block.
=> Make copy changes to vulnerability components

src/components/VulnerabilitiesBlock/VulnerabilitiesBlock.tsx
This PR adjusts the wording in the vulnerability block.
=> Adjust wording in vulnerability block

src/cms-content/tooltips/info-tooltips.json, src/cms-content/tooltips/metric-calculation-tooltips.json
Update percentage vaccinated tooltips.
=> CMS content entry: Update percentage vaccinated tooltips

src/components/NewLocationPage/LocationName/utils.ts
Some regions contain a name with multi-suffix. This PR ensures these few cases are accounted for.
=> Account for multi-suffix location names

src/components/Banner/GetVaccinatedBanner.style.ts, src/components/Banner/GetVaccinatedBanner.tsx
[Trello](https://trello.com/c/jiNjXRSr/1333-change-banner-button-to-talk-to-your-friends-and-find-vaccines) - Update vaccination banner
- The button links to the CDC page about how to talk to friends and family about vaccinations
- Remove end icon, use larger button and center the button on the banner
- center text in the banner on all the screen sizes
=> update the vaccination banner

src/components/NewLocationPage/SparkLineBlock/SparkLine.tsx
Ran into this whilst looking into something else.
=> Fix negative height error on sparklines

src/components/HomepageUpsell/HomepageUpsell.tsx, src/components/LocationPage/ChartsHolder.tsx
Changes trigger point to 3000px for all screens
=> Homepage upsell edit

src/components/NewLocationPage/LocationOverview/LocationOverview.style.tsx, src/components/NewLocationPage/VaccinationProgressBarBlock/VaccinationProgressBarBlock.style.tsx
=> Location overview style tweeks

src/common/metrics/case_growth.tsx
https://trello.com/c/hsHzovvp/1362-infection-rate-remove-exploding
=> Update Infection Rate Copy to Remove Hospital and Exploding References

src/components/Charts/MetricChart.tsx, src/components/Compare/CompareMain.tsx, src/components/LocationPage/ChartsHolder.tsx, src/components/Map/Map.tsx, src/components/Map/USACountyMap.tsx, src/components/NewLocationPage/AboveTheFold/AboveTheFold.tsx, src/components/NewLocationPage/CountyMap/CountyMap.tsx, src/components/NewLocationPage/SparkLineBlock/SparkLineSet.tsx
Memoize some key components, especially ones with lots of html elements (charts, maps, compare table, etc.) to make renders faster.
I basically picked out interesting components, added console.log statements so I could see when they were rendering, and then memoized stuff until they seemed to stop rendering unnecessarily. 😁
=> Add memoization to various components.

src/components/LocationPage/ChartBlock.tsx, src/components/LocationPage/ShareButtons.tsx, src/components/LocationPage/SocialButtons.tsx, src/components/ShareButtons/SocialButtonBlock.tsx
This PR:
- Re-orders share buttons.
- Removes the embed button from sections which are currently non-embeddable.
=> Re-order share buttons

src/common/metrics/case_growth.tsx
=> Fix grammar on inflation rate chart

src/assets/theme/index.tsx, src/assets/theme/sizes.tsx, src/components/Charts/Charts.style.ts, src/components/LocationPage/ChartsHolder.style.tsx, src/components/LocationPage/ChartsHolder.tsx, src/components/LocationPage/LocationPageBlock.style.ts, src/components/NewLocationPage/AboveTheFold/AboveTheFold.style.tsx, src/components/NewLocationPage/AboveTheFold/AboveTheFold.tsx, src/components/NewLocationPage/CountyMap/CountyMap.style.tsx, src/components/NewLocationPage/Shared/Shared.style.tsx
Kept colored borders for QA purposes. will remove them before merging
=> Unify padding/spacing on location page

src/components/NewLocationPage/CompareLocationTabs/CompareLocationTabs.stories.tsx, src/components/NewLocationPage/CompareLocationTabs/CompareLocationTabs.style.tsx, src/components/NewLocationPage/CompareLocationTabs/CompareLocationTabs.tsx
This PR creates new location tabs for the compare table and display them in storybook.
=> Create compare location tabs

src/components/RegionItem/RegionItem.tsx
https://trello.com/c/L9uym7Du/1430-low-risk-doesnt-show-up-in-card
=> Fix location card when risk level is low.

src/common/colors.ts, src/components/USMap/USVaccineMap.stories.tsx, src/components/USMap/USVaccineMap.tsx
Tooltip isn't implemented yet.
=> Add USVaccineMap with coloring by vaccinations.

src/components/SocialLocationPreview/SocialLocationPreview.style.tsx, src/components/SocialLocationPreview/SocialLocationPreviewMap.tsx, src/screens/internal/ShareImage/HomeShareCardImage.tsx, src/screens/internal/ShareImage/ShareCardImage.style.ts
And move updated date into a subheader
=> Remove black border for share card image

src/components/VaccineDot/VaccineDot.stories.tsx, src/components/VaccineDot/VaccineDot.tsx
Adds a VaccineDot component for use in the map tooltip.  Supports solid or hatched coloring.
=> VaccineDot component.

src/components/HorizontalThermometer/RiskLevelThermometer/RiskLevelThermometer.style.tsx, src/components/HorizontalThermometer/RiskLevelThermometer/RiskLevelThermometer.tsx, src/components/ShareBlock/ShareModelBlock.tsx, src/components/ShareButtons/SocialButtonBlock.tsx, src/screens/HomePage/HomePage.style.tsx, src/screens/HomePage/HomePage.tsx, src/screens/HomePage/MapAccessories/MapAccessories.style.tsx, src/screens/HomePage/MapAccessories/MapAccessories.tsx
[Figma](https://www.figma.com/file/JGqemgZwlG9e5DQbZpdKgy/Redesign?node-id=2532%3A135785)
Before/currently on prod--
After--
=> Update items under homepage map

src/components/USMap/VaccineTooltip/VaccineTooltip.style.ts, src/components/USMap/VaccineTooltip/VaccineTooltip.tsx
Pablo pointed out the hover color was wrong which led me to discover that I should have been using one of our builtin button components. 😬
=> Fix more data link style.

src/components/Compare/Compare.style.tsx, src/components/Recommend/Recommend.style.tsx, src/components/ShareButtons/FacebookShareButton.tsx, src/components/ShareButtons/TwitterShareButton.tsx, src/components/SmallShareButtons/SmallShareButtons.tsx, src/components/TableOfContents/TableOfContents.style.ts
This PR updates components with the old blue color to the new blue.
=> Update component colors to new blue

src/components/USMap/VaccineTooltip/VaccineTooltip.tsx
Context: https://actnowcoalition.slack.com/archives/C01J5RYT9B6/p1624468501008000?thread_ts=1624465740.003400&cid=C01J5RYT9B6
=> Swap first / second dose and remove dot.

src/components/SharedComponents/SharedComponents.style.tsx, src/components/USMap/MapCounties.tsx, src/components/VaccinationsTable/VaccinationsTable.tsx
Adds focus state to toggle buttons, adds missing key, removes county map from tab order (same as state map implementation, so the map won't be a focus trap)
=> Small fixes

src/App.tsx, src/components/SocialLocationPreview/SocialLocationPreviewMap.tsx, src/screens/Embed/Embed.tsx
Customer reached out about it and it's easy to do...
=> Add URL for risk map embed.

src/assets/theme/megaMenu.ts, src/components/MenuContent/LearnSection.tsx, src/components/MenuContent/Menu.style.tsx
This PR aligns the button wrapper styling under "Education Resources" with that of "About Us"
=> Fix margin under Educational Resources

src/cms-content/recommendations/recommendations-main.json
Implement updates as described at https://www.dropbox.com/scl/fi/y36bt14394y7foeopb2ok/July-2021-CDC-Recommendation-Update.paper
=> Updating Masking Recommendations

src/components/EmailAlertsForm/EmailAlertsForm.tsx, src/components/NewLocationPage/GetAlertsBlock/EmailForm/EmailForm.tsx
https://trello.com/c/ZwpiR5V6/177-remove-call-to-sign-up-for-daily-download-from-alerts-callout
cc/ @BrettBoval
=> Remove daily download checkbox when signing up for alerts.

src/screens/Terms/Terms.tsx
This PR updates trademark terms.
=> Edit trademark terms

src/common/fullstory.ts, src/common/utils/storage.ts, src/components/NewLocationPage/CountyMap/CountyMap.tsx
remove logic resetting to vaccination status on navigation, and persist setting in localstorage if available.
=> keep minimap selection in local storage

src/common/colors.ts, src/components/HorizontalThermometer/VaccinationsThermometer/VaccinationsThermometer.tsx
Per https://www.dropbox.com/scl/fi/biyc9r2ddgxfuym3wjxqy/Update-Vaccination-Map-Color-Scale.paper?dl=0
=> Update vaccine map coloring to adjust for progress.

src/components/Banner/Banner.style.ts, src/components/Banner/DonationBanner.tsx, src/screens/HomePage/HomePage.tsx
Add donate banner back to the homepage.
=> Add donate banner

src/components/NewLocationPage/LocationName/LocationName.tsx
To be merged if/when we get nervous about holiday data quality...
=> Add holiday data update notice.

src/screens/HomePage/HomePage.tsx
- Move Trends to be above Compare in Homepage
- Remove Announcements section
=> homepage: move Trends and remove Announcements

src/components/NewLocationPage/AboveTheFold/AboveTheFold.style.tsx, src/components/NewLocationPage/AboveTheFold/AboveTheFold.tsx
This PR removes the vulnerability note from the location page.
**Note:** Not deleting `VulnerabilityNote.tsx` yet. In case we decide to add it back again in the future.
=> Remove vulnerability note

src/cms-content/learn/about-our-alerts.json, src/screens/Learn/Explained/ExplainedLanding.tsx
https://actnowcoalition.slack.com/archives/C01DNUNLC56/p1643065518001500?thread_ts=1643062850.000800&cid=C01DNUNLC56
=> Learn content update

src/components/MenuContent/AboutUsSection.tsx, src/components/MenuContent/Menu.style.tsx
Tiny fix to resolve footer not recognizing markdown links.
=> Markdown fix

src/common/metrics/hospital_admissions_per_100k.tsx, src/common/metrics/hospitalizations_per_100k.tsx, src/common/metrics/ratio_beds_with_covid_patients.tsx, src/common/metrics/weekly_cases_per_100k.tsx
Adds files with placeholder content for new metrics
Trello: https://trello.com/c/acDWkNnM/529-create-metric-files-for-the-new-cdc-metrics
=> New metric files

src/components/MenuContent/Menu.style.tsx
Trello ticket: https://trello.com/c/64PtEXcR/534-bug-style-of-the-act-now-coalition-link
=> Menu link color bug

public/admin/config.yml, src/cms-content/cms-config.test.ts
Update the CMS branch to use `can-82`
=> update the CMS config branch

public/admin/config.yml, src/cms-content/cms-config.test.ts, src/cms-content/team/alumni.json, src/cms-content/team/strategy.json, src/common/metrics/hospitalizations_per_100k.tsx, src/common/metrics/ratio_beds_with_covid_patients.tsx, src/common/metrics/weekly_cases_per_100k.tsx, src/components/MenuContent/Menu.style.tsx
Update the CMS branch to use `can-82`
=> develop → main

src/cms-content/footer/footer.json, src/components/ShareBlock/ShareBlock.tsx
Footer and share copy updates as per:
- https://trello.com/c/9OyK8uF4/532-copy-update-footer-menu
- https://trello.com/c/7vGeU0YR/531-copy-update-share-embed
=> Footer and share copy updates

src/components/NewLocationPage/CountyMap/CountyMap.tsx
Defaults location page's county map view to community level rather than % vaccinated
Trello: https://trello.com/c/BqmDuu55/394-update-location-page-above-fold-to-community-level
=> Default minimap view

src/common/metrics/admissions_per_100k.tsx, src/components/NewLocationPage/AboveTheFold/AboveTheFold.style.tsx, src/components/NewLocationPage/SparkLineBlock/utils.ts
Need to update with correct dataset IDs once API updates are merged in
=> New metrics into spark lines

src/common/metrics/admissions_per_100k.tsx, src/common/metrics/ratio_beds_with_covid_patients.tsx, src/common/metrics/weekly_new_cases_per_100k.tsx, src/components/Explore/utils.ts
- Wires up correct dataset IDs in explore
- References correct metric in tooltip content util
=> Wire up correct dataset ids in explore

src/common/utils/provenance.tsx, src/components/Dialogs/utils.tsx
- Add correct sources for all three new metrics
- Fix casing of metric name in about this data modal
- Update copy of hospitalized patients tooltip ('how its calculated' section)
=> Misc. todos

src/components/NewLocationPage/ChartFooter/utils.ts
Small adjustment based on the copy referenced [by these comments in the copy doc](https://docs.google.com/document/d/1pITjM1gctulpwyqez5SFrQLFIYO4vndJArDjFPnVMG4/edit?pli=1&disco=AAAAXlM39JE)
=> Hospitalizations chart copy edit

src/common/metrics/weekly_new_cases_per_100k.tsx
Updates labels from `Low`->`Lower` // `High`->`Higher`
=> Weekly new cases chart labels

src/common/metrics/admissions_per_100k.tsx, src/common/metrics/ratio_beds_with_covid_patients.tsx, src/common/metrics/weekly_new_cases_per_100k.tsx
From [copy doc](https://docs.google.com/document/d/1pITjM1gctulpwyqez5SFrQLFIYO4vndJArDjFPnVMG4/edit?pli=1#):
=> Weekly new cases chart status text

src/components/SocialLocationPreview/SocialLocationPreviewMap.stories.tsx, src/components/SocialLocationPreview/SocialLocationPreviewMap.tsx, src/screens/HomePage/HomePage.tsx, src/screens/internal/ShareImage/HomeShareCardImage.tsx, src/screens/internal/ShareImage/USMapImage.tsx
https://covid-projections-git-pablo-preview-image-home-covidactnow.vercel.app/internal/share-image/map
=> update the social preview map (home page)

src/common/metrics/hospitalizations.tsx, src/components/NewLocationPage/ChartFooter/utils.ts
Updates as per [CAN 8.2 copy doc](https://docs.google.com/document/d/1pITjM1gctulpwyqez5SFrQLFIYO4vndJArDjFPnVMG4/edit#).
=> Update chart footer copy for hospitalizations

src/components/Banner/Banner.style.ts, src/components/Banner/Can82Banner.tsx, src/components/Banner/index.ts, src/components/NewLocationPage/AboveTheFold/AboveTheFold.tsx, src/screens/HomePage/HomePage.tsx
Copy and URL subject to change
Trello: https://trello.com/c/zv4ok0cO/585-add-banner-to-homepage-and-location-pages
=> Can 8.2 banner

src/App.tsx, src/common/hooks/index.ts, src/common/hooks/useScrollToRecommendations.ts, src/common/regions/types.ts, src/common/urls.ts, src/components/LocationPage/ChartsHolder.tsx, src/components/Recommend/Recommend.tsx, src/components/Recommend/Recommendations.tsx, src/screens/HomePage/HomePage.tsx
fixes recommendations sharing on homepage, cleans up for both homepage + location page
trello: https://trello.com/c/aHQARQRJ/566-bug-clicking-on-share-home-recommendations-shares-the-wrong-url
=> Recommendations sharing

src/components/Banner/Banner.style.ts, src/components/Banner/Can82Banner.tsx, src/components/Charts/Groupings.tsx
- Edits casing of chart block headers
- Updates banner copy per what's in the trello ticket (URL still needs to be finalized)
=> Small copy edits

src/common/metrics/positive_rate.tsx
Per slack thread: https://actnowcoalition.slack.com/archives/C0182MKHWCR/p1650288253179059
=> Remove missing test positivity special case

src/common/metrics/positive_rate.tsx
Combine disclaimer with chart footer for positive test rate.
=> Combine disclaimer with chart footer

public/index.html, scripts/generate_index_pages.ts, src/screens/HomePage/HomePage.tsx, src/screens/LocationPage/utils.ts
Page title has already been updated. This PR just updates page description.
Trello: https://trello.com/c/r6X1GOmo/595-social-meta-tags
=> Update page description

src/common/models/Projection.ts, src/components/Explore/utils.ts
Addresses https://trello.com/c/jK3YzX5g/594-weekly-new-cases-in-trends-incorrect-normalization
Calculate raw weekly cases from smoothed daily cases and use in Trends chart
=> Fix weekly new cases Trends chart

src/screens/HomePage/HomePage.tsx
Tiny PR adjusting header above the community level map, as per request in the [launch checklist](https://www.dropbox.com/scl/fi/u23ob7sqtyqyo3e9n37bx/CAN-8.2-CDC%2B%2B-Launch-Checklist.paper?dl=0&rlkey=ebmgo5rcj5i3mesd8bkeglac3).
=> Adjust community level map header

src/components/Banner/Can82Banner.tsx
Tiny PR updating banner copy as per [launch checklist](https://www.dropbox.com/scl/fi/u23ob7sqtyqyo3e9n37bx/CAN-8.2-CDC%2B%2B-Launch-Checklist.paper?dl=0&rlkey=ebmgo5rcj5i3mesd8bkeglac3#:uid=495169661123461441020632&h2=Blocking).
=> Edit banner copy

public/admin/config.yml, src/cms-content/cms-config.test.ts
Changes branch from `can-82` back to `cms-content-entry`
=> Revert cms branch

src/common/metrics/admissions_per_100k.tsx, src/components/Banner/Can82Banner.tsx
Addresses two cards:
- https://trello.com/c/RLWaFHWH/599-copy-update-hsa-names
- https://trello.com/c/tUtKiung/597-update-the-target-of-the-learn-more-link-in-the-banner
=> Banner link update and tiny copy edit

src/components/NewLocationPage/OverallRiskBlock/OverallLevelText/OverallLevelText.style.tsx, src/components/NewLocationPage/OverallRiskBlock/OverallLevelText/OverallLevelText.tsx
Trello: https://trello.com/c/RhuxGuxK/584-fix-low-medium-high-indicator-above-fold-on-mobile
=> Shorter risk level labels on mobile

src/common/models/Projections.ts, src/components/Charts/Groupings.tsx, src/components/Explore/interfaces.ts, src/components/Explore/utils.ts, src/components/LocationPage/ChartsHolder.tsx
Addresses https://trello.com/c/jNylgmzc/607-more-explicitly-highlight-older-transmission-metrics
=> Add daily new cases, rename additional metrics, move vaccinations lower

src/components/Compare/columns.tsx
Based on high profile feedback we've opted to bring it back to compare for now.  I've hidden the grading dots.
=> Add infection rate back to compare.

src/components/Banner/Can82Banner.tsx
Update banner link as per [conversation](https://docs.google.com/document/d/1pITjM1gctulpwyqez5SFrQLFIYO4vndJArDjFPnVMG4/edit?disco=AAAAYDH8_wA).
=> Update banner link

yarn.lock
I want to upgrade our dependencies with security alerts (at least the ones listed as Critical in https://github.com/covid-projections/covid-projections/security/dependabot?q=is%3Aopen+severity%3Acritical)
This PR only upgrades 3 of them, will try to upgrade the rest on follow up PRs.
=> upgrade react-html + handlebars

src/common/metrics/weekly_new_cases_per_100k.tsx, src/components/Compare/columns.tsx
Trello: https://trello.com/c/KhehNBWT/635-fix-bug-in-which-yellow-is-used-for-higher-cases-not-orange
=> Weekly new cases color fix

src/components/LocationPage/ChartsHolder.tsx
Per: https://trello.com/c/nW0chShX/632-reorder-sections-on-location-page
=> Reorder location page sections

src/components/Explore/utils.ts
Revise and re-order explore metric labels as per [card](https://trello.com/c/4vaBpo28/634-rename-metrics-in-trends-menu).
=> Revise explore metric labels

scripts/alert_emails/template.html, scripts/alert_emails/utils.ts
Updates the copy of the alert emails. I'm want to confirm that we are actually intended to remove the commented code before removing it definitively. [Updated copy doc - Alert Emails](https://docs.google.com/document/d/1pITjM1gctulpwyqez5SFrQLFIYO4vndJArDjFPnVMG4/edit#heading=h.8ugpgz4hwowi)
Here is a screenshot of a test email (note that we use mock data for this email, including the date)
=> Update the copy of the alert emails

src/components/NewLocationPage/AboveTheFold/AboveTheFold.tsx, src/screens/HomePage/HomePage.tsx
[Trello ticket](https://trello.com/c/HkQEWqiM/653-remove-can-82-banner)
=> Remove can 8.2 banner

public/index.html, scripts/generate_index_pages.ts, src/screens/HomePage/HomePage.tsx, src/screens/LocationPage/utils.ts
As per [card](https://trello.com/c/EvhbNVD2/658-add-risk-to-social-meta-tags).
=> Add risk to social meta tags

src/screens/HomePage/HomePage.style.tsx, src/screens/HomePage/HomePage.tsx, src/screens/HomePage/MapBlock.tsx
Trello: https://trello.com/c/tC3JEiqP/630-de-duplicate-learn-links-under-community-levels-map
=> Consolidate map info links

src/screens/HomePage/HomePage.style.tsx, src/screens/HomePage/HomePage.tsx, src/screens/HomePage/MapBlock.tsx
Trello: https://trello.com/c/okXekTeR/655-add-copy-and-tooltip-under-community-risk-levels-on-homepage
=> Risk map description + tooltip

src/screens/HomePage/HomePage.style.tsx, src/screens/HomePage/HomePage.tsx
This is a revert of c34c3cddb3c489e53a5f287ee46fa8d2d26bd13d except I left the updated survey URL in the (now unused) `FeedbackSurveyBanner` component.
=> Remove survey banner.

src/components/Charts/ChartAdmissionsPer100k.tsx, src/components/Charts/ChartCaseDensity.tsx, src/components/Charts/ChartRt.tsx, src/components/Charts/ChartWeeklyNewCasesPer100k.tsx, src/components/Charts/ChartZones.tsx, src/components/Charts/LinePathRegion.tsx, src/components/Charts/ZoneLinePath.tsx
Fix chart line bug as pointed out in [this card](https://trello.com/c/XsIYZOsx/692-color-grading-visual-bug-in-a-small-number-of-hospital-metric-charts).
=> Fix chart line bug

src/App.tsx
=> Add back GiveMomentum route

src/components/Charts/Groupings.tsx
Remove unnecessary console log.
=> Remove unnecessary console log

scripts/alert_emails_report/generate-report.ts
Adding context to the calculation that can not be inferred just from reading the provided code.
=> Adding Analytics Context

scripts/alert_emails/template.html, scripts/alert_emails/utils.ts
[Proposed copy:](https://docs.google.com/document/d/14eDHgYfzSdwbZ7_piIppjgFj81cDGTNzsZbuyevPGaQ/edit#) 
Preview:
=> Update email template
