src/App.js
src/components/Map/Map.js
src/screens/ModelPage.js

This PR
- redirects all unknown routes to `/`
- makes the `/state/:id` route dynamic, taking the stats abbreviation as an ID.  Currently, there's no error handling (for example, if you manually typed `/state/westeros` but for now, I think that's an edge case we can bump

Make state route dynaic based on id

---

public/index.html
src/components/AppBar/AppBar.js
src/screens/ModelPage/ModelPage.js
src/screens/ModelPage/ModelPage.style.js

Fixes https://github.com/covid-projections/covid-projections/issues/71
Adds Facebook share button to top bar.
Adds Facebook, Twitter, and Linkedin share buttons to state pages. We could integrate with the SDKs directly, but that introduces some design inconsistencies and it also adds a lot of weight and 3rd-party tracking to the page.

Add social media share buttons

---

src/components/AppBar/AppBar.js

Adds the Facebook share button to the mobile menu as well (whoops).

Add Facebook share to mobile menu

---

src/components/AppBar/AppBar.js
src/components/AppBar/MobileMenu.js
src/utils/model.js

Fixed a few link a11y issues. Main difference is that `goTo` now returns an event handler, rather than needing to be called as part of an event handler. This is done so that `goTo` can call `event.preventDefault()`. 
Terminal output from `yarn start` is now clean. Browser console still has some warnings and errors, but many are from dependencies and are probably not worth chasing down right now.

Remove remaining warnings from CRA

---

src/screens/ModelPage/ModelPage.js

* We now have dynamic phrasing depending on current intervention and whether hospital overload is expected within 3 months.  See https://docs.google.com/document/d/1MA-hitauZ82XCRI_XZUY0G1fdsa9WkAsiWPOVaKNOJI/edit#
* Refactored entire Callout element into a dedicated CallToAction component (which subsumed the existing LastDatesToAct component).
New version for okay states:
New version for not-okay states:
As implemented it does not ever recommend "Social Distancing".  This is open for discussion.

Rework "point-of-no-return" call to action.

---

src/screens/About/About.js

Looks like it got re-added my mistake in 0bfc074f5f7113868034795569a961ebd23df247.

Remove "General Counsel" position.

---

src/assets/data/interventions.json

Alaska announces shelter in place
https://www.alaskapublic.org/2020/03/27/we-crossed-a-line-today-dunleavy-further-limits-travel-and-movement-as-coronavirus-cases-increase/

backfill from interventions update

---

src/utils/model.js

#86 this doesn't apply to changing the flag based on the selected
series, but does fix the positioning of the flag.
the original interpolation wasn't placing the line close to the
intersection. It seems like it was using a portion of the bed shortfall
as a stand in for a duration, which doesn't make much sense to me.
the new appoaches finds the beginning and end of the window in
which the hospitalization and beds lines first intersect. finds the
intersection point, then uses that to interpolate the day range.

fix: interpolation of overwhelmed date

---

src/assets/images/capacityIcons.js
src/assets/images/interventionIcon.js
src/components/Map/Map.js
src/components/Newsletter/Newsletter.style.js
src/screens/ModelPage/CallToAction/CallToAction.js
src/screens/ModelPage/CallToAction/CallToAction.style.js
src/screens/ModelPage/ModelPage.js
src/screens/ModelPage/ModelPage.style.js

It may seem like this change makes important information _less_ prominent, but coupled with the [new state headers](https://github.com/covid-projections/covid-projections/pull/243), this will be an elegant and appropriate visual for conveying key information.

Add table with intervention and hospital capacity status

---

src/App.js
src/screens/Terms/Privacy.js
src/screens/Terms/Terms.js

Not ready to be merged until we have final approval (edit: we have it now), but I anticipate it will look almost identical to this. Note that this is not intended to get a nav link, but only be reachable directly at the URL (`/privacy`) or via the Terms of Use.

Initial commit of the privacy policy, including links from the ToU

---

package.json
src/App.js
src/components/Charts/ModelChart.js
src/screens/CompareModels/CompareModels.js
src/screens/CompareModels/CompareModels.style.js
src/screens/ModelPage/ModelPage.js
src/utils/model.js
yarn.lock

This is an experimental page for internal usage but needs to live in the
website so we can share all of the chart loading / rendering code with the rest
of the website.
The idea is to let us easily compare all of the (state) graphs for e.g. staging
vs. prod or a modeler can point it at their local model files and compare them
as well.
I think this will be useful, but for now it's experimental.  We can iterate and
or abandon it depending on future needs.
One specific improvement I'd like to make is adding logic to do a simple
algorithmic comparison of each model and then sort them based on how different
they seem to be.

Add a /compare page for testing / debugging model data.

---

public/index.html

duplicating the tracking to legacy GA property since the Firebase / App+Web reports have some limitations.

add traditional GA property to gtag

---

src/components/Charts/ModelChart.js
src/components/Charts/ModelChart.style.js
src/components/StateHeader/StateHeader.js
src/enums/interventions.js
src/screens/ModelPage/Outcomes/Outcomes.js

TL;DR: it's more friendly, Shelter in Place is more of a disaster response term.
I left "Shelter in Place" in `interventions-data.js`, since it seems to be used in CSVs. Unsure if this data makes it to the front end and therefore needs to change, or if we can leave it around.
As a side note, I left all the variable names in place, I just changed the string values.

Initial take on renaming to Stay at Home, per JKT's copy change.

---

src/components/AppBar/AppBar.js

1. Our push routes weren't being tracked as events in GA, so we can't actually see how people navigate on the site.  https://developers.google.com/analytics/devguides/collection/gtagjs/pages
2. My eye's twitching from the hardcoding of the config id, but I didn't want to add in react-ga module and risk breaking more things. Open to suggestions here.

Add push state to GA tracking

---

src/components/MapSelectors/datasets/us_states_dataset_01_02_2020.json

24d628048e0c58d0d27a15612d3fc1dacb079d58 accidentally updated Kings County, CA to point at NYC instead of updating Kings County, NY.

Fix Kings County (NY vs CA) search results.

---

src/components/Header/SearchHeader.js
src/components/Header/SearchHeader.style.js
src/components/MapSelectors/GlobalSelector.js

Note: Easier to review if you disable whitespace diffs:
https://github.com/covid-projections/covid-projections/pull/396/files?diff=split&w=1
Shows "See county data" text next to the map toggle, unless the search is focused or unless the screen is really narrow.
Normally:
> ![image](https://user-images.githubusercontent.com/1570168/78307573-11a71f80-74fb-11ea-9eca-03527db9e760.png)
When search is focused:
> ![image](https://user-images.githubusercontent.com/1570168/78307585-179d0080-74fb-11ea-9c15-6b5a2004d279.png)
When screen is narrow:
> ![image](https://user-images.githubusercontent.com/1570168/78307675-50d57080-74fb-11ea-9009-289052190fd1.png)

Add "See county data" text

---

package.json

Set CHOKIDAR_USEPOLLING=1 env var per https://github.com/gatsbyjs/gatsby/issues/11406#issuecomment-565748588 to avoid "System limit for number of file watchers reached" error that's been occurring in CI (e.g. see failure in https://github.com/covid-projections/covid-projections/pull/427/checks?check_run_id=563255441).  Seems to have worked.
This problem should go away soon once we move data files out of the covid-projections repo.

Try to fix CI error (Error: ENOSPC: System limit for number of file watchers reached).

---

src/App.css
src/components/Charts/ModelChart.style.js
src/components/Map/Legend.js
src/components/Map/Legend.style.js

Executes several UX improvements from Josh Ziman:
- On homepage’s legend, consider changing titles to `font-weight: bold` in order to increase visibility
- On chart page’s legend and on hover state for each legend item, consider changing to `cursor: pointer` to better indicate interactivity/toggle affordance
- On charts, consider changing curves to `fill-opacity: .8` to reveal the trajectory of curves in the background

UX fast-follows from V2

---

src/components/AppBar/AppBar.js

Previously, clicking the nav links in the footer did not change which link was highlighted in the AppBar (top bar). See this example -- we are on `/faq` but the AppBar still has **Map** highlighted.
The issue was by the fact that only the AppBar's own links told AppBar to update state. This PR changes AppBar to update state based on the current URL, so it's always up to date no matter how the page was navigated to.

Make AppBar state always reflect URL

---

public/index.html
src/components/AppMetaTags/AppMetaTags.js
src/screens/Endorsements/EndorsementsPage.js
src/screens/FAQ/FAQ.js
src/screens/HomePage/HomePage.js
src/screens/ModelPage/ModelPage.js

Fixes #411
This is the effect I hope this PR will have:
| Before    | After    |
| ----------| -------- |
| ![before] | ![after] |
[before]: https://user-images.githubusercontent.com/206364/78419072-b3f7fd80-75f6-11ea-8fe2-600244f3f751.png
[after]: https://user-images.githubusercontent.com/1570168/78424902-7c547a00-7625-11ea-9f15-4ca634e764d7.png
What's not fixed:
As noted extensively in comments, the FB/Twitter share buttons aren't picking up the meta tags that we're injecting using react-helmet. I don't think they've ever worked, and I don't think any frontend change can fix this. I opened #450 for this and added links to it where the code is currently broken.

Fix meta tags on all pages

---

src/components/Charts/ModelChart.js
src/models/Projections.js

[See for yourself
](https://covid-projections-git-ap-fix-past-hospital-overload.covidactnow.now.sh/us/co/county/gunnison_county)
Resolves #470

Don't show time window for Hospital Overload if it's in the past

---

scripts/models/projections.js
src/models/Projections.js
src/utils/model.js

This removes the data fetching for the wuhan intervention file, it is currently file 2, if the BE updates reindexes 2 to become the social distancing model ModelIds->weakDistancingNow needs to be updated

remove contain now model loading

---

src/components/AppBar/AppBar.js

Manual testing:
* checked that the Facebook share link from /us/wa/county/king_county has county-specific text
* checked that a state share link still works
* checked that share links from / still have the nonspecific text.
also fixes #398 along with #488 (which fixes #398 for states only)

Detect county URL pattern and use it in share links. Fixes #487

---

src/components/AppBar/AppBar.js

This doesn't fix county pages currently because `match` isn't set for county pages, but that's because of #487 which I will deal with separately.

Bring back the back arrow on state pages. Refs #398

---

src/components/CountyMap/CountyMap.js
src/components/Map/Map.js
src/enums/us_state_centers.js

Let's give this one more try. All 50 states should now be visible and correctly rotated.
Washington state before:
Washington state after:

Orient states in a more familiar manner in minimap (refs #439)

---

.github/ISSUE_TEMPLATE/bug-template.md

Since mostly blocks of text are expected, it makes more sense to use titles and sections than italicized prompts.
I left the endorsement template because that's different - we'd only expect a short response for each item.

Update bug template to use Markdown titles

---

src/components/Charts/ModelChart.js
src/screens/CompareModels/CompareModels.js

It tends to dwarf the "current trend" graph, so disable it by default when comparing.

/compare: Disable "Restrictions Lifted" graph by default.

---

src/components/Charts/ModelChart.js
src/components/Header/HomePageHeader.style.tsx
src/components/Header/HomePageHeader.tsx
src/models/Projections.js
src/screens/FAQ/FAQ.tsx

We're updating the model every 3 days now, not 24 hours, so I've updated that everywhere. In addition, this PR swaps the homepage hero and links to our 43k lives blog post.

Swap 24hrs for 3 days and update hero

---

src/components/Charts/ModelChart.js
src/models/Projections.js
src/screens/CompareModels/CompareModels.js
src/screens/Embed/ChartsTab.js
src/screens/Embed/Embed.js
src/screens/ModelPage/ModelPage.js

We were overloading the countyName property of ModelChart as a signal for two things:
1. Should we show the county disclaimer?
2. Should we try to show inference projections?
The embeds were not setting countyName because they didn't want a disclaimer. But this resulted in them hitting the inference projections codepath, which doesn't work for counties.
I fixed this by:
1. Removing `countyName` since it's not necessary (we can find out if it's a county from the projections).
2. Using `interventions.isCounty && !isEmbed` to decide whether to show the county disclaimer or not.

Fix county embeds (they were trying to show inference projections).

---

src/components/Charts/ModelChart.js
src/utils/model.js

`new Date()` on safari doesn't like the timezone offset as `+0000` so just use moment for parsing.

Fix 'Last Updated' date on Safari and give us an extra day of breathing room.

---

src/api/index.ts
src/models/Projection.ts
src/models/Projections.ts
src/utils/model.js

Column numbers are gone and accessing properties from the API schema is all type-checked. 😁 I _think_ everything is working other than county inference.

Use API v1 to load state / county timeseries projections.

---

src/components/Charts/ModelChart.js
src/models/Projection.ts

I have a [dummy draft PR](https://github.com/covid-projections/covid-projections/pull/596) that can be used to see what this actually looks like pointed at a 1-day-interval snapshot: https://covid-projecti-git-mikelehen-allow-1-day-intervals-use-1-a5a45e.covidactnow.now.sh/us/sd/county/meade_county (note the hospital overload lines up as expected now).
* We had logic to extract a 200-day duration by dividing it by 4 (to compensate for 4-day-interval), but in practice the API gives us way less than 200 days of data (it's ~4mo == 120 days), so I just removed the duration logic for now.
* Actually testing with a snapshot with 1-day-interval (e.g. snapshot 146) exposed a bug (https://github.com/covid-projections/covid-data-model/issues/315) which I have temporarily worked around (see …

Allow 1-day-interval datasets.

---

src/api/index.ts
src/components/LocationPage/ChartsHolder.tsx
src/models/Projection.ts

I've created PR #600 to demonstrate this in action by combining with @pnavarrc's chart work and doing a quick/dirty integration into the model page. Demo here: https://covid-projections-git-mikelehen-test-charts-and-api.covidactnow.now.sh/

Plumb Phase 3 data from API through getDataset().

---

src/components/Charts/zoneUtils.js

The tooltips for hospital usage and positive tests rate were showing the value as a fraction instead of as a percentage
Positive Tests
Hospital Usage

Fix the tooltip formatter for zone charts

---

src/components/Charts/zoneUtils.js

Fixes part 1 (Charts don't always have all 3 sections) of https://github.com/covid-projections/covid-projections/issues/609.
If you'd rather not merge this since you'll probably be mucking with this code later today, that's 100% fine. But it seems to work, so sending it your way for consideration.

Phase 3 Charts: Ensure high region is at least as large as the medium region.

---

src/components/Charts/utils.ts
src/components/Charts/zoneUtils.js

Fixes an issue that was causing the current value for zone charts to be hidden.
The value for the current point annotation was taken as the last item of the passed `data` array. Since the future values have data, but it's undefined, the values for `x` and `y` were `undefined` too. This PR gets the last value such that both `x` and `y` are finite numbers.
Before
After
(I took a screenshot scaling down, it might look a bit funky, but the values are shown now).

Fixes missing current values for zone charts

---

src/models/Projection.ts

This definitely helps (totally fixes WA), but we may still want some 7-day-rolling-average smoothing as a next step?
---

Add interpolation of cumulatives to smooth out stalled days.

---

src/models/Projection.ts

WA had some weird reporting where they reported 37 negatives, but 0 positives.  The result after interpolating, calculating deltas, dividing, and smoothing was:
😬 
(basically interpolation generated a large number of positives for that day, which were huge compared to the low number of negatives)
But if we instead interpolate, smooth, calculate deltas, and then divide, then it's much better:

Improve positive rate smoothing (do rolling average on deltas, before dividing to get the positive rate percent).

---

src/components/Charts/ModelChart.js
src/components/Charts/ModelChart.style.js
src/enums/colors.js
src/enums/team.js

Update the Future Projections Chart
Designs in [Figma](https://www.figma.com/file/UUCr3ZpwaPV4o1KuGdSCNl/Covid?node-id=2719%3A4830)
Screenshot: with and without inferred data
I'm still trying to have this annotation outside the chart, but maybe we should have a plan B for it (Josh?)
I'm using the `projected` series to show the "previous estimate" section, let me know if we need to update it.

Update the Future Projections Chart

---

src/components/Charts/utils.ts
src/components/Charts/zoneUtils.js

Fixes the upper limit for zone charts
The upper limit for the y-axis was taken only from the data. When the max y value was below the upper limit of the medium region, the mid point between the max y value and the upper limit of the medium region, making it show below the upper limit of the medium region:
**Example: Before the change**
```
maxY = 0.4
mediumUpperLimit = 0.8
yHighLabel = (maxY + mediumUpperLimit) / 2 = 0.6
```
This changes the logic to take either the max of the data, or `1.5 * mediumUpperLimit`, to ensure that the high region is visible, also aligning the high region label
```
maxY = 0.4
maxYAxis = max(maxY, 1.5 * mediumUpperLimit) = 1.6
mediumUpperLimit = 0.8
yHighLabel = (maxYAxis + mediumUpperLimit) / 2 = 1.2
``` 
**Examples**

Fix the y-axis limit for zone charts

---

src/components/Charts/ModelChart.js
src/components/Charts/ModelChart.style.js
src/components/Charts/ZoneChart.style.js
src/components/Charts/utils.ts
src/components/Charts/zoneUtils.js

Updates the styles of some elements in the charts. Following the items from [UX Fit and Finish](https://www.dropbox.com/scl/fi/oih4o7ikqfhje2yw62yvn/UX-fit-and-finish.paper?dl=0&rlkey=f6d8ezrv210e92kgd0mc6hq9u)
- https://covid-projections-43g45t00c.now.sh/
- https://covid-projections-43g45t00c.now.sh/all
- I'm working on a demo for a broken y-axis for when the values of the series make the LOW area to be too small (squeezing the LOW annotation). We don't know if that solution will work, so I'm doing that on a separate PR so we can discard it if it doesn't work.
cc @igorkofman @mikelehen

Chart Updates - Style Fixes

---

src/components/Charts/ModelChart.style.js
src/components/Charts/ZoneChart.style.js

- makes the font-family of the axes consistent with the rest of the text on the charts
- Adds a background for the current value annotation, so if it overlaps with the grid lines it doesn't look as bad
- Highcharts renders axes as `<span>` (HTML) or `<text>` (SVG) elements, so I had to style both. It appears that chooses which one randomly 🤷‍♂️

changes the font of the axis to match other text

---

src/components/LocationPage/ChartsHolder.tsx
src/models/Projections.ts

Tweaks per feedback from Igor / Dan during evening standup.
* Igor thought "Additional people will be hospitalized" was a little too weak of an assertion. 😁 
* Fixed the overwhelmed date (was showing up as null in some cases, and was using the decoy "worstCaseProjection" which is not really the worst case projection (now removed).

Update the future predictions description text.

---

src/components/Charts/utils.ts
src/components/Charts/zoneUtils.js

- Set a maximum value for positive testing (see thread on [Slack](https://covidactnow.slack.com/archives/C0110QQAPJA/p1588215240213300) to 50%.
- It also rounds up the maxYAxis value to the closest 1% instead of rounding up to the closest 10%, this gives extra space to the data, it looks nicer in my opinion
- It increases the z-index of the last point annotation, to ensure that it always shows up, even if it overlaps with other annotations (this can be seen in the `/all` page)

set the y-axis limit for positive test rate to 50%

---

src/components/Map/Map.js

Fixed a bug where we were showing the "click a state" instructions in the minimap

hide instructions in minimap

---

src/components/ClaimStateBlock/ClaimStateBlock.style.js
src/components/LocationPage/ChartsHolder.tsx
src/components/Newsletter/Newsletter.style.tsx
src/components/ShareBlock/ShareBlock.style.tsx
src/components/ShareBlock/ShareBlock.tsx
src/screens/About/About.tsx
src/screens/Contact/Contact.tsx
src/screens/HomePage/CriteriaExplanation/CriteriaExplanation.style.tsx
src/screens/HomePage/HomePage.js
src/screens/Resources/Resources.tsx

Our sharing and "claim state" modules were weirdly aligned on some large screen sizes. Fixed that and removed box shadow to align with our styling approach.

redo share styling

---

src/components/LocationPage/ChartsHolder.tsx
src/models/Projection.ts

Projection.totalICUCapacity and ProjectiontypicallyFreeICUCapacity are now nullable.
Without this, 506 county pages fail to load.

Fix issue affecting 506 counties that don't have actuals.ICUBeds data.

---

src/components/LocationPage/ChartsHolder.tsx

Good enough? (else let me know what you want)
NOTE: We end up saying "we calculate ... rate" twice in a row, but the second one is harder to change.
Alternative:
* We calculate the rate as a 7-day trailing average to smooth out daily reporting inconsistencies.

Add 7-day trailing average text to disclaimer under positive rate chart.

---

src/components/SummaryStats/SummaryStats.tsx

Helps avoid confusion when the rounded value lands on a zone threshold.

Deploy: Add 1 decimal point to positive rate in header too

---

src/components/CountyMap/CountyMap.js
src/components/MiniMap/MiniMap.tsx
src/utils/model.js

We used to need these files to render the county map without having to read all the projection files. But the calculated_county_interventions.json file took the place of that a while ago so it's been redundant for a while.
Additionally, the summary files are slightly wrong. E.g. they indicate Weber County, UT (fips 49057) should have data, but it does not. I'm not sure why the summary file is wrong, but we don't need it anymore, so who cares.
My next PR (to move the calculated interventions script onto the batch API will remove use of the summary file completely).

Remove use of county_summaries/XX.summary.json files in the frontend.

---

src/assets/images/checkIcon.tsx
src/assets/images/exclamationIcon.tsx
src/assets/images/questionIcon.tsx
src/assets/images/tildeIcon.tsx

Components that render SVG should have props such as `stroke-width` should be camelCased. This PR fixes the ones I could find in `/src`

Fix props on components with inline SVG

---

src/components/LocationPage/ChartsHolder.tsx
src/components/SocialLocationPreview/SocialLocationPreview.tsx
src/models/Projection.ts
src/screens/About/About.tsx
src/screens/ModelPage/ModelPage.js

I wasn't sure where to put the `County` type declaration.

Fix county sharing and About page typo

---

src/models/Projection.ts

Our r(t) indicator algorithm uses smooting such that new data points can
substantially shift the prior ~7 days of data. So we are not including it in
the calculation. @pnavarrc is additionally working on a change to the charts to
show this data as a dotted line.

Ignore the last 7 days of r(t) data when calculating official metric.

---

src/components/Charts/utils.ts
src/components/Charts/zoneUtils.js

Close https://trello.com/c/XaDBcNF8/106-make-the-last-week-of-rt-dotted-and-use-the-value-from-7-days-ago-in-the-metric-ui
cc @mikelehen @igorkofman

update the Rt chart to dot the most recent 7 days

---

src/api/index.ts
src/assets/data/data_url.json
src/components/LocationPage/ChartsHolder.tsx
src/enums/zones.ts
src/models/Projection.ts

Reverts covid-projections/covid-projections#724. There's an issue with the dates aligning between actuals and predicted numbers that needs to be addressed. it's a little tricky so best to keep staging clean. I'll work on a fix tomorrow am

Revert "Adding ICU headroom calculation"

---

src/models/Projection.ts

Disable ICU Headroom for Utah / Utah counties to unblock deploying a new data snapshot.
See https://trello.com/c/CrcF4MsE/112-model-utah-icu-utilization-unreasonably-low-in-latest-snapshot (or Slack) for context...

Disable Utah ICU headroom metric.

---

src/components/Charts/ModelChart.js
src/components/MapSelectors/GlobalSelector.js
src/models/Projections.ts
src/screens/Embed/ChartsTab.js
src/screens/Embed/Embed.js
src/screens/Embed/ProjectionsTab.js

This is a precursor to make my next PR possible which deletes ~750 lines of code (related to state interventions, social distancing, stay-at-home, etc.).  The changes are separated into 3 different commits if that's easier to review.
It contains 4 behavioral changes:
**Before:**
**After:**
---
**Before:**
**After:**
---
**Before:**
**After:**
---
The 14 counties on the blacklist were the only places on the site where we were still showing a "stay at home" projection.  But I checked all of them, and the inference projection is virtually identical to the stay-at-home projection, so I don't think the blacklist is necessary any more.  If we want to keep it, I suggest we just treat these counties as no-data counties rather than showing stay-at-home.
Example: Hall County, NE
**Before:** …

Tweak site functionality to enable cleanup.

---

src/components/AppBar/AppBar.tsx
src/components/ShareBlock/ShareBlock.tsx
src/components/ShareBlock/ShareModelBlock.js

I noticed that all our share text started with '@covidactnow...' If you start a tweet with an “@handle...”, only people who follow both the tweeter and the @handle will see the tweet. 
So, net-net, virtually nobody is seeing tweets about us from our sharing buttons.
This PR fixes that (updating 3 different files)
cc @schlosser @igorkofman @mikelehen for one of you to review

Jt sharing text update

---

src/components/AppBar/AppBar.tsx

- Redirects to homepage if an invalid state or county is entered into URL
- Previously: invalid county would return a blank page, invalid state would return a blank page with CAN header/footer

Redirect if invalid state or county in URL

---

src/components/Charts/ChartRt.tsx

The most recent confirmed value for R(t) is shown as "preliminary", this is a bug. This PR fixes that (the screenshot doesn't show it, but the cursor is hovering the highlighted point)
**Production** 
**This branch** (I should have taken a screenshot of the same location, but I didn't, sorry!)

Charts - Fix the tooltip for the current R(t) value

---

src/common/models/Projection.ts

Removes days with negative values when calculating avg cases/day.  This makes WA closer to reality (139 cases/day instead of 97), but still is questionable, since in addition to a negative value (now removed) there are several very low values pulling the average down:
```
[267, 225, 130, 30, 5, 178]
```
**Before:**
**After:**
I spot-checked ~5 other states and they were completely unaffected.

Ignore days with negative cases when calculating cases/day for contact tracing.

---

package.json
src/components/Charts/ChartContainer.tsx
src/components/Charts/ChartPositiveTestRate.tsx
src/components/Charts/ChartRt.tsx
src/components/Charts/ChartZones.tsx
src/components/Charts/Charts.style.ts
src/components/Charts/Tooltip.tsx
src/components/Charts/ZoneAnnotation.tsx
src/components/Charts/ZoneLinePath.tsx
src/components/Charts/index.tsx
src/components/Charts/utils.ts
src/components/LocationPage/ChartsHolder.tsx
src/screens/internal/AllStates/AllStates.js
yarn.lock

Closes https://trello.com/c/2IEGjPVL/150-rewriting-charts-positive-tests
This chart re-implements the Positive Test Rate chart and extracts common code from `ChartRt` into components so it can be reused. The `ChartZone` component can be also used for ICU hospitalization rate and contact tracing, but I prefer to change those in separate PRs to make it easier to test.
Can @goldblatt review?

Chart Remake - Positive Test Rate

---

src/assets/theme/palette.tsx
src/components/Charts/BoxedAnnotation.tsx
src/components/Charts/ChartContactTracing.tsx
src/components/Charts/ChartFutureHospitalization.tsx
src/components/Charts/ChartICUHeadroom.tsx
src/components/Charts/ChartPositiveTestRate.tsx
src/components/Charts/ChartRt.tsx
src/components/Charts/ChartZones.tsx
src/components/Charts/Charts.style.ts
src/components/Charts/Legend.tsx
src/components/Charts/RectClipGroup.tsx
src/components/Charts/Tooltip.tsx
src/components/Charts/index.tsx
src/components/Charts/utils.ts
src/components/LocationPage/ChartsHolder.tsx

This PR re-implements the Future Hospitalizations chart
**Other Changes**
- beb01cfb629f0ecde29d442c965b64921af3e90b Added padding to the clipping region, to avoid cutting half of the line when they hit the top of the chart.
- 04d8c55fbf1fdc9eaae48d2521abf989eec5ad52 Update the Tooltip component so it can receive children and minor styling fixes. This is needed because the tooltip for the Future Hospitalizations chart is formatted (some text is in bold).
- The Highcharts version allows us to toggle the series on and off by clicking on the legend. I vaguely remember that this behavior wasn't desired, because it allowed the user to hide all of them, so I didn't implement that. We can implement it if that's something we want to have (or a variation of it)
- I haven't removed the old chart …

Charts Remake - Future Hospitalizations

---

src/App.js
src/assets/theme/palette.tsx
src/components/Charts/ChartFutureHospitalization.tsx
src/components/Charts/Charts.style.ts

This makes the charts minimally "theme-able" and adds a dark set of colors for them.
To see how this gets used in the chart sharing, see [here](https://github.com/covid-projections/covid-projections/pull/825/files#diff-f5680937bf6b070548b0898693f6fc04R69)
And preview: https://covid-projections-git-mikelehen-share-charts.covidactnow.now.sh/internal/share-image/states/wa/chart/0

Make charts 'theme-able' and add a 'dark' theme.

---

src/components/Charts/ChartContainer.tsx
src/components/Charts/ChartFutureHospitalization.tsx
src/components/Charts/ChartZones.tsx
src/components/Charts/HoverOverlay.tsx

Follow up from https://github.com/covid-projections/covid-projections/pull/822
This PR adds assertions to check that the charts have enough data to have a min/max for x and y, and remove some default values that were there as safeguards.

Asserts that the charts have data

---

src/App.js
src/components/ScrollToTop/ScrollToTop.tsx
src/components/ScrollToTop/index.tsx

Fix [Bug: Clicking on county often scrolls to bottom of location page.](https://trello.com/c/CQpybrw0/114-bug-clicking-on-county-often-scrolls-to-bottom-of-location-page) - Clicking on county often scrolls to the bottom of the location page
I found a solution here https://reacttraining.com/react-router/web/guides/scroll-restoration. The `useEffect` hook is triggered every time `pathname` is updated, scrolling the client to the top.
- Go to a location page, scroll all the way to the bottom (https://covid-projections-git-pablo-scroll-to-top.covidactnow.now.sh/us/wa)
- Click on a county
- In `develop`, the browser will navigate to the county, but will be scrolled down all the way to the bottom. In this branch, the browser scrolls to the top as it renders the county page.

Scroll to top when navigating to a new county/state

---

src/assets/theme/palette.tsx
src/common/metrics/case_growth.ts
src/common/metrics/contact_tracing.ts
src/common/metrics/hospitalizations.ts
src/common/metrics/positive_rate.ts
src/common/utils/index.ts
src/components/Charts/ChartContactTracing.tsx
src/components/Charts/ChartFutureHospitalization.tsx
src/components/Charts/ChartICUHeadroom.tsx
src/components/Charts/ChartPositiveTestRate.tsx
src/components/Charts/ChartRt.tsx
src/components/Charts/ChartZones.tsx
src/components/Charts/Charts.style.ts
src/components/Charts/Tooltip.style.ts
src/components/Charts/Tooltip.tsx
src/components/Charts/utils.ts
src/components/Charts/zoneUtils.js
src/components/SummaryStats/SummaryStats.tsx

Close [Better UX for preliminary Rt data + add Confidence Intervals](https://trello.com/c/fQX9Jxxj/115-better-ux-for-preliminary-rt-data-add-confidence-intervals)
I tried to replicate the styles from [Figma - Preliminary Data for Rt](https://www.figma.com/file/xGLbdgTR348eQmmIpvBrvF/Preliminary-data-for-Rt?node-id=0%3A1), but the width of the tooltip wasn't big enough in some cases.
I also updated the tooltips for the other charts (see screenshots below) trying to keep the styles consistent with the new and existing design. The body of the future hospitalizations chart is the one that departs most from the others.
Note: Used the [triangle trick](https://css-tricks.com/snippets/css/css-triangle/) for the tooltip arrow. I only implemented the arrow down since that's the only one we need for …

Better UX for Preliminary Rt Data 

---

scripts/generate_index_pages.ts
scripts/generate_share_images/index.ts
src/assets/data/share_images_url.json

* Modify generate_share_images to generate the additional share / export images (e.g. /states/wa/chart/0.png)
* Modify generate_index_pages to generate the additional share chart index.html files (e.g. /us/wa/chart/0/index.html)
I had to do some refactoring to combine our handling of states / counties better to avoid duplicating too much code.

Update generate_index_pages and generate_share_images for chart sharing.

---

scripts/generate_index_pages.ts
src/common/urls.ts
src/components/AppBar/AppBar.tsx
src/components/EnsureSharingIdInUrl/EnsureSharingIdInUrl.tsx
src/components/EnsureSharingIdInUrl/index.ts
src/components/LocationPage/ShareButtons.js
src/components/ShareBlock/ShareBlock.tsx
src/screens/HomePage/HomePage.js
src/screens/LocationPage/LocationPage.js

This adds a unique ?s=123 ID to our homepage / location URLs to ensure that Facebook / Twitter / etc. fetch fresh versions of them instead of using an old cached version of the page (and therefore the sharing preview image).
The ID corresponds to the ID in our sharing URL so it'll always update whenever we update our sharing images.
Fixes https://trello.com/c/iPbx5dC5/

Add "sharing ID" to URLs to prevent unwanted caching.

---

src/components/ShareBlock/EmbedPreview.js

Some `Grid` elements were missing the `item` property, which was throwing a warning in development.

Fix warnings for missing item property on Grid

---

src/components/Charts/Charts.style.ts

Fixes the default font for the charts
While working on #850 - Implement 4th color, I noticed that the box around the "Critical" didn't enclose the text correctly. This happens because during the first render the browser uses the default font to measure the box, and doesn't measure it again when the fonts are loaded.
If we change the default font to `monospace`, the discrepancy between size of the box calculated with the default font and with `Source Code Pro` is almost unnoticeable.
It also changes the fallback `Roboto` to `Roboto Mono` since we expect the font of the chart to be monospaced.
- Change the `text` to `"Critical"` on [src/components/Charts/BoxedAnnotation.tsx#L37](https://github.com/covid-projections/covid-projections/blob/master/src/components/Charts/BoxedAnnotation.tsx#L37) …

Charts - Fix the default and fallback fonts

---

src/common/models/Projection.ts
src/common/models/Projections.ts
src/components/Charts/MetricChart.tsx
src/components/LocationPage/ChartsHolder.tsx
src/components/SummaryStats/SummaryStats.tsx

In particular, this fixes:
1. The Montana ICU chart truncating at May 18, due to the value going to 0%.
2. The Hawaii ICU chart disappearing entirely because it was all 0's.
**Before:**
**After:**
**Before:**
**After:**

Fix several issues with conflating null and '0', leading to our metrics disappearing when the metric goes to 0.

---

src/common/models/Projection.ts

A number of states seemingly made large corrections to their test reporting in the last week or two resulting in large _negative_ deltas in the day/day numbers, which was wagging the positive test rate metric around...
This PR fixes our deltasFromCumulatives() code to always ignore negative deltas (replace them with a null) and then consequentially our calcTestPositiveRate() needed to deal with nulls properly.
A bunch of states were affected modestly, but a few had big changes, e.g.:
**DC Before**
**DC After**
---
**GA Before**
**GA After**
---
**MO Before**
**MO After**

Ignore negative deltas in cumulatives. Fixes test positive rate for several states.

---

src/components/Charts/ChartFutureHospitalization.tsx
src/components/Charts/ChartRt.tsx
src/components/Charts/ChartZones.tsx

Fixes a bug that was causing the y-axis ticks to be misaligned by 5px.
I noticed this while working on https://github.com/covid-projections/covid-projections/pull/889, I increased the margin-top to accommodate the intervention annotations, and then all the values for the y-axis ticks were misaligned.
In [`ChartContainer.tsx#L58`](https://github.com/covid-projections/covid-projections/blob/master/src/components/Charts/ChartContainer.tsx#L58) component adds the margin-left and margin-top for all its child components, so by setting the `marginTop` property on the `AxisLeft component, we were moving down the y-axis 5px down.
I also removed the `AxisLeft` from the `ChartFutureHospitalizations` because this chart doesn't have an axis (I added it during development and forgot to remove it …

Fix alignment of y-axis ticks on all charts

---

src/components/Charts/ChartFutureHospitalization.tsx

Close [193](https://trello.com/c/ALh0HTSt/193-make-sure-capacity-horizontal-line-is-labeled-in-projection-charts) - Make sure that the capacity horizontal line is labeled in projections chart
The vertical scale maps the min and max values on the data to the min and max values of the inner chart dimensions in pixels. If the number of beds is the maximum data value, the label ends up outside the chart because it's above the line.
This PR moves the label outside the clipping path boundaries to avoid cropping the label and adjusts the chart margins a bit so it fits. I also adjusted where the minimum value goes (`chartHeight - MAX_LINE_WIDTH`) to avoid hiding the lines if they are too close to the x-axis.
**Before** https://covidactnow.org/us/ak?s=41740
**After** …

Charts - Fix missing label on hospitalizations chart

---

src/screens/internal/ShareImage/ShareCardImage.style.ts

**Trello:** https://trello.com/c/C1ypJQvo/224-home-page-share-card-is-truncated
**Before:**
**After:**

Tweak scaling homepage share card image so that legend isn't truncated.

---

src/components/LocationPage/NewLocationPageHeader.style.tsx

lil change: adds back in gray border between 'share' and 'get alerts' buttons (mobile only)

Header buttons style-fix

---

src/common/models/Projection.ts

Update default decomp factor to 25% and override states that are >5% off of the 25% (based on CDC estimates)

Adjust decomp factor from 30% to 25% (#932)

---

src/components/Header/HomePageHeader.style.tsx
src/components/Header/HomePageHeader.tsx

This PR removes the first line of the subheading on mobile.
From [Slack](https://covidactnow.slack.com/archives/C011CKR2B2B/p1591811774012400)
Can @igorkofman review?

Hide the first line in home page subheading on mobile

---

src/components/Map/Legend.style.js

Close [221](https://trello.com/c/jJE61NeP/221-ui-fix-on-homepage-make-homepage-legend-2x2-on-mobile) - Make the map legend 2x2 on mobile
I set `flex-direction: column` instead of `flex-direction: row` to make sure that the orange item is below red (instead than on the first row).
Can @mikelehen review? Thanks!

improve the alignment of map legend items on mobile

---

src/common/models/Projection.ts

@BrettBoval noticed that we were showing overload dates beyond the truncated chart, e.g. CA on prod:

Truncate 'Hospital Overload Date' to 30 days.

---

src/assets/data/data_url.json
src/assets/data/share_images_url.json

We already bumped to this snapshot, but this updates the share URL as well.
Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

Deploy share images for snapshot 637. (#1029)

---

src/components/MiniMap/MiniMap.style.tsx
src/components/MiniMap/MiniMap.tsx
src/components/MiniMap/index.ts
src/screens/LocationPage/LocationPage.js

Updates the MiniMap component to accommodate the prevalence metric. See the designs in [Figma](https://www.figma.com/file/kQGQ5qsDh7ir4MhjMM20Tl/5th-metric?node-id=48%3A2025)
I updated the layout to match the designs and added a sized container for the state maps, we need this to adjust the map projection parameters later (center, rotation, scale) so they use the entire available area for the map. I will implement that in a follow-up PR.
Can @goldblatt and @chasulin review? Thanks!

Update the MiniMap component

---

src/common/metrics/contact_tracing.ts
src/components/Charts/utils.ts

Removes the `CRITICAL` level for the contact tracing chart and moves the upper limit of the orange level from 7% to 10%.
This is done by changing the upper limit of the `CRITICAL` threshold to `0` and updating the upper level of `HIGH` from 7% to 10%. I updated how regions (the equivalent of levels, but with upper and lower limits) to filter out regions such that their lower and upper limit are too close (< 1e3).
Can you review @mikelehen ?

Prevalence - Update the critical threshold for contact tracing

---

src/common/metrics/contact_tracing.ts
src/common/models/Projection.ts

This is a purely optional refactor that we could punt for now, but I started down this path while I was trying to track down an issue I was seeing.  If you're not a fan or are busy, we could hold off on this.

Refactor: Use smoothWithRollingAverage() instead of getWeeklyAverageForDay().

---

src/components/Charts/ChartCaseDensity.tsx

Adding a cap for the case density chart. We need to review the value, set to 100 for now.
http://localhost:3000/us/tx/county/garza_county?s=665110
- I changed the curve parameter as an experiment, after realizing that `curveNatural` can produce strange loops depending on how much the value of the curve changes between 2 points. I think we should change all the lines to use [`curveMonotoneX`](https://github.com/d3/d3-shape#curveMonotoneX) instead. From the docs:
> “a smooth curve with continuous first-order derivatives that passes through any given set of data points without spurious oscillations. Local extrema can occur only at grid points where they are given by the data, but not in between two adjacent grid points.”
Compare

Prevalence - Add cap for case density chart

---

package.json

Updates the `build` script to skip the generation of `index.html` pages on Vercel and local development.
It seems that we are hitting the [limits](https://vercel.com/docs/v2/platform/limits) for the number of generated files for Vercel builds. Since we only need to generate them on production and staging, I removed it from the `build` script to keep us under the limit.
Can @mikelehen review?

generate index pages only on staging and prod builds

---

src/screens/internal/ShareImage/ShareCardImage.style.ts

- Edits sharecard so map+legend both fit in entirety
Before:
After:

Sharecard fix (homepage)

---

src/components/Charts/Axis.tsx
src/components/Charts/ChartRt.tsx
src/components/Charts/ChartZones.tsx
src/components/Charts/utils.ts

- Calculate the end date of the chart to ensure that the threat level labels don't overlap the last point of the time series instead of just adding 2 weeks and hope for the best.
- Changed the format of the x-axis tick labels from full month to 3-letter abbreviations (September → Sep).
- Moved the current point annotation from being on the right of the last point to be on top of the last point, to minimize the chance of overlapping with the zone labels.
Before → After
Before
After
- There is some discussion around getting rid of the zone labels on mobile, but I'm going to submit a separate PR so we can get feedback on that change.
- The margins can be optimized as well, I will do that on a separate PR too.

charts - minor improvements for mobile and share images

---

src/common/metrics/case_density.ts
src/common/models/Projection.ts

This PR adds the copy from [CAN Phase 3 Webapp Text](https://docs.google.com/document/d/1Jsj4zOksCJcgjQLUo3rwVAobEUkGLFukD1K71IqVNpo/edit#) for the prevalence metric.
Note: The copy for case density is not complete in the document, adding what we have for now.

Prevalence - Status text copy

---

src/common/models/Projection.ts
src/screens/internal/CompareSnapshots/CompareSnapshots.tsx

* We were assuming that cumulativeConfirmedCases and cumulativePositiveTests were interchangeable, but they're not. E.g. Marion County, IN has good cumulativeConfirmedCases, but cumulativePositiveTests is garbage.  So we use cumulativeConfirmedCases now for the contact tracing and case density metrics.
Also added new case density metric to compare tool (mostly because it made it easier
for me to sanity-check all the graphs).
Before this change (with deaths disabled):
After this change (with deaths disabled):

Use cumulativeConfirmedCases instead of cumulativePositiveTests where applicable.

---

src/common/models/Projection.ts

Updates how the case density metric is calculated to use only cases. See the [discussion on Slack](https://covidactnow.slack.com/archives/C0177KERT89/p1594945641003000)
Note: I left the function just in case we need to put deaths back in the mix, I will remove the ranges and unused properties and functions once we confirm the calculation.

prevalence: calculate case density by cases only

---

src/common/colors.js
src/common/models/Projections.ts
src/components/Header/HomePageHeader.style.tsx
src/components/LocationPage/LocationPageHeader.style.tsx
src/components/LocationPage/LocationPageHeader.tsx
src/components/Map/Map.js
src/components/Map/Map.style.js
src/components/MiniMap/MiniMap.style.tsx
src/components/MiniMap/MiniMap.tsx
src/components/SummaryStats/LocationHeaderStats.tsx
src/components/SummaryStats/SummaryStats.style.tsx
src/screens/HomePage/Announcements/Announcements.style.tsx
src/screens/HomePage/Announcements/Announcements.tsx
src/screens/HomePage/CriteriaExplanation/CriteriaExplanation.style.tsx
src/screens/HomePage/HomePage.style.js
src/screens/HomePage/HomePageThermometer.style.tsx
src/screens/internal/ShareImage/ShareCardImage.style.ts
src/screens/internal/ShareImage/ShareCardImage.tsx

This PR adds the copy for the Updates section on the Location page header.
For testing:
- New York changed
- Washington State didn't change
The copy is still preliminary, but since we will probably need the change in levels due to the introduction of prevalence it's better to have the levels ready.
Note that the function `getAlarmLevelWithoutCaseDensity` is only useful while the update is relevant (a few weeks after the release of prevalence), so we can remove this function once it's no longer necessary.

prevalence: add the update copy on the location page header

---

src/components/Charts/ChartCaseDensity.tsx

I fixed the spacing of labels in `develop` but didn't include the fix for the case density chart. Note that since the case density chart doesn't have uncertainty interval anymore, we can reuse ChartZones as we do with other charts. I will replace it later, just in case we need to put the intervals back or implement other custom elements for this chart.

case density: minor chart fixes

---

src/components/LocationPage/ChartsHolder.tsx
src/components/LocationPage/LocationPageHeader.tsx
src/components/SummaryStats/LocationHeaderStats.tsx

Fixes [Trello 317](https://trello.com/c/kz9wMPgk/317-clicking-the-case-incidence-metric-scrolls-to-the-rt-chart) - Clicking on the case incidence stat scrolls to the Rt chart.
I missed this when implementing the chart, fixed now :)

case incidence: clicking on the case incidence stat scrolls to the correct chart

---

src/components/LocationPage/ShareButtons.js

case incidence charts currently download with 'undefined' in filename, ie. "nd_undefined_2020-07-22.png". this pr will set filename to "nd_case_incidence_2020-07-22.png"

Prevalence-adds chart download filename

---

src/common/metric.ts
src/components/LocationPage/ChartBlock.tsx
src/screens/internal/ShareImage/ChartExportImage.tsx
src/screens/internal/ShareImage/ChartShareImage.tsx

Our share and download images for case density do not currently include the words "per 100k population" anywhere. This PR adds "per 100k population" to the images' headers.

Prevalence-share/export image header update

---

src/components/Charts/ChartCaseDensity.tsx

From [Slack](https://covidactnow.slack.com/archives/C0177KERT89/p1595453168127300)
The "Low" level for case incidence goes from `0` to `1`, which is too narrow to show the label in the chart. We added some padding before to make room for it, but as a consequence, the chart ends up being a bit misleading, as the spacing between the x-axis and 1 is the same as the space between 1 and 10.
This fix hides the "Low" label and sets the min y-axis to 0 if the current level is not Low, and makes room and adds the "Low" label if the current Level for the location is "Low".

improve the spacing of case incidence level annotations

---

scripts/alert_emails/campaign-monitor.ts
scripts/alert_emails/send-test-email.ts
scripts/alert_emails/send_emails.ts

Fixes the handling of invalid emails in the `send_emails` script. It also fixes the name of the collection with invalid emails. 
This is how I tested:
**Setup**
- Make sure that you have the `CREATE_SEND_TOKEN` environment variable set.
- Make sure that you have the `scripts/alert_emails/google-service-account.json` with the development credentials.
- Unzip the [alerts.json.zip](https://github.com/covid-projections/covid-projections/files/4973819/alerts.json.zip) on `scripts/alert_emails`
**Testing**
1. Run `yarn send-test-email invalid@email.com,` - This will try to send a test email to the address `invalid@email.com,` (note the `,` after the email, that passes the regex, but Campaign Monitor rejects it). It should fail and log the `Invalid email` error in the console.
2. Add the invalid …

fix handling of invalid emails

---

scripts/alert_emails/template.html
scripts/alert_emails/utils.ts

* Change alert template to use "risk increased" and "risk decreased" again (but keep "new risk
score" for unknown=>non-unknown transitions.
* Fix unsubscribe link. I'm not sure how long it's been broken, but Handlebars was html-escaping the
URL in a way that CreateSend didn't like when it tried to add click-tracking to it.

Alert Email Fixes

---

src/components/Header/SearchHeader.tsx

Fixes [trello item re: minimap not closing when search bar is open](https://trello.com/c/TWpPenNR/329-map-doesnt-disappear-when-clicking-on-the-search-bar-on-mobile)

Fix: search bar/minimap 

---

src/App.js

We are creating a vanity URL for the response simulator to make it easier to share. The URL is just redirecting to `/resources#covid-response-simulator`
`https://covidactnow.org/response-simulator`

add a URL for the response simulator

---

src/components/Compare/Compare.style.tsx
src/components/Compare/LocationTable.style.tsx
src/components/Compare/LocationTable.tsx

compare: minor styling fixes

---

src/common/utils/compare.ts
src/components/Compare/LocationTable.tsx
src/components/LocationPage/ChartsHolder.tsx

This PR fixes a couple of `any` I left when fixing the scroll behavior and pinned location on the compare table. It doesn't fix everything, but it's a bit better than before.

compare: small typing fixes

---

src/common/utils/compare.ts
src/components/Compare/Compare.style.tsx
src/components/Compare/CompareTable.tsx
src/components/Compare/CompareTableRow.tsx
src/components/Compare/LocationTable.style.tsx
src/components/Compare/LocationTable.tsx

This PR updates the compare table to make sure that the row for the current location (for counties) always shows in the inline version of the table in a position relative to its ranking. 
**Top**
The Karnes County is at the top given the current sorting of the table, so it shows at the top.
**Middle**
Cameron County is in the first 6 locations, so it shows in the corresponding location.
**Bottom**
Jim Wells County should be below the fold, so it shows at the end with its corresponding ranking.

show current location in ranked position

---

src/common/metric.tsx
src/common/metrics/case_density.tsx
src/common/metrics/case_growth.tsx
src/common/metrics/contact_tracing.tsx
src/common/metrics/future_projection.tsx
src/common/metrics/hospitalizations.tsx
src/common/metrics/interfaces.ts
src/common/metrics/positive_rate.tsx
src/components/Disclaimer/Disclaimer.tsx

This PR adds `renderDisclaimer` to the `MetricDefinition` interface, and moves the copy accordingly.

 add disclaimer to metric definition

---

scripts/alert_emails/utils.ts

This PR creates a different group for each email alert send so we can have engagement stats for each send instead of having them grouped together.

rename the alert email groups for better tracking

---

src/components/Explore/Explore.style.ts
src/components/Explore/Explore.tsx
src/components/Explore/ExploreTabs.tsx
src/components/Explore/index.ts
src/components/LocationPage/ChartsHolder.tsx

Implement the Tab component for Explore. I added placeholders for the other components of the Explore block. The component is at the bottom of the location page.
- [Mocks](https://www.figma.com/file/nkoC6P02eXxkB95ukdU6Ms/Explore?node-id=260%3A24)
**Desktop**
**Mobile**

explore: tab component

---

src/components/AppBar/AppBar.tsx
src/components/LocationPage/SocialButtons.js
src/components/ShareBlock/ShareBlock.tsx

"I’m keeping track of the latest COVID data and risk levels with @CovidActNow. What does your community look like?" is what I used as the new default share text.   More than happy to change this, but wanted to put a proposed change in motion!

changing default share text to not start with @CovidActNow

---

src/components/Charts/BarChart.tsx
src/components/Explore/Explore.style.ts
src/components/Explore/Explore.tsx
src/components/Explore/ExploreChart.tsx
src/components/Explore/SeriesChart.tsx
src/components/Explore/interfaces.ts
src/components/Explore/utils.ts
src/components/LocationPage/ChartsHolder.tsx

This PR implements the Explore chart container and the BarChart component. [Design Specs](https://www.figma.com/file/nkoC6P02eXxkB95ukdU6Ms/Explore?node-id=260%3A25)
- The demo won't include comparing with other location, but I prepared the API of the `ExploreChart` component so it can receive an array of series. For the MVP, it will only show raw and smoothed data.
- The axes need some tweaking to match the designs, more PRs to come!

explore: implement chart container and bar chart

---

src/common/models/Projection.ts
src/components/Explore/Explore.tsx
src/components/Explore/ExploreChart.tsx
src/components/Explore/SeriesChart.tsx
src/components/Explore/interfaces.ts
src/components/Explore/utils.ts

It looks like our rolling average function "translates" the data forward by a week, the effect is more noticeable with hospitalization data.
@mikelehen @chasulin can you double-check that I'm using the correct metrics in each case? I need to adjust the smoothed line to not go to zero before and after having data, but I will do that on a separate PR

explore: use the real datasets

---

src/components/Explore/ExploreChart.tsx
src/components/Explore/utils.ts

Small fix to adjust tick positions to what we have in [the mocks](https://www.figma.com/file/nkoC6P02eXxkB95ukdU6Ms/Explore?node-id=260%3A24)

explore: format x-axis labels and tick positions

---

DEV_README.md
README.md
scripts/update_location_summaries.ts
src/api/index.ts
src/common/colors.js
src/common/index.js
src/common/interventions.js
src/common/models/Projection.ts
src/common/models/Projections.ts
src/common/utils/makeChartShareQuote.js
src/common/utils/model.ts
src/components/Charts/MetricChart.tsx
src/components/LocationPage/ChartsHolder.tsx
src/screens/Embed/Embed.js

NOTE: This is low-pri.  No rush. 
With the removal of future projections and the outcomes table, we no longer
need any intervention-related code.
We now only load the OBSERVED_INTERVENTION api endpoint, not NO_INTERVENTION.
This makes the location page, compare tool, update-location-summaries, etc. faster.

Remove legacy intervention-related code.

---

src/components/MapSelectors/GlobalSelector.js

Was showing 'contains zipcode' even if there was no zipcode match.
Before
After

Fix displaying contains zipcode if no matched zips in list

---

src/common/models/Projection.ts
src/components/Charts/ChartCaseDensity.tsx
src/components/Charts/Tooltip.style.ts
src/components/Charts/Tooltip.tsx

This PR enhances the tooltip on the "Daily new cases per 100k population" chart.
The tooltip now includes 7 day average new cases for a given day. 
(Addresses https://trello.com/c/O9nRsq19/358-implement-new-new-cases-tool-tip.)

Enhance Daily New Cases Tooltip

---

src/common/metrics/case_density.tsx
src/common/metrics/case_growth.tsx
src/common/metrics/contact_tracing.tsx
src/common/metrics/hospitalizations.tsx
src/common/metrics/positive_rate.tsx

Some more metrics cleanup - removing unused variables and exports.

remove unused exports from metric files

---

src/common/locations.ts
src/components/CountyMap/CountyMap.js
src/components/Map/USACountyMap.js
src/components/MiniMap/MiniMap.tsx

This PR changes how we do navigation when clicking on locations on the map. In production, we pushed the new URL to the [`history`](https://reactrouter.com/web/api/history). 
This PR replaces navigation for the maps with the [`Link`](https://reactrouter.com/web/api/Link) component in order to allow opening links on a new tab, using the contextual menu to copy the link address, among others. If we go with this solution, we need to also replace links on:
- Compare table
- Top navigation bar
- Footer
but we can do that on a separate PR.

add links to state and county maps

---

src/components/MapSelectors/GlobalSelector.js

This PR adds a stateReducer function to the Downshift element that captures the escape key event and overrides the default behavior and closes the menu.  The default behavior is to pass null the onChange callback, which was causing the error.

Fix Escape Key Bug

---

src/screens/Resources/Resources.tsx

Debbie surfaced that the actual link to the COVID Response Simulator is buried under a lot of content, this PR adds a direct link under the title to make it more obvious.

update copy for covid response simulator section

---

package.json
src/App.js
src/components/Banner/FeedbackSurveyBanner.tsx
src/components/Banner/index.ts
src/screens/HomePage/HomePage.js
yarn.lock

- Adds the feedback survey banner in the homepage
- It attaches a random ID to the Typeform URL, so we can track which responses belong to the same individual (we need this to link the first part of the feedback form to demographics, which are in the 3rd part of the survey)
- Adds a redirect so we can track users coming from social media with a unique ID as well. The link shared in social will be `https://covidactnow.org/feedback-survey`, upon clicking, the user will be redirected to the Typeform URL with `source=social&id={UNIQUE_ID}`

feedback survey: add banner with tracking links

---

src/App.js
src/components/Banner/FeedbackSurveyBanner.tsx
src/components/Banner/index.ts
src/components/ExternalRedirect/ExternalRedirect.tsx
src/components/ExternalRedirect/index.ts
src/screens/Resources/Resources.tsx

We want to track clicks to the COVID Response Simulator. Since Google Analytics already tracks page views for all our pages, one way to track clicks is to replace the URL of the CRS with an internal link to `/covid-response-simulator-redirect` and configure the router to redirect visits to  `/covid-response-simulator-redirect` to the actual CRS URL.
The `Redirect` component from `react-router-dom` only redirects to pages within the application, so I implemented a component to hide the implementation details of the external redirect.

add redirect to track clicks to the covid response simulator

---

src/components/Explore/Explore.style.ts
src/components/Explore/ExploreChart.tsx
src/components/Explore/utils.ts

This PR changes the format of the date marker to show weeks and days ago instead of the default from `moment().fromNow()`.
- Changes the format of the date marker to weeks and days ago.
- Do not show the marker for dates in the future.
- The last points are missing, I'm going to fix that on a separate PR.

explore: update the date marker to show relative time in weeks and days

---

src/components/Explore/SeriesChart.tsx

This PR changes the curve type for the smoothed series in the explore chart. The type of curve we were using, `curveCardinalOpen` doesn't show the first and last point, here we are using `curveCardinal` which doesn't have this problem (See https://github.com/d3/d3-shape#curves).

explore: change curve type to show the first and last points

---

src/components/Explore/utils.ts

This PR fixes the URL of the export image for the Explore feature.

explore: fix the export image url

---

src/components/Explore/Explore.style.ts
src/components/Explore/ExploreChart.tsx

This PR updates the tooltip to include both the smoothed value and the raw value for the series. I also adjusted the width of the tooltip to make it narrower.

explore: add the smoothed series to the tooltip

---

src/components/Compare/LocationTable.tsx

- Fixes (removes) gap at the bottom of compare modal that occurs when metro menu is not displayed (mobile only)
Before:
After:

Fix: compare modal

---

src/components/Compare/Compare.style.tsx
src/components/Compare/CompareTableRow.tsx

- Adds ability to open a row's corresponding location page in a new tab
- Replaces navigation via pushing URL to `history` with navigation via `Link` component

Compare: open in new tab

---

src/common/colors.js
src/common/location_summaries.ts
src/common/utils/model.ts
src/common/utils/snapshots.ts
src/components/Charts/ChartContainer.tsx
src/components/Explore/ExploreChart.tsx
src/components/Map/Map.js
src/components/Map/USACountyMap.js
src/components/Screenshot/ScreenshotReady.tsx
src/components/Screenshot/index.ts
src/screens/internal/ShareImage/ChartExportImage.tsx
src/screens/internal/ShareImage/ChartShareImage.tsx
src/screens/internal/ShareImage/ExploreChartExportImage.tsx
src/screens/internal/ShareImage/ExploreChartImage.tsx
src/screens/internal/ShareImage/ShareCardImage.tsx

* Allow passing ?snapshot=xyz to most pages to choose what snapshot to use for rendering. This lets us generate screenshots for non-current snapshots as necessary.
* Refactor USACountyMap "summaries file" usage so that it can render maps for non-current snapshots.
* Add a <ScreenshotReady/> component that must be used to signal when the screenshot content is fully rendered and ready to be captured (i.e. all async requests are done, etc.).
For an example of what the first two bullets enable, see:
https://covid-projections-git-mikelehen-host-share-images-prework.covidactnow.vercel.app/?snapshot=983
vs
https://covid-projections-git-mikelehen-host-share-images-prework.covidactnow.vercel.app/?snapshot=974

Website tweaks to enable dynamic screenshot generation.

---

src/components/Charts/BarChart.tsx
src/components/Explore/EmptyChart.tsx
src/components/Explore/Explore.style.ts
src/components/Explore/Explore.tsx
src/components/Explore/ExploreChart.tsx
src/components/Explore/utils.ts
src/components/Map/USACountyMap.js

Addressing feedback from [CAN Explore - Feedback](https://paper.dropbox.com/doc/CAN-Explore--A6wWR1iltDXmI1xe4ZTRyFhrAg-RIlOIJkMWHcX0AmXQA5PW)

explore: v1 fixes

---

.github/workflows/update-snapshot.yml
src/assets/data/share_images_url.json

Note: This is a bit hard to validate as-is.  We should probably merge to staging and then load some sharing URLs (e.g. https://staging.covidactnow.org/us/wa/chart/0/?s=987199), look at the meta tags served (should be the new covidactnow-prod.web.app URL), and then verify the image URL serves the expected image.

Move over to the dynamic image serving.

---

src/common/utils/index.ts
src/components/Explore/Explore.tsx
src/components/Explore/ExploreChart.tsx

- Fix the metric name in the subtitle
- Make the 7-day average less prominent
- Shows the 7-day average with one decimal digit

explore: small improvements and fixes

---

src/components/LocationPage/ShareButtons.js

Now that we generate download images dynamically, there's a few second delay before they download.  This PR adds a spinner so the user knows it's working...

Show a spinner while downloading charts.

---

src/common/locations.ts
src/components/AutocompleteLocations/AutocompleteLocations.tsx
src/components/AutocompleteLocations/index.ts
src/components/AutocompleteLocations/utils.ts
src/components/Explore/Explore.tsx
src/components/Explore/LocationSelector.style.ts
src/components/Explore/LocationSelector.tsx
src/components/Explore/utils.ts

This PR implements the location selector for Explore v2
- State pages show only states as options
- County pages show only counties in the current state as options
Note that I'm leaving UI polish ~~and formatting of the location names~~ for later (see [CAN Explore - V2 Compare Locations](https://paper.dropbox.com/doc/CAN-Explore--A63xPTEkOs8MoTLBhyR8l3SoAg-RIlOIJkMWHcX0AmXQA5PW) so I can get a 1st version of the compare functionality working sooner.
**Mobile**
**Desktop**

explore v2: implement location selector

---

src/components/Explore/Explore.tsx

This ensures that the current location is always selected and also avoids having to handle the case where the user just unselects all the locations.

explore v2: ensure that the current location is always selected

---

src/common/models/ICUHeadroom.ts

https://trello.com/c/nvHzgI0r/420-icuutilization-total-beds-disconnect-between-actuals-and-actualstimeseries
Imperial County before (20 beds):
Imperial County after (28 beds):

Only use ICU bed capacity from the timeseries if it's from the last 7 days.

---

src/common/urls.ts
src/components/Compare/CompareMain.tsx

1. Parse query string params and use them as default values for compare table options.
2. Use compare table options to generate a sharing URL and (for now) log it to the console.

Generate sharing URLs for compare pages.

---

src/components/Explore/Explore.tsx
src/components/ShareButtons/ShareButtonGroup.tsx

Disable the sharing buttons when there are multiple locations selected.

explore v2: disable sharing buttons when comparing multiple locations

---

src/common/locations.ts
src/components/AutocompleteLocations/AutocompleteLocations.tsx
src/components/Explore/Explore.style.ts
src/components/Explore/Explore.tsx
src/components/Explore/ExploreChart.tsx
src/components/Explore/LocationSelector.style.ts
src/components/Explore/LocationSelector.tsx
src/components/Explore/MultipleLocationsChart.tsx
src/components/Explore/utils.ts
src/components/LocationPage/ChartsHolder.tsx
src/components/Map/USACountyMap.js

This PR implements normalization of Explore metrics per 100k population.
- Styling the checkbox, labels, spacing, etc.
- Add the normalization control for mobile (see designs in [Figma](https://www.figma.com/file/nkoC6P02eXxkB95ukdU6Ms/Explore?node-id=260%3A747))

explore v2: normalize per 100k population

---

src/screens/LocationPage/LocationPage.js

I'm not 100% sure why the equality didn't work (I also tried lodash equality, which I thought would've fixed it) but I ran into a bug where navigating to a county page after adding it to explore just showed the loading page.  
I think this fix is fine - comparing the fips code should give the result we want, but I'm not super familiar with this code.  let me know if there's a better way to handle this!

Fix error when navigating to county after adding to explore

---

src/components/Compare/LocationTable.tsx

- Fixes bug that was causing some county-rows to appear 3x in modal (image # 1)
- Edits modal locations to exclude inline current-county-row if current county is ranked # 1 (causing consecutive repeating rows in image # 2)

Compare modal bug fix

---

src/components/Charts/utils.ts

Addressing the y-axis issue: https://trello.com/c/82IW2Lvm/323-poor-y-axis-range-when-graph-barely-enters-critical-range
If the highest y coordinate of the dataset surpassed upper limit (in this case 20%) of the High level, the maxTick would be set to that Y, rather than 1.5 x the upper limit.  This is why maxTick went from 35% to 21% as soon as the data passed 20%.

Improve computation of maxTick

---

firebase/firestore.rules
scripts/generate_index_pages.ts
src/App.js
src/common/urls.ts
src/components/Compare/CompareMain.tsx
src/components/Compare/CompareTable.tsx
src/components/Compare/LocationTable.tsx
src/components/Compare/ModalCompare.tsx
src/components/HandleRedirectTo/HandleRedirectTo.tsx
src/components/LocationPage/ChartsHolder.tsx
src/components/ShareButtons/ShareButtonGroup.tsx
src/screens/HomePage/HomePage.js
src/screens/internal/ShareImage/CompareTableImage.tsx
src/screens/internal/ShareImage/ShareImage.tsx

This moves us away from using query params for compare sharing and instead uses Firestore to store your compare parameters when you share the table, so we can create predictable URLs.  This is necessary so we can pre-generate index.html pages that have meta tags that point to the corresponding share image URL.
One consequence of this change is we don't generate the share URL until the user clicks on the share / save buttons, so I had to rework ShareButtonGroup so you don't necessarily need to know the URLs up front but can instead pass in functions that generate a URL (asynchronously) and then return it.  The code's a bit more complicated and now there's a small delay when you click the share button. 😢  I may see if I can improve that by showing the buttons even before we have the right …

Use Firestore to store share parameters so we can create predictable URLs.

---

src/components/Explore/Explore.tsx

When the component loads, there is only a single location and the data is not normalized.
When a 2nd location is selected, normalization is automatically enabled.
When the 2nd location is removed, normalization is disabled.
Fixes issue #1471

default to not-normalized

---

scripts/alert_emails/template.html

Added the alt text for the only image that didn't have one in the alert email template.

accessibility: alt text for the can logo on the alert email template

---

src/components/Footer/Footer.style.tsx
src/components/Footer/Footer.tsx
src/components/Footer/FooterSocialLinks.js
src/components/LogoGrid/LogoGrid.tsx
src/components/Map/USACountyMap.js

Small accessibility fixes. This brings our accessibility score for the home page from 69 to 84, although I couldn't notice a difference when using the default Mac screen reader 🤷‍♂️ 
- Update the links in the footer to use links instead of span elements with an `onClick` handler
- Add the `aria-label` attribute to social links (they don't contain any text, just the social media logo)
- Add `alt` text to the homepage logos
- Add the `title` and `aria-label`s to the links for state shapes, and set the role of the shapes to `img` (they had an invalid role before)
- https://web.dev/image-alt
- https://web.dev/aria-roles
- https://web.dev/link-name
- https://www.deque.com/blog/text-links-practices-screen-readers/

accessibility: misc fixes

---

src/components/Explore/Explore.tsx
src/components/Explore/MultipleLocationsChart.tsx
src/components/Explore/SingleLocationChart.tsx
src/components/Explore/utils.ts

- Remove "since March 1st" from the copy (From [Paper - CAN Explore](https://paper.dropbox.com/doc/CAN-Explore--A7ptCAakhRbthPiIlcrVsbKbAg-RIlOIJkMWHcX0AmXQA5PW))
- Change Trends → Raw Data [Slack thread](https://covidactnow.slack.com/archives/C018XQHEB1A/p1599778034007500)
- Change Hospitalizations and ICU Hospitalizations → COVID Hospitalizations and COVID ICU Hospitalizations (copy and tooltip). [Slack thread](https://covidactnow.slack.com/archives/C0110QQAPJA/p1600189192003700)

explore: copy updates

---

src/components/Explore/Explore.tsx
src/components/Explore/LocationSelector.tsx
src/components/Explore/utils.ts
src/components/LocationPage/ChartsHolder.tsx

This PR enables comparing states and counties from any location page (state or county). 
I'm not sure about the ordering of the options is [components/Explore/utils.ts#123](https://github.com/covid-projections/covid-projections/pull/1489/files#diff-dd7f086fa1c0daa9a9fbd34229f306e4R384-R386). That order shows the most relevant locations first, but showing states in the county page, or counties in the state page might make the change more discoverable. Thoughts?

explore: enable comparing with states and counties

---

src/components/LocationPage/ChartBlock.tsx
src/components/LocationPage/ChartsHolder.tsx
src/components/LocationPage/LocationPageHeader.tsx
src/components/SummaryStats/LocationHeaderStats.tsx

There were a few places where we repeated very similar code 5 times, once for each metric, and I simplified it to just map over ALL_METRICS.

Reduce metric-related code duplication in ChartsHolder, LocationPageHeader, and LocationHeaderStats

---

cypress/integration/ModelPage_spec.js
src/screens/HomePage/HomePage.js
src/screens/LocationPage/LocationPage.js
src/screens/LocationPage/index.ts
src/screens/LocationPage/utils.ts

This PR updates the title and description metatag for the home page and location pages to increase our search rankings. 
Gaia's analysis reveals that people search using the county name and state name and/or state code. People in some states tend to use the state code, while others use the full name. Adding this information on the title and description of the page helps our page rank higher when people search for it.
Check the [Growth Analytics Roadmap](https://docs.google.com/document/d/110tRmOW-Y_BcmYF0OcxVjV5-lDf0RTkqfRx1oWdyK6o/edit#) document for the proposed changes.

analytics: update pages title and description

---

src/components/Explore/Explore.tsx
src/components/Explore/MultipleLocationsChart.tsx
src/components/Explore/interfaces.ts
src/components/Explore/utils.ts

This PR optimizes the labels for the explore chart when there are multiple locations selected. There are 3 main cases:
- Desktop: We show the full name, hoping that it will fit (it will overflow if not)
- Mobile (states only): We show only the state code, so we need a narrow right margin
- Mobile (with counties): We show a cropped version of the county name and expand the margin so it will fit.
**Desktop**
**Mobile (states only)**
**Mobile (states + county)**

explore: optimize margin size

---

firebase/firestore.rules
package.json
scripts/generate_index_pages.ts
src/App.js
src/common/locations.ts
src/common/sharing.ts
src/common/urls.ts
src/common/utils/model.ts
src/components/Compare/CompareMain.tsx
src/components/Explore/Explore.tsx
src/components/Explore/MultipleLocationsChart.tsx
src/components/Explore/SingleLocationChart.tsx
src/components/Explore/utils.ts
src/components/LocationPage/ChartsHolder.tsx
src/screens/internal/ShareImage/ChartExportImage.style.ts
src/screens/internal/ShareImage/ChartShareImage.style.ts
src/screens/internal/ShareImage/ExploreChartExportImage.tsx
src/screens/internal/ShareImage/ExploreChartImage.tsx
src/screens/internal/ShareImage/ShareImage.tsx

FYI- This is split into two commits.  
1. A refactor / reimplementation of compare sharing to make it more general-purpose. The second one uses that infrastructure to implement explore sharing. It mostly has no functional changes though it does point at /share/xyz/ URLs instead of /compare/XYZ URLs which lets us unify the index.html pages we generate to just /share/xyz for compare, explore, and any future components that implement sharing.
2. Actual sharing implementation for the explore component (based on above refactor).
NOTE: Preexisting shared explore URLs should continue to work, but going forward instead of a URL like /us/wa/explore/cases it'll end up being /share/123?redierctTo=/us/wa/explore/123.
With this PR, the following should work:
1. You make an arbitrary explore chart and …

Rework compare sharing and implement explore sharing.

---

firebase/firestore.rules
package.json
scripts/generate_index_pages.ts
src/App.js
src/common/locations.ts
src/common/sharing.ts
src/common/urls.ts
src/common/utils/model.ts
src/components/Compare/CompareMain.tsx
src/components/Explore/Explore.tsx
src/components/Explore/MultipleLocationsChart.tsx
src/components/Explore/SingleLocationChart.tsx
src/components/Explore/utils.ts
src/components/LocationPage/ChartsHolder.tsx
src/screens/internal/ShareImage/ChartExportImage.style.ts
src/screens/internal/ShareImage/ChartShareImage.style.ts
src/screens/internal/ShareImage/ExploreChartExportImage.tsx
src/screens/internal/ShareImage/ExploreChartImage.tsx
src/screens/internal/ShareImage/ShareImage.tsx

Rework compare sharing to be more generic (reusable for explore).
* Create common helpers for storing / fetching component params to/from Firestore.
* Change shared URLs to /share/xxx since we can redirect to the right URL
anyway, and this lets us just generate /share/xxx/index.html pages.
Implement (multi-location) Explore Sharing (moves existing sharing to new 'shared component' infrastructure).

Deploy explore sharing (#1517)

---

public/index.html

Add og:image:{width,height} tags to hopefully help Facebook render previews.
I noticed the [docs](https://developers.facebook.com/docs/sharing/webmasters/images/) say:
> Use og:image:width and og:image:height Open Graph tags: Using these tags will specify the image dimensions to the crawler so that it can render the image immediately without having to asynchronously download and process it.

Specify image sizes so maybe Facebook will render a preview?

---

scripts/alert_emails/send_emails.ts

Temporarily hack email sending script to only send 50 batches (500 emails) to make sure AWS is behaving well.

Only send first 500 emails.

---

src/components/Analytics/PageviewTracker.tsx

Discussed with Gaia - we are going to use Title Case for events from now on, it will help us to tell apart "old" events from the current implementation.

analytics: set title case for events

---

package.json
src/index.js
yarn.lock

Thought it might be worthwhile to add in sentry alerting for the website, since I don't think we have much visibility into any problems that might arise.  
This is the most basic setup - ideally we would also upload sourcemaps during builds to make the errors easy to trace, but that doesn't have to happen right away.  I'm more curious if there are currently a lot of edge cases that are bad experiences for a certain subset of users

Add basic sentry config

---

src/common/metrics/case_density.tsx

https://trello.com/c/d08xcPc3/389-dont-round-cases-day-in-explanatory-text-to-0
Avoid rounding down to zero, leading to confusing explanatory text, e.g.:

Don't round cases/day to zero in explanatory text.

---

src/screens/Resources/Resources.tsx

We don't have the CSV files on the resources page, removing the link for now.

resources: remove broken link to CSV files

---

src/cms-content/recommendations/index.ts

The export was incorrect, it was aliasing the variables instead of casting the type

recommend: fix cms exports

---

src/App.js
src/common/locations.ts
src/components/Explore/Explore.tsx
src/components/Explore/utils.ts

Fixes some issues when sharing the Explore chart from the homepage.
- When the user copies the link, the copied link will redirect the user to either the location or the home page, depending on the original location of the user. The link correctly updates the Explore chart and scrolls to the corresponding location on the page.
- When the user saves an image, the image filename will include the names of the locations currently selected, not the initial location (up to 2 locations, beyond that it will be named `multiple-locations-{METRIC}-{YYYY-MM-DD}.png`)

explore: fix homepage sharing url and image name

---

src/cms-content/recommendations/recommendations-main.json
src/cms-content/recommendations/recommendations-modal.json
src/common/utils/recommend.ts
src/components/Button/Button.style.ts
src/components/Recommend/Recommend.tsx
src/components/Recommend/RecommendModal.style.ts
src/components/Recommend/RecommendModal.tsx
src/components/Recommend/RecommendTabs.tsx

Edits in this PR from slack feedback:
- Fixes intro copy punctuation and changes language to what was suggested by Tom
- Changed LinkButton's hover state (underline instead of gray background)
- Sets fixed height on level description containers within modal
- Opens modal links in new tab
To-do:

Recommend: misc edits

---

src/components/Markdown/Markdown.style.ts
src/components/Markdown/MarkdownContent.tsx
src/components/Markdown/index.ts
src/components/Recommend/RecommendModal.style.ts

This attaches `rel="noopener noreferrer"` to links in markdown content

recommend: use a custom link for markdown content

---

src/common/models/Projection.ts
src/components/LocationPage/LocationPageHeader.tsx

@ghop02 Can you merge this after merging the new snapshot, before merging to master?

Add HHS data announcement and reenable ND test positivity.

---

src/components/Analytics/PageviewTracker.tsx
src/components/Banner/Banner.tsx
src/components/Banner/DonationBanner.tsx
src/screens/HomePage/HomePage.js

I added a plugin to track attribution. Ideally, it should be able to tell us which link started the navigation to an internal page when we have more than one link towards a page (for donation, for example). I'm still investigating how to access this in GA.

restore the donation banner

---

src/index.js

Disabling sentry until we fix some of the more common sentry errors.  (we're hitting our quota and unable to receive new events)

Disable sentry

---

src/components/Explore/SeriesChart.tsx

[Trello card](https://trello.com/c/ReNU4QcC/521-removing-overshoot-artifact-from-explore-moving-averages) - This PR replaces the interpolation method used for the Explore charts to avoid artifacts. The new interpolation is [d3-shape#curveMonotoneX](https://github.com/d3/d3-shape#curveMonotoneX)
> “a smooth curve with continuous first-order derivatives that passes through any given set of data points without spurious oscillations. Local extrema can occur only at grid points where they are given by the data, but not in between two adjacent grid points.”
_Before_
_After_

explore: update the interpolation method for line series

---

src/components/Explore/Explore.style.ts
src/components/Explore/Explore.tsx

The chart container for the Explore chart was adding negative margins to counteract the margins of the main container on each page. The negative margins were bigger than the main container margins, making the chart container to be wider than the viewport.
This PR uses the same margin as the main container, ensuring that the Home Page won't show the horizontal scrolling control. I also changed the number of characters to use the "narrow" margin to 4, to accommodate for the Native American abbreviation "NAMC" to be shown with narrow margins (more space for the chart)

homepage: adjusts the margins of the explore chart

---

src/components/Compare/CompareTable.tsx
src/components/Explore/Explore.tsx
src/components/ShareButtons/FacebookShareButton.tsx
src/components/ShareButtons/LinkedinShareButton.tsx
src/components/ShareButtons/ShareButtonGroup.tsx
src/components/ShareButtons/ShareButtons.style.tsx
src/components/ShareButtons/TwitterShareButton.tsx

Adding tracking for when users click "share" on Facebook, Twitter, and Linkedin for Compare and Explore. The metric charts use an old component and need to migrate that first.

analytics: tracking social sharing for explore and compare

---

src/components/AppBar/NavBar.style.ts

I attached an invalid prop for the IconButton component (this only throws a warning in development). https://material-ui.com/api/icon-button/

remove invalid prop for IconButton

---

src/components/SmallShareButtons/SmallShareButtons.tsx

It adds a Snackbar when users copy the link on Recommendations. The alert dismisses in 2 seconds.

add feedback for when copying a link for recommend

---

src/common/utils/recommend.ts

Fed task force's yellow zone is defined as:
```
Both:
- New cases between 10-100 per 100,000 population
- Diagnostic test positivity result between 5-10%
Or one of those two conditions and one condition qualifying as being in the “Red Zone”.
```
We weren't calculating this correctly:
- We were calculating the first half with `||` instead of `&&`
- We weren't capturing the second half/the 'Or...'
For reference (from the fed doc):
To test:
Vermont, Maine = Fed green zone
Minnesota, Oregon = Fed yellow zone
South Dakota, Utah = Fed red zone

Recommends: fix yellow

---

src/components/Markdown/MarkdownContent.tsx
src/components/Markdown/MarkdownLink.tsx
src/components/SharedComponents/Accordion.tsx
src/screens/Learn/Glossary/Glossary.tsx

The markdown component has a custom renderer for links. This PR differentiates internal and external links by parsing the `href` parameter as a [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL) and checking if the link includes a hostname.
Internal links use the `HashLink` component, which scrolls to the specific link (let's say `/glossary#superspreader`, external links will open on a new tab (and have `rel="noopened noreferrer"`)

handle internal and external links on markdown content

---

src/components/ErrorBoundary/ErrorBoundary.tsx
src/components/ErrorBoundary/FallbackAlert.tsx
src/components/ErrorBoundary/index.ts
src/components/Markdown/MarkdownContent.tsx
src/index.js

An error boundary prevents the entire app from crashing when a component crashes. One potential problem with the CMS is that CMS users could put an invalid URL in the link, which would crash the app.
This PR uses the ErrorBoundary component provided by Sentry to wrap the markdown component. If the markdown component crashes for any reason, the error boundary will capture the error and render the fallback UI. It will also send the error report to Sentry
In local development, errors are shown with an overlay by Create React App, which hides the Error boundary. To test the error boundary, we need to use the production build
- Throw an error from the Markdown component (add `new URL('~~~')` somewhere in the component)
- Build the app locally (`yarn build`)
- Run the server using the build …

implement error boundary

---

src/components/Footer/Footer.tsx

This PR adds a link to the Learn page on the footer, and re-arranges the items to match the top navigation bar.

learn: add learn on the footer

---

src/components/Charts/ChartCaseDensity.tsx

Update the cap on the daily new cases chart. I moved the cap to 500 to account for counties in North Dakota that are unfortunately over 250 / 100k.
See [Wells County, ND](https://covid-projections-git-pablo-update-case-density-cap.covidactnow.vercel.app/us/north_dakota-nd/county/wells_county?s=1231303) for an example

update the cap for the case incidence chart

---

src/components/Markdown/Markdown.style.ts
src/components/Markdown/MarkdownContent.tsx
src/components/Markdown/index.ts
src/screens/Learn/CaseStudies/CaseStudiesLanding.tsx
src/screens/Learn/CaseStudies/CaseStudy.style.ts
src/screens/Learn/CaseStudies/CaseStudy.tsx
src/screens/Learn/CaseStudies/CaseStudyCard.style.ts
src/screens/Learn/CaseStudies/CaseStudyCard.tsx
src/screens/Learn/Faq/Faq.tsx
src/screens/Learn/Faq/Section.tsx
src/screens/Learn/Glossary/Glossary.tsx
src/screens/Learn/Landing/Landing.tsx
src/screens/Learn/Landing/SectionButton.style.tsx
src/screens/Learn/Learn.style.tsx

This PR updates and centralize the styles for Learn pages, mostly on typography and spacing around elements.
On Learn pages, we have paragraphs and headings both inside and outside markdown blocks. We need headings and spacing to be consistent in both cases. For example, the [Case Studies landing page](https://covid-projections-git-pablo-case-studies-ux-feedback.covidactnow.vercel.app/case-studies) uses `h2` elements for category names, but in the [California Department of Public Health](https://covid-projections-git-pablo-case-studies-ux-feedback.covidactnow.vercel.app/case-studies/cdph-calcat) case study, the `h2` level is part of the markdown content added via the CMS.
One solution to keep both consistent is to export the headings from the `Markdown` component and use them directly in …

case studies: ux feedback

---

src/api/schema/Actuals.d.ts
src/api/schema/ActualsTimeseriesRow.d.ts
src/api/schema/AggregateFlattenedTimeseries.d.ts
src/api/schema/AggregateRegionSummary.d.ts
src/api/schema/AggregateRegionSummaryWithTimeseries.d.ts
src/api/schema/Metrics.d.ts
src/api/schema/MetricsTimeseriesRow.d.ts
src/api/schema/RegionSummary.d.ts
src/api/schema/RegionSummaryWithTimeseries.d.ts
src/common/metric.tsx
src/common/metrics/interfaces.ts
src/common/metrics/positive_rate.tsx
src/common/models/Projection.ts
src/components/Disclaimer/Disclaimer.tsx
src/components/LocationPage/ChartBlock.tsx
src/components/LocationPage/LocationPageHeader.tsx

This has no effect until we switch to a snapshot that uses CMS data.  So I created a separate branch with that preview.  See e.g. https://covid-projections-git-mikelehen-use-cms-demo.covidactnow.vercel.app/us/in/county/fayette_county?s=1231303
Update copy:
Disclaimer copy:

Add CMS-specific update and disclaimer copy.

---

src/components/StateSvg/NorthernMarianaIslands.js

Fixes the names of the props for the SVG of Mariana Islands (react doesn't like the dashes in multi-word properties, unless it's for aria labels or data attributes)

fix Mariana Islands svg props

---

src/components/SignalStatus/SignalStatus.style.tsx

[Trello](https://trello.com/c/4LNZymF4/555-embed-icon-for-daily-new-cases-is-smaller-than-the-rest) - This PR adjusts the space shared by the warning icon and the word "Critical" to make sure that they fit in the embed. 
- [Standalone](https://covid-projections-git-pablo-fix-embed-icon.covidactnow.vercel.app/embed/us/indiana-in)
- [Location Page](https://covid-projections-git-pablo-fix-embed-icon.covidactnow.vercel.app/us/indiana-in)
Before
After

fix the size of the status labels on embed

---

src/components/AutocompleteLocations/AutocompleteLocations.tsx
src/components/Explore/utils.ts

[Trello](https://trello.com/c/fKbc9J9l/543-explore-search-has-sorting-quirks-for-states-and-especially-counties) - Explore search has sorting quirks for states and especially counties
This PR fixes the quirks, in particular:
- Sort the locations alphabetically, preserving the order of each group (i.e., aggregated, states, state counties, other counties),  (`Alabama` shows before `Alaska`)
- Only match strings from the start of the string (`king` will match `Kings County, TX` and `Kingfisher County, OR` but not `Hocking County, OH`)
The filter options are not super well documented, but the source code is fairly straightforward, see [material-ui/src/useAutocomplete/useAutocomplete.js](https://github.com/mui-org/material-ui/blob/4d50a9ed6a7c2007b9e5061d0842f38df191cfb2/packages/material-ui/sr …

fix some explore search quirks

---

src/components/Charts/Axis.tsx

This PR adjusts the separation between the ticks on the x-axis for metric charts. It's just a stop gap while I work on a more definitive solution.

adjust ticks on metric charts

---

public/index.html

[Trello Card](https://trello.com/c/hVhZfGvt/591-add-google-ads-tags-to-the-website) - Add Google Ads tracking to the website
I thought that this script was already included when initializing Google Analytics in [PageviewTracker.tsx](https://github.com/covid-projections/covid-projections/blob/develop/src/components/Analytics/PageviewTracker.tsx), but I inspected the network requests and it seems that is not the case. 🤷‍♂️

add google ads tracking

---

.github/workflows/ci.yml

MY [PR](https://github.com/covid-projections/covid-projections/pull/1912/checks?check_run_id=1409629678) failed with:
Looks like github made a [breaking change](https://github.blog/changelog/2020-11-09-github-actions-removing-set-env-and-add-path-commands-on-november-16/).
This seems to fix it!

Use latest setup-node action to fix broken CI.

---

src/common/metric.tsx
src/common/metrics/case_density.tsx
src/common/metrics/case_growth.tsx
src/common/metrics/contact_tracing.tsx
src/common/metrics/hospitalizations.tsx
src/common/metrics/interfaces.ts
src/common/metrics/positive_rate.tsx
src/components/Thermometer/Thermometer.style.ts
src/components/Thermometer/Thermometer.tsx
src/components/Thermometer/index.ts
src/screens/Contact/Contact.tsx

Implement the thermometer component for the metric explainers. See [Figma](https://www.figma.com/file/ak4c25AkVqwVcg2GzjQ3JB/CMS-(Learn%2C-products%2C-about%2C-contact)?node-id=565%3A5215).
Since we need one per metric, I added the `renderThermometer` function to the `MetricDefinition` interface for each metric. The content of the function is a bit repetitive, but that allows handling the differences between the metrics without much hassle
- Contract tracing doesn't have a Low level
- Number formatting for the limits between each level don't match exactly the number formatting function for the metric (we need fewer decimal points)
- The grey box is exported as a separate component to make the thermometer component more reusable and less context-dependent.
- This component is not rendered …

explainers: thermometer component

---

scripts/alert_emails/utils.ts

While testing the new thermometer images, I noticed that our alt text was non-ideal.
*Before:* Image depicting that District of Columbia went from level HIGH to SUPER_CRITICAL
*After:* Image depicting that District of Columbia went from "At risk of outbreak" to "Severe outbreak"

Use summary text instead of enum name in alert email alt text.

---

src/components/Compare/Filters.tsx
src/components/SharedComponents/SwitchComponent.stories.mdx
src/components/SharedComponents/SwitchComponent.style.tsx
src/components/SharedComponents/SwitchComponent.tsx
src/screens/HomePage/HomePage.js

SwitchComponent had two separate callbacks (onChange and onGridClick) and we were only tracking analytics events when you hit the onChange handler (concretely, if you hit the actual switch GUI then `onChange` would fire and we'd track it; but if you clicked on the "States" or "Counties" labels, then `onGridClick` would fire instead and we wouldn't track it). 
I reworked it to only have a single event callback and also added it to storybook and did some minor cleanup.

Fix inconsistent tracking of switch component clicks due to extra event callback.

---

src/common/models/Projection.ts

https://trello.com/c/fjjyfcKG/629-new-york-ny-test-positivity-data

Mask NYC Boroughs Test Positivity

---

firebase/functions/src/dynamic_web_content.ts
public/index.html
scripts/generate_index_pages.ts
src/common/urls.ts
src/components/AppMetaTags/AppMetaTags.js
src/components/SocialLocationPreview/SocialLocationPreview.tsx
src/screens/internal/ShareImage/ChartShareImage.tsx
src/screens/internal/ShareImage/ExploreChartImage.tsx
src/screens/internal/ShareImage/ShareCardImage.tsx
src/screens/internal/ShareImage/ShareImage.style.ts
src/screens/internal/ShareImage/ShareImage.tsx
src/screens/internal/ShareImage/USMapImage.style.ts
src/screens/internal/ShareImage/USMapImage.tsx

https://trello.com/c/4d3VBDOm/598-update-covidactnoworg-snapshot
1. Create a new map image for SEO (separate from the homepage share image) that doesn't have the big black background and header, etc.
1. Revert the homepage share URL back to 'home.png' (instead of [date]-image-covid-us-map-cases.png)
1. Point [date]-image-covid-us-map-cases.png at the new map image and insert it into our `<meta name="image">` tag on the homepage.
The image is generated from https://covid-projections-git-mikelehen-map-seo.covidactnow.now.sh/internal/share-image/map/
The image isn't really great, but hopefully it's good enough for now.  It might also be nice if we had a dedicated URL for the county-colored homepage (https://covidactnow.org/us-county/ or whatever) and generated the appropriate county-colored …

SEO: Add a new map image to link to from our 'image' meta tag.

---

src/components/Dialog/Dialog.style.ts

A recent edit threw off the dialog spacing:

Dialog fix

---

src/screens/About/Team/ActiveMember.tsx
src/screens/About/Team/Team.style.tsx

- center-align profile picture and name for team members without a title or description
- add alt-text for profile pictures

fix vertical alignment of the team member description

---

public/admin/config.yml
src/cms-content/learn/index.ts

- Adds config + types for metric explainers
- Removes config + types for product pages (section nix'ed, no longer needed)

Metric explainers CMS config

---

src/components/Banner/Banner.style.ts
src/components/Banner/Banner.tsx
src/components/MapSelectors/GlobalSelector.style.js

[Trello](https://trello.com/c/Kpu34lhS/603-horizontal-scrollbar-on-iphone-after-using-search-box) - Horizontal scrollbar on iPhone after using search box
This is a bug in Safari, if the font size on an input element is smaller than 16px, Safari will zoom in when the user focus the input element, but it won't zoom out once the user leaves the input area. The font size of our search input element is 14px 
The best fix I could find is to increase the font-size to 16px (1rem) and scale the input element so the text _looks_ 14px, so by a factor of (14 / 16 = 0.875). I adjusted the spacing around too so it matches (and remove the border radius, which is not necessary since borders are not visible).
- Open the page with Safari on iPhone
- Click on the search box, the browser should not zoom-in
- …

Fix horizontal scrollbar on iPhone

---

public/admin/config.yml
src/cms-content/learn/index.ts
src/cms-content/learn/learn-faq.json
src/cms-content/learn/learn-glossary.json
src/common/utils/index.ts
src/screens/Learn/Faq/Faq.tsx
src/screens/Learn/Glossary/Glossary.tsx
src/screens/Learn/Learn.style.tsx

- The timestamps are fields in the glossary+FAQ's CMS UIs
- Whoever deploys cms changes for either of those pages needs to be sure to update the respective timestamp to `now` before shipping

Adds timestamp to glossary+FAQ

---

src/common/regions.test.ts
src/common/regions.ts
src/components/LocationPage/ChartsHolder.tsx
src/components/LocationPage/LocationPageHeader.tsx
src/components/LocationPage/LocationPageHeading.tsx
src/screens/LocationPage/LocationRouter.tsx

This PR builds on top of  #2043 and uses the proposed region context to get location information from within location pages. It doesn't migrate all the instances yet.
- Adds the methods `findCountyByUrlParams` and `findStateByUrlParams` to `RegionDB` (and corresponding test cases)
- Implements `RegionContext` and `useRegion` to allow accessing the `region` object from anywhere under a location page.
When creating the `RegionContext`, I passed a stand-in region as default value. This allows TypeScript to understand that `useRegion` will always return an instance of `Region` (otherwise we will have to null-check everywhere). Open to suggestions!

Region API: Use region context to access location properties

---

src/components/AutocompleteLocations/AutocompleteRegions.stories.tsx
src/components/AutocompleteLocations/AutocompleteRegions.tsx

Similar to `AutocompleteLocations`, but for regions. I want to update the email alert form to use this component, but will do that on a separate PR.
I added the `ariaLabelledBy` prop so we can label the input correctly

implement autocomplete regions component

---

src/common/regions/region_db.ts
src/common/regions/regions.test.ts

Queries to regions from either fips codes or regions were returning the rest of the nyc counties.  we just want to return a single nyc county for all nyc boroughs

Return NYC from regions database

---

src/common/urls.ts
src/components/LocationPage/ChartsHolder.tsx

This updates a handful of url functions to use region.  one thing to think about is we might want to use `window.location.origin` in `canonicalUrl` so that all the links point to links specific to the domain we're on.
A couple functions didn't have any callers with county and state, so I just removed those arguments in favor of cutting code, can re add if we think we'll use those in the future.

Updating urls to use region where possible

---

src/common/regions/types.ts
src/screens/internal/CompareSnapshots/CompareSnapshots.tsx

Also add a toString() method for better handling in log messages, etc.:
Before:
> Error: INTERNAL ASSERTION FAILED: Failed to fetch projections for [object Object]
After:
> Error: INTERNAL ASSERTION FAILED: Failed to fetch projections for Kalawao County (fips=15005)

Fix compare handling missing counties.

---

src/components/LocationPage/HospitalizationsAlert.tsx
src/components/LocationPage/LocationPageHeader.tsx
src/components/Recommend/Recommend.style.tsx

[Trello item](https://trello.com/c/4EzIOrR6/606-reconsider-county-data-is-still-in-beta-our-forecasts-may-not-be-as-accurate-copy)

Removes "county data is still in beta" copy

---

src/components/LocationPage/LocationPageHeader.style.tsx
src/components/LocationPage/LocationPageHeader.tsx
src/components/LocationPage/LocationPageHeading.style.ts
src/components/LocationPage/LocationPageHeading.tsx

Update the `LocationPageHeading` component to support MSAs. I'm not adding a link on the state codes because some MSAs go to more than one state.
I tested this on the `pablo/region-page-draft` branch, but didn't commit the changes there because this can be merged to `develop`.

update location header to support MSAs

---

src/common/regions/regions_data.ts
src/components/Compare/CompareMain.tsx

DC currently has both a state page and a county page (noticed via DC state page's compare table, which was showing the non-matching county page's data - screenshot below). This PR filters out DC county when building regions in `regions_data.ts`.
[Trello item](https://trello.com/c/tIqXApGD/667-dc-has-two-location-pages-state-and-county-with-different-data)

Filters out DC county

---

scripts/generate_index_pages.ts

The script was silently failing during deploys due to trying to read CBSA fips codes from county API endpoints.
> Error: INTERNAL ASSERTION FAILED: Failed to find county 10180
This is a minimal fix to only read counties and to and makes sure that the script doesn't silently fail in the future.

Fix index page generation.

---

src/common/utils/model.ts

The job [update-data-snapshot](https://github.com/covid-projections/covid-projections/runs/1560828963?check_suite_focus=true#step:10:24) failed because because the API returns the projections for the county with FIPS `11001` (District of Columbia), but we don't have it in `regions` as a county (we have it as a state, with FIPS code "11").
This PR filters out the county projections that don't have a county.

fix: filter out county projections if the county is not in the regions instance

---

src/components/CountyMap/CountyMap.js
src/components/Header/SearchHeader.tsx
src/components/Map/Map.js
src/components/MiniMap/MiniMap.tsx
src/components/SocialLocationPreview/SocialLocationPreview.tsx
src/screens/LocationPage/LocationPage.tsx

This removes most of the logic in the `goToStatePage` click handler when navigating to a state from the map.  It was causing some weirdness in the history by including an old url.  
Now that we are using links in the map, we don't need to control as much state from places that we click.  For instance, in this PR I move the logic to close the mobile map to simply change when the region changes on a location page.

Remove additional push to history on click of state from state map

---

public/scripts/embed.js
src/App.js
src/common/regions/region_hooks.ts
src/common/utils/hooks.tsx
src/components/AppBar/NavBar.tsx
src/components/AppBar/SocialIcons.tsx
src/components/Footer/Footer.tsx
src/components/LocationPage/LocationPageHeader.tsx
src/components/ShareBlock/EmbedPreview.tsx
src/components/ShareBlock/ShareModelBlock.tsx

Separates out the `isEmbed` logic into it's own hook as it's a pretty different use case, and this felt more clean to separate the `useEmbed` to rely solely on the region passed into it rather than url params.
Also modified the embed so that all embed requests hit `/embed/fips/<fipsCode` instead of having separate sections for state and county.  This will let it work seamlessly with Metros.  As a result, I had to change the public Embed script to handle the old version of the embed (with state code + optionally fips) set and the new version (with just fips).
I don't have a ton of experience with the embeds so i might be missing something, but it seems to work on my tests!

Embed with regions

---

scripts/update_location_summaries.ts

Minor change on `update_location_summaries` to use `regions` instead of functions from `common/locations`

remove references to locations on update-location-summaries

---

src/common/regions/types.ts
src/components/LocationPage/LocationPageHeader.tsx
src/components/LocationPage/LocationPageHeading.style.ts
src/components/LocationPage/LocationPageHeading.tsx
src/components/MiniMap/MiniMap.tsx

This is the beginning of changing the MSA name to include "metro area".  
There are still some unresolved issues.  One issue is that we use `region.name` throughout the code and I'm not 100% clear what it refers to, but it'll pop up as the uglier version of the Metro name.

First attempt at changing MSA name

---

src/components/SummaryStats/SummaryStats.tsx

The embed preview has some layout issues, but I'm not fixing those here. The metric name on the header has "per 100k" on a different element, so I'm using the function that returns the names for compare.

fix metric name on embed

---

src/screens/AlertUnsubscribe/AlertUnsubscribe.tsx

Updates the `AlertUnsubscribe` component to work with regions (it's broken in the feature branch) to use regions instead of locations.
- Go to `http://localhost:3000/alert_unsubscribe?email=pnavarrc@gmail.com` (the component doesn't work without the `email` param)
- You should see your alert subscriptions
- Remove some locations, unsubscribe

update unsubscribe page to work with regions

---

src/components/Compare/CompareMain.tsx
src/components/Compare/CompareTable.tsx
src/components/Compare/Filters.tsx
src/components/Compare/LocationTable.tsx
src/components/Compare/ModalCompare.tsx

`viewAllCounties` and `setViewAllCounties` controlled the state<->county switch that is no longer used (replaced by state/city/county slider)

Remove unused state+setState variables

---

src/components/Search/MenuItem.tsx
src/components/Search/MenuItemIcon.tsx
src/components/Search/MetroItemIcon.tsx
src/components/StateSvg/Circle.style.ts

Based on the [mocks](https://www.figma.com/file/NMKWJ9RU3SxSPZcF1w5VCT/MSA-County-Bundling?node-id=108%3A1475). Using the icon from Material UI that looks closer to the one in the mocks.

add search icons for MSA items

---

src/components/LocationPage/LocationPageHeading.tsx

There was an extra `/us` in the stateCode redirect on county pages

Location page header redirect fix 

---

src/common/urls.ts
src/components/Compare/CompareTable.tsx

Share links from compare on MSA location pages were redirecting to the homepage because `getComparePageUrl` didn't use regions/didn't account for metros. This fixes that

Compare sharing fix pt. 1

---

src/common/regions/utils.ts

Proposal to match closer to the behavior we have on production - just sorts the counties in a state from largest to smallest when you're on a state, county or metro page

change sort order to be by county population on location pages

---

src/common/urls.ts

[Trello item](https://trello.com/c/TmSN71uU/706-compare-sharing-doesnt-link-properly)

Compare share url fix

---

src/components/Compare/CompareMain.tsx

Adds check for `locations`
Quick fix for [this trello item](https://trello.com/c/ZbTTsIiD/710-investigate-compare-sentry-error)

Compare edit

---

.github/workflows/alert-email-report-prod.yml
scripts/alert_emails/firestore.ts
scripts/alert_emails_report/generate-report.ts

I haven't hooked up AWS engagement stats, but we at least get the location stats and the (new) "subscribers by date" stats.
Context: Gaia had asked for a graph of subscribers over time.

Reenable email alerts report and add subscriptions by date.

---

src/App.js

The redirect for `/state/:stateId` and `/state/:stateId/county/:countyId` was not implemented correctly (apparently, the children component of a route doesn't have access to the URL parameters). 
This PR fixes that by using `from` and `to` in the `Redirect` component, and updates the syntax other instances of nested redirects for consistency.

fix redirect for deprecated location routes

---

src/common/models/Projection.ts

Follow up to https://trello.com/c/wW18WA48/660-virginia-test-positivity-incorrect-at-0-hhs-test-positivity-data-suspect and https://covidactnow.slack.com/archives/C010NN3DF6H/p1609861974134800

re-enable Virginia test positivity

---

src/components/Newsletter/Newsletter.js
src/components/Newsletter/Newsletter.style.tsx

For historical reasons, when somebody signed up for alerts or the newsletter, we were using a Campaign Monitor signup form that would:
1. Always add the user to the "Alert Signups" list in Campaign Monitor.
2. Optionally (depending on whether they checked the newsletter checkbox) add them to the "Full Sign Up List_Scrubbed" list in Campaign Monitor.
But we don't actually use Campaign Monitor at all for alert emails anymore, so we don't need to sign them up to the first list, and it was costing us extra money.
So I've regenerated the form so that it only signs them up for "Full Sign Up List_Scrubbed" and we only actually submit the form if they check the newsletter checkbox.
Since we only *sometimes* submit the Campaign Monitor signup form now, I had to invent a new subscription …

Update alert/newsleter signup to not store alert subscribers in Campaign Monitor.

---

package.json
yarn.lock

Adds the `yarn analyze` script to generate a bundle analysis. 
- Generate the production build of the app 
- Open a visualization of the source maps
Once it finishes, it opens a visualization of the source maps. Note that unmapped / unsourced basically corresponds to JSON and SVG files (we can see this by opening the files directly).
- [CRA · Analyzing the bundle size](https://create-react-app.dev/docs/analyzing-the-bundle-size/)

add a script to analyze the bundle size

---

src/common/regions/index.ts
src/common/regions/regions_data.ts
src/common/utils/compare.ts
src/components/Compare/Compare.style.tsx
src/components/Compare/CompareTableRow.tsx
src/components/Compare/LocationTable.tsx
src/components/Search/MenuItem.tsx

Trello items:
- [Add state codes](https://trello.com/c/1sDb8zix/722-add-state-codes-to-metro-names-in-search-albany-metro-has-3-identical-search-results)
- [Format/style metro names in compare](https://trello.com/c/QsOLuKKO/709-compare-table-metros-name-bolding)

Adds state codes to metro labels in compare + search autocomplete

---

src/components/Search/SearchAutocomplete.tsx

Addresses bug mentioned in [this trello card](https://trello.com/c/PhgcJBxK/723-search-priority-inconsistent-across-pages-align-on-homepage-search-order):
"For example, another question i have is: should searching metro pull up the metros? Also, right now if you search "new york metro area" it actually doesn't show the result (seems like a bug)."
Search was matching against the wrong location name variation. This fixes (now matches against the same name variation used throughout the dropdown menu).

Fixes autocomplete bug

---

src/common/regions/utils.ts

Per [this trello ticket](https://trello.com/c/PhgcJBxK/723-search-priority-inconsistent-across-pages-align-on-homepage-search-order), edits order of autocomplete locations.
Homepage order: all states, all metros, all counties
Location page order: counties in page's state/metro, all states, all metros, counties not in page's state/metro

Update autocomplete locations order

---

src/components/LocationPage/ChartsHolder.style.tsx

Currently Google is picking up "ICU capacity usedBeta".  I'm assuming if we use a `<div>` it'll at least treat beta as a separate word.  But we could also add an explicit space before it or something. 🤷

Use div for beta tag so google (hopefully) indexes it as a separate word.

---

cypress/integration/ModelPage_spec.js
src/cms-content/learn/learn-faq.json
src/cms-content/learn/learn-glossary.json
src/cms-content/learn/learn-landing.json
src/cms-content/learn/metric-explainers.json
src/screens/HomePage/HomePage.js
src/screens/Learn/Articles/ArticlesLanding.tsx
src/screens/LocationPage/utils.ts

- Updates page titles+descriptions to match [trello ticket](https://trello.com/c/hC06LW0n/702-update-homepage-and-location-pages-meta-titles-and-tags-according-to-new-headline)
- Removes hardcoded '- Covid Act Now' from individual page titles because `AppMetaTags` component already appends it

updates titles and descriptions

---

scripts/generate_index_pages.ts

NOTE: We could alternatively call `getFirebase().firestore().terminate()` but that seemed more hacky given the Firestore usage is currently abstracted behind the `getNextSharedComponentId()` call.

Explicitly exit the process when generate-index-pages is done so we don't wait on Firestore connections to shut down.

---

src/common/regions/types.ts

[Trello item](https://trello.com/c/pPCFELxY/725-seo-some-metros-could-be-more-easily-discoverable-with-multiple-names)

Appends 'city' to New York metro principal city

---

scripts/cbsa/parse-metro-areas.ts
src/common/data/msa-data.json

Updates NY metro area's URL segment to include 'city'
[prod ny metro url](https://covidactnow.org/us/metro/new-york-newark-jersey-city_ny-nj-pa/?s=1490446) --> [preview ny metro url](https://covid-projections-git-casulin-city-in-ny-metro-url.covidactnow.vercel.app/us/metro/new-york-city-newark-jersey-city_ny-nj-pa?s=1490446)

New york metro URL segment update

---

public/index.html

Remove an unused script (see https://github.com/covid-projections/covid-projections/issues/70), it was added to autosize an iframe for email signups with Mailjet back in March.

remove iframe-resizer

---

public/index.html

According to [PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fcovidactnow.org&tab=mobile), we need to optimize loading third party code.
Using `async` instead of `defer` because I imagine that the page load event is important to event trackers
- [Loading third-party JavaScript](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/loading-third-party-javascript)

Performance - defer loading and evaluating 3rd party scripts

---

src/screens/LocationPage/LocationPage.tsx
src/screens/LocationPage/utils.ts

The page meta tags don't really depend on the projections, we can calculate them using location summaries, which should be faster.

update page metatags to calculate them with summaries

---

src/common/regions/types.ts

Note: The sitemap library requires relative URLs and a global `hostname` when creating the sitemap, so we have to update the relative URLs instead of updating the `canonicalUrl` method once.

update relative URLs to include '/'

---

scripts/generate_sitemap/utils.ts
src/App.js
src/cms-content/learn/index.ts
src/cms-content/learn/learn-landing.json
src/components/AppBar/NavBar.tsx
src/components/Banner/ThirdWaveBanner.tsx
src/components/IndigenousPopulationsFeature/IndigenousDataCheckbox.tsx
src/components/LocationPage/Notifications.tsx
src/screens/Learn/Articles/Article.tsx
src/screens/Learn/Articles/ArticlesLanding.tsx

Replaces `deep-dives` with `covid-explained`

Updates deep-dives urls, labels, sitemap with CE

---

package.json
public/index.html
src/components/AppBar/DonateButton.style.ts
src/components/AppBar/DonateButton.tsx
src/components/AppBar/NavBar.tsx
src/components/Experiment/Experiment.tsx
src/components/Experiment/Variant.tsx
src/components/Experiment/index.ts
yarn.lock

Adds support for [Google Optimize](https://optimize.google.com/) and add an experiment to test the tool (makes the donate button purple for 50% of people).
Google Optimize provides a UI to define A/B tests and takes care of assigning users (browser sessions) to each variant in the experiment. The process is as follows:
1. Create an experiment in Google Optimize
- name the experiment
- define the variants
- define objective (visits to /donate in this case)  
- copy the experiment ID
2. Implement the variants in the code
3. Once the code with the experiment is deployed, start the experiment
4. Optimize will show results and let us know which version is better
5. Finish the experiment
5. Remove the experiment code and keep the successful version
The code always defaults to version A if the …

implement setup for A/B testing

---

src/components/Compare/LocationTable.tsx
src/components/LocationPage/ChartsHolder.tsx

Fixes [compare bug](https://trello.com/c/pYKWaSYH/789-compare-modal-broken-if-county-is-first-in-list). Weirdly it looks like a `===` became a `!==` at some point and stopped checking if the pinned row is also the first ranked row. Spooky and mysterious :/

Compare bug fix

---

src/cms-content/learn/index.ts
src/screens/Learn/Articles/Article.tsx
src/screens/Learn/CaseStudies/CaseStudy.tsx
src/screens/Learn/Faq/Faq.tsx
src/screens/Learn/Footer/Footer.tsx
src/screens/Learn/Glossary/Glossary.tsx
src/screens/Learn/MetricExplainer/MetricExplainer.tsx

Adds general CAN-related footer to bottom of glossary, faq, metric explainers, articles, and case studies. Also adds glossary-specific footer.

Learn footer

---

src/components/LocationPage/Notifications.tsx

Fixes a typo on NJ's FIPS code and adds Hawaii

exposure notifications: fix New Jersey and add Hawaii

---

src/components/Explore/MultipleLocationsChart.tsx
src/components/Explore/SingleLocationChart.tsx

The grid line is not aligned with the y-axis because of the timezone difference. This PR uses the `scaleUtc` to make sure they match.
**Before**
**After**

fix timezone on explore chart

---

src/common/metric.tsx
src/common/metrics/vaccinations.tsx
src/components/Analytics/utils.ts
src/components/SignalStatus/SignalStatus.style.tsx
src/components/SignalStatus/SignalStatus.tsx
src/components/SummaryStats/LocationHeaderStats.tsx
src/components/SummaryStats/SummaryStats.tsx

[Copy doc](https://docs.google.com/document/d/14d2VfKcl0eqTYUyvuEzR0-cxb95tmdARJ7rceaRwAvg/edit#) + comments from Igor on Slack.
- Update the name of the vaccination metric on:
- Location header
- Compare
- Location page embed
- Vaccination chart
- Change the level of the vaccination metric to unknown so the dot is grey 
- Add tracking for clicks on the CDC link (vaccination disclaimer)
- Remove _Beta_ from ICU Capacity
- Add _Beta_ to Vaccinations

vaccination: copy updates 2

---

src/common/utils/recommend.ts
src/components/LocationPage/Notifications.tsx

Currently the link in the "Notifications" section under "Recommended Actions" section in the locations page uses the general region name instead of state name. This PR changes the link to use state name instead.

Updated region name to state name in notification link

---

src/components/Compare/CompareTableRow.tsx

Changes the styling of the cells for vaccination data so they show the grey dot instead of a dot with a level. Since vaccinations are not graded, I changed the level so it's always unknown. I updated the style of the metric so unknown is based on the value of the metric, not on the level of the metric from the summary.

vaccinations: fix the styling of cells for compare

---

src/common/metrics/vaccinations.tsx

We don't need the summary since this metric is not graded

vaccination: remove metric detail

---

src/components/Charts/Charts.style.ts
src/components/Explore/Explore.style.ts
src/screens/internal/ShareImage/ChartExportImage.tsx

The sharing image has black background, this PR updates the styles of the lines and labels for the vaccination chart so they are lighter when using the dark theme.
To see this image we need to go to `/internal/share-image/states/:stateId/chart/6`, see [Florida](https://covid-projections-git-pablo-vaccination-sharing.covidactnow.now.sh/internal/share-image/states/fl/chart/6), for example
The code that makes colors lighter doesn't work with black, so I hacked it a bit to cover this case. Will implement a better solution post launch!

vaccination: update the styles to work for the dark theme

---

src/components/Explore/ExploreChart.tsx
src/components/Explore/MultipleLocationsChart.tsx

The solution is pretty simple, it just adds a margin on the next label if the y coordinate of the current label is too close to the previous label, and keep the position otherwise. A potential drawback of this solution is that the labels could go off-screen, but since the labels are outside the `RectClipGroup`, there is some extra space below the x-axis that could be used by the labels.
**Before**
**After**

better alignment for the explore labels

---

src/screens/HomePage/HomePage.tsx

This PR updates homepage meta to include vaccine and death keywords.

Add vaccine to homepage meta

---

tools/deploy-s3.sh

This avoids some flakiness that's showing up in our staging deploys.

Specify us-west-1 region in deploy.

---

.github/workflows/prod.yml
.github/workflows/staging.yml
tools/deploy-s3.sh

Removed setting the region in the shell script and simply set the region in the environment variables.
I think setting it in the environment variables makes it a bit more consistent and obvious that region should be set

Fix missing region in aws calls

---

src/components/LocationPage/LocationPageHeader.style.tsx

Changes the location page header buttons to be real buttons instead of wrapped divs to make them accessible. I also added a focused style to match the focused state of links. The buttons can be operated with the keyboard only and have a visual indicator of focus now.

transform the header buttons into real buttons

---

src/common/utils/recommend.ts

Removing school recommendation made the columns look unbalanced. This reorders the recommendations
Before-
After-

Recommendations order

---

src/components/Markdown/utils.ts

#2539 added an `isInternalUrlWithCan` util, which broke markdown links that include covidactnow.org but aren't actually internal links (ie. apidocs.covidactnow.org, blog.covidactnow.org...). This PR fixes

Fixes markdown links, pt. 2

---

src/components/Newsletter/Newsletter.js

Adding the class `fs-exclude` to elements excludes the element from the recordings, the field will be shown as a white block with stripes on the recordings
- [How do I protect my users' privacy in FullStory?](https://help.fullstory.com/hc/en-us/articles/360020623574-How-do-I-protect-my-users-privacy-in-FullStory-)

exclude the user email address from FullStory recordings

---

src/common/metrics/case_density.tsx

This PR adjusts projection timeline from one year to three months. Some considerations:
- Some variable names might be getting a little long? What's the best practice here for keeping variable names concise?
- Need some confirmation on the new text to ensure the new content makes sense and is good to go.

Adjust projection timeline to 3 months

---

src/components/Markdown/MarkdownLink.tsx

The timeout needed a bump from 350->400 in order for the scroll to work properly when page's content isn't yet lazy-loaded

Increase timeout in scrollWithTimeout

---

src/cms-content/learn/products-landing.json
src/components/Markdown/Markdown.style.ts
src/components/Markdown/MarkdownLink.tsx
src/components/Markdown/utils.ts
src/screens/Embed/Embed.style.js
src/screens/Tools/Tools.style.tsx
src/screens/Tools/Tools.tsx

This PR enables CMS users to add our embeds to markdown content inline by adding the URL of the embed as a link on the markdown content.
I also fixed the embed a bit because it wasn't showing the borders correctly, however, this fix will be noticeable only once we deploy this to production (we can test it by replacing the url with the local embed URL (`http://localhost:3000/embed/us/fips/19100`, for example)

cms: allows adding embeds in the markdown blocks

---

src/components/LocationPage/ShareButtons.tsx

The link was showing up as `https://covidactnow.org/us/new_york-ny//chart/6?s=1557497`, so share images weren't working

Fix Chart URL link

---

src/components/RegionVaccinationBlock/RegionVaccinationBlock.tsx
src/components/RegionVaccinationBlock/index.ts

This PR removes the special case for states. I'm keeping the component just in case, but will remove and rename after we launch.

vaccination block: remove special case for states

---

.github/workflows/alert-email-report-prod.yml
.github/workflows/send-alert-emails.yml
.github/workflows/update-snapshot.yml

GitHub disabled short SHA for third-party GitHub Actions, which made the workflow for [alert emails fail this morning](https://github.com/covid-projections/covid-projections/actions/runs/518909331)
The recommended way to use third-party actions is to have the full SHA hash in the action, or use the tag number if we trust the author. I updated the action to use the full hash for now.
- https://github.com/Ilshidur/action-slack/releases
- https://github.com/Ilshidur/action-slack/commit/fb92a78a305a399cd6d8ede99d641f2b9224daf3 (2.0.0 release)
See https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions for more details

update reference to action-slack to use the full commit sha

---

src/components/LocationPage/ChartsHolder.tsx
src/components/RegionVaccinationBlock/RegionVaccinationBlock.style.ts
src/components/RegionVaccinationBlock/RegionVaccinationBlock.tsx

Reported by Igor - fixes an issue that was causing the compare table to not have padding on mobile (location page)

fix alignment for compare on the location page

---

src/components/Analytics/utils.ts
src/components/AppBar/DonateButton.style.ts
src/components/AppBar/DonateButton.tsx
src/components/LinkButton/LinkButton.stories.tsx
src/components/LinkButton/LinkButton.style.ts
src/components/LinkButton/LinkButton.tsx
src/components/LinkButton/index.ts

Implements a reusable LinkButton component. We use links that look like buttons in a couple of places in the app, and we keep re-implementing them each time.
- Don't have double focus (accessibility)
- Handle internal and external links (passing `to` or `href` respectively)
- The type of its props match the types of Material UI button + either Link (from `react-router-dom`) or an anchor element. This allows the button to take any props that a Material UI button would expect.
- Disabled ripple effect (but they can be re-enabled with props)
- Have a focus outline for accessibility
- Don't have much extra styling, that way we can style them for each use case.
The `Donate` button was updated to be based on this new component.

implement LinkButton component

---

src/components/Compare/LocationTable.tsx

[Trello ticket](https://trello.com/c/f5edT7a9/793-4-concerns-that-state-level-compare-charts-only-show-100-counties-when-expanded-even-though-the-copy-says-view-all-counties-in-s)
To test: 
[On prod](https://covidactnow.org/us/missouri-mo/county/jackson_county/?s=1568508), clicking 'View all counties in Missouri' below the compare table only shows the first 100 counties (rather than all 115 in the state)
[With fix](http://localhost:3000/us/missouri-mo/county/jackson_county/?s=1568508)

Fix amount of locations shown in compare modal

---

src/common/hooks/index.ts
src/common/hooks/useScrollToElement.ts
src/screens/Learn/Glossary/Glossary.tsx

Currently, when the user navigates to a term on the glossary page _using a new tab/window_, the page doesn't scroll to the term. This PR fixes the scroll location so even when the user navigates to a term in a new tab/window, the page will automatically scroll to the term's location. Some points to consider:
- Perhaps the `useScrollToTerm` function can be placed in a common location so it can be reused elsewhere. Is `common/hooks` an appropriate place? (If this function is moved, it will be renamed accordingly).
- Glossary term is moved out of the `return` clause to acknowledge them as their own objects. @pnavarrc suggests to have the scroll-to-term functionality within each term object (correct me if I misunderstand though!), although I'm not sure whether we should be mixing an object …

Add useScrollToTerm function

---

package.json
src/components/Analytics/index.ts
src/components/Analytics/utils.ts
src/index.js
src/reportWebVitals.ts
yarn.lock

See https://trello.com/c/CwE3us86/844-performance-add-reporting-of-fcp-to-google-analytics

Add web-vitals measuring and event tracking

---

src/common/models/Projection.ts

We blocked state level TN and WA ICU data due to reporting anamolies in January. Those anomalies have resolved themselves.
See
- https://trello.com/c/dcas02sS/764-disabled-tennessee-icu-capacity-used-suspicious-drop-off-at-tail
- https://trello.com/c/1IkmUuhw/755-disabled-washington-icu-capacity-used-spiked-up-25-to-96-despite-declining-covid-icu-hospitalizations

Re-Enable TN and WA ICU Data

---

src/common/models/Projection.ts

Re-enabling TN and WA ICU Data now that the data reporting issue has resolved itself.
https://trello.com/c/dcas02sS/764-disabled-tennessee-icu-capacity-used-suspicious-drop-off-at-tail
https://trello.com/c/1IkmUuhw/755-disabled-washington-icu-capacity-used-spiked-up-25-to-96-despite-declining-covid-icu-hospitalizations

Re-Enable TN and WA ICU Data (#2637)

---

src/common/models/Projection.ts

For https://trello.com/c/J3M0Ksb5/827-unmask-ohio-vaccination-data this undoes
https://github.com/covid-projections/covid-projections/pull/2499﻿

rm OH counties from disabled vaccinations

---

src/common/metrics/vaccinations.tsx
src/common/models/Projection.ts
src/common/models/Projections.ts

Fix for https://github.com/covid-projections/covid-projections/pull/2634
This PR removes the extraneous conversion from a ratio (0-1) to percent (0-100) and renames the variables from percent... to ratio...
It fixes the incorrect vaccinated count currently seen at https://covidactnow.org/us/tennessee-tn/county/shelby_county/chart/6/
Ran `yarn` and `yarn start` and checked http://localhost:3000/us/tennessee-tn/county/shelby_county/chart/6 has text "In Shelby County, Tennessee, 33,226 people (3.5%) have received the first shot ..."

Fix vaccine ratio/pct mixup

---

src/components/Compare/Compare.style.tsx
src/components/Compare/CompareTableRow.tsx

This PR adds wrappers to the compare table on the homepage to enable more specific styling of location cells. Within each first column cell of the table, this also enables the location name text to roll up to the first line and be immediately next to the rank element.

Get rid of div grouping metro name and state

---

.github/workflows/alert-email-report-prod.yml
.github/workflows/send-alert-emails.yml
scripts/.gitignore
scripts/alert_emails/create_lists_to_email.ts
scripts/alert_emails/firestore.ts
scripts/alert_emails/generate_daily_alerts.ts
scripts/common/firebase/firestore.ts
scripts/common/firebase/index.ts
scripts/vaccination_alerts/README.md
scripts/vaccination_alerts/generate-vaccine-alerts-info.ts
scripts/vaccination_alerts/utils.ts

This PR updates the generate-vaccination-alerts script to fetch the vaccination info version from Firebase and move the `getFirebase` function to a common location since it will be reused for vaccine alerts.

vaccination alerts: fetch vaccination info from Firestore

---

src/common/models/Projection.ts

Masking to ship a snapshot.
https://trello.com/c/9OCK0e3O/878-maine-vaccination-metric-data-off-by-2-decimal-places-likely-ratio-vs-percentage-bug

Disable Maine County Vaccination

---

cypress.json
cypress/plugins/index.js
package.json
yarn.lock

Cypress tests started failing in CI.  I updated the timeout from 60s to 120s and that seems to have fixed it.
They were also failing for me locally, but for a different reason.  Updating the packages and how we initialize the coverage plugin fixed that.

Fix cypress tests locally and in CI.

---

src/common/metrics/case_density.tsx
src/common/metrics/case_growth.tsx
src/common/metrics/positive_rate.tsx
src/common/models/Projection.ts
src/common/models/Projections.ts
src/common/models/ProjectionsPair.ts
src/common/models/ProjectionsSet.ts
src/common/utils/recommend.ts
src/screens/internal/CompareSnapshots/CompareSnapshots.style.js
src/screens/internal/CompareSnapshots/CompareSnapshots.tsx
src/screens/internal/CompareSnapshots/ComparisonList.tsx
src/screens/internal/CompareSnapshots/OptionsSelector.style.ts
src/screens/internal/CompareSnapshots/OptionsSelector.tsx
src/screens/internal/CompareSnapshots/SnapshotVersions.tsx
src/screens/internal/CompareSnapshots/utils.ts

* Cleaned up / centralized how we track disabled metrics.
* Added a "Blocked Locations" item to the "Show" list.
* Refactored the code substantially to make it easier to improve in the future.
* Tweaked sorting so that when diffs are equal (e.g. gained/lost metrics), we order higher-population locations before lower ones.

Add "Blocked Locations" to compare.

---

public/admin/config.yml
src/cms-content/info-tooltips.json
src/cms-content/infoTooltips/index.ts

Uses copy from [figma](https://www.figma.com/file/085lLFwjpkg8JUB05LSUnb/Learn-Product?node-id=121%3A5208) + dummy copy for metrics that aren't in mocks

Info tooltip content in CMS

---

src/App.js
src/assets/theme/typography.tsx
src/screens/internal/VaccinationPhases/VaccinationPhases.tsx

available at `/internal/vaccine-eligibility`.
I wrote this relying less on styled components and more on the material ui system (just because I'm more familiar).  Had to override margins for typography header (which would be nice to look into in general) but otherwise fairly straightforward!

Add vaccination phases internal page

---

src/common/metric.tsx
src/common/metricEnum.ts

I was getting a circular dependency error in a working branch. It seems like the cause might be declaring `Metric` in `metric.ts`--where we also import everything from `common/metric/*each-individual-metric-file*`--each of which import+use `Metric`. This PR pulls the enum into its own file

Metric enum into its own file

---

scripts/alert_emails_report/generate-report.ts

There was an off-by-1 error with the "subscriptions by date" tracking that I've fixed.
Also, the script was silently failing every day due to too many cells in the spreadsheet.  I deleted extra rows/columns, which seems to have fixed it, but I also changed the script so that it will fail more loudly in the future.

Fix email alert script: Fix day tracking and don't fail silently on errors.

---

src/components/EmailAlertsForm/utils.ts

Adds metro's states to default alert signup locations
[Trello ticket](https://trello.com/c/07bDUrRi/886-add-metro-states-to-the-alerts-default-signup-when-youre-on-a-metro-area)

Edit default signup regions

---

firebase/public/googlea39d320c48a99e85.html
scripts/generate_sitemap/utils.ts

Also verify https://covidactnow-prod.web.app/ with Google Search Console per directions on https://developers.google.com/search/docs/advanced/sitemaps/image-sitemaps:
> In some cases, the image URL may not be on the same domain as your main site. This is fine,
> as long as both domains are verified in Search Console.
Resulting entry in the sitemap:
```
<url>
<loc>https://covidactnow.org/</loc>
<image:image>
<image:loc>https://covidactnow-prod.web.app/share/1590-530/2021-02-10-image-covid-us-map-cases.png</image:loc>
<image:caption>A map of the United States colored by the risk level of each county</image:caption>
<image:title>Realtime U.S. COVID Risk Map</image:title>
</image:image>
</url>
```

Add map image to sitemap.

---

src/components/Charts/ChartVaccinations.tsx
src/components/Charts/MetricChart.tsx

If we really want to support this, well need to make additional updates to the copy, but this gets us closer and resolves the symptom reported in https://trello.com/c/gmpQgViy/859-oh-vaccine-timeseries-rendering-mixup
Before:
After:

Make vaccine chart more forgiving of missing 2nd dose data.

---

src/common/fullstory.ts

We write a flag to `localStorage` to determine whether or not to enable FullStory recordings. Some users block applications from writing to `localStorage` and in this case, writing to it would fail (also if the storage is full).
This PR handles that failure more gracefully, catching the error if we can't write to `localStorage`

handle failure to write to localStorage more gracefully

---

src/index.js

We're currently bumping up against the sentry limit for number of events reported. Adding sampling for reporting until we have more bandwidth to tackle the root cause of the issues.

Add sample rate to sentry

---

src/reportWebVitals.ts

Recently there have been a number of errors importing a bundle.  Looking into it, it's probably people on iOS navigating away when the bundle is being downloaded.  However, it looks like the (tiny) `web-vitals` code is already included in the main bundle as it's imported by default.

Directly import web-vitals functions

---

.github/workflows/vaccination-alerts.yml
scripts/vaccination_alerts/utils.ts

This PR enables the vaccination alerts workflow. Since we want to be able to send alerts only for specific states, I added a check to verify that the version in the CMS is 1 or more to actually send the alerts, which is a bit of an undocumented feature (I'm open to better ideas on how to do this!)

enable vaccination alerts workflow

---

src/components/Footer/Footer.style.tsx
src/components/Footer/Footer.tsx

I also changed `div` → `footer` to make it more semantic/accessible.
Note: I initially added `role="contentinfo"` to the footer, but since the footer is directly under `body` that's not necessary (see [WAI-ARIA Practices - ContentInfo](https://www.w3.org/TR/wai-aria-practices-1.2/#aria_lh_contentinfo))

remove the blog link from the footer

---

src/components/Map/Map.style.js
src/components/Map/USACountyMap.js

Increase the target size for Hawaii and Puerto Rico in the US map. I added an huge invisible border to the paths with opacity set to `0` to make the tap size bigger (new tap areas highlighted below). 
I also set `tabIndex=-1` on the link and paths to prevent the map from becoming a keyboard focus trap. A user trying to use `tab` to navigate the page will have to go through all the states before reaching the compare table. We provide a good way to navigate to states already, so I think it's better to skip the map completely from keyboard-navigation for now.

increase target size for HI and PR

---

src/components/Markdown/Markdown.style.ts
src/components/Markdown/MarkdownLink.tsx

This PR adds a corresponding embed link under each embed preview on the "Tools" page. This is a work-in-progress. Some notes regarding necessary revisions are attached to specific parts of the code below.

Add embed link below each embed preview

---

src/components/IndigenousPopulationsFeature/IndigenousDataCheckbox.tsx

The indigenous populations checkbox for Explore wasn't fully associated with its corresponding label, which was causing that clicking on the label didn't toggle the checkbox. This PR fixes that issue.
Note: `aria-labelledby` works for screen readers, but it doesn't implement the behaviour described above.

fix association between checkbox and label for explore

---

src/components/Compare/Filters.style.tsx
src/components/Compare/Filters.tsx
src/components/Compare/HomepageSlider.tsx
src/components/Compare/LocationTable.tsx

A previous bug fix to the compare modal introduced a new one. When the pinned row is ranked #1, no other locations are populating the modal (image below). This fixes.
Also, alignment of the compare filters looked a bit off. This addresses that.
Before:
After:

Fix compare bug + alignment

---

src/common/metrics/vaccinations.tsx

Under vaccinations chart on county+metro pages, there is currently no tooltip with data source info. This PR removes the "where our data comes from" piece of disclaimer copy when there is no tooltip linked.
Before:
After:

Vaccination disclaimer/tooltip edit

---

.github/workflows/vaccination-alerts.yml

So @BrettBoval hopefully doesn't have to go poking in Firebase to figure out what alerts are going to be sent. 😁

Add support for vaccine alert dry runs.

---

.github/workflows/vaccination-alerts.yml

The option `--dryRun` is `true` when passed, and false when the option is absent (like `--verbose`).

fix dryRun option for vaccination alerts workflow

---

src/common/metrics/case_density.tsx
src/common/metrics/case_growth.tsx
src/common/metrics/hospitalizations.tsx
src/common/metrics/positive_rate.tsx
src/common/metrics/vaccinations.tsx
src/components/InfoTooltip/DisclaimerTooltip.tsx
src/components/InfoTooltip/InfoTooltip.tsx
src/components/InfoTooltip/index.tsx
src/components/LocationPage/LocationPageHeader.tsx

We were calling trackOpenTooltip() and trackCloseTooltip() immediately on page
load, instead of when the tooltip was actually opened/closed, causing ~22 (I think) GA
events to be fired on page load.

Fix tooltip analytics event tracking.

---

.github/workflows/update-snapshot.yml

Looks like the vercel deploy link slightly changed: https://covid-projections-git-bump-snapshot-1611-555-covidactnow.vercel.app/internal/compare/ works but https://covid-projections-git-bump-snapshot-1611-555.covidactnow.vercel.app/internal/compare/ does not.  Updating the deploy snapshot workflow accordingly

Update vercel preview link in deploy-snapshot workflow

---

src/components/Banner/VaccinationsBanner.style.tsx
src/components/Banner/VaccinationsBanner.tsx

The banner buttons were implemented as a button inside a link, which caused both elements to have a tab stop when navigating using the keyboard. Now that the `LinkButton` component supports `HashLink`, we can replace the implementation, which avoids the double <kbd>tab</kbd> problem.

a11y: fix the double-focus bug on banner buttons

---

src/screens/LocationPage/LocationPage.tsx

[Trello](https://trello.com/c/0PajW6Pl/968-close-the-county-map-on-mobile-upon-navigation)
The minimap should close when you click it and navigate to a new location page. It currently doesnt. This fixes!

Mobile minimap bug

---

src/cms-content/learn/products-landing.json
src/screens/DataApi/DataApi.tsx

This updates the Data API page content.  There will be many more changes to come, but the content here comes from Tom and I.  Planning on adding more sections other than just license.  
Would like to get this in so that the renamed tools page makes more sense.

Start to add Data API specific content - remove embed :'(

---

src/components/RegionVaccinationBlock/RegionVaccinationBlock.tsx

[Trello](https://trello.com/c/kJpd5apB/908-google-analytics-add-a-custom-dimension-for-the-type-of-page-state-county-metro-home-etc-to-filter-search-events) - Remove location names from vaccination event labels.
The original intent of adding the location name on the events tracking interactions with the vaccination block was to be able to tell in which locations user were interacting with the links more often. That makes difficult to aggregate the events by type of link (Eligibility or Options) across all locations.
Also, there we have [Content Groups](https://support.google.com/analytics/answer/2853423?hl=en) set up for state, metro and county pages, so we can use that as secondary dimension when looking at vaccination events.

remove location name on vaccination events

---

public/index.html
src/components/Analytics/PageviewTracker.tsx
src/components/Experiment/Experiment.tsx

[Trello](https://trello.com/c/KQdb7uEx/740-update-the-page-title-in-ga-every-time-we-navigate) - update the page title when tracking page views.
The page title should be tracked automatically by `ReactGA.pageview`, however, the page view event is fired before the title has time to update. This PR adds a small delay (it seems to be enough) between the change in the URL and the moment when we track the page view so it has the correct title.
I also commented out optimize and removed the linkid plugin (both unused).

analytics: remove unused tracking scripts and fix page title tracking

---

src/components/Analytics/utils.ts
src/components/LocationPage/ChartsHolder.tsx
src/components/RegionItem/RegionItem.tsx

[Trello](https://trello.com/c/ukcrg893/993-track-clicks-on-geolocated-county-vs-geolocated-metro-on-homepage-to-gauge-metro-interest) - Labels the click events on GeoCards by region type instead of by region name to make it easier to compare county vs. metro areas.

analytics: label geolocation events with region type

---

src/common/regions/utils.ts

Currently the search bar on the homepage and location page returns location results in the following order: state, metro area, county. Each of these groups are sorted alphabetically.
This PR sorts search results within each group alphabetically, but if two locations have the same name, then it will sort these locations by population in descending order.

Sort location search results by name (asc) then population (desc)

---

src/components/InfoTooltip/Tooltip.style.tsx

[Trello](https://trello.com/c/BZDZEvvZ/978-mobile-info-tooltip-x-buttons-are-mis-aligned)
Bug -- x-icon should be right aligned:

fixes mobile close icon

---

src/components/VaccinationEligibilityBlock/ButtonBlock.style.tsx
src/components/VaccinationEligibilityBlock/ButtonBlock.tsx

[Trello ticket](https://trello.com/c/D483uORo/965-fix-the-subscribe-to-vaccine-alerts-button-icon-to-not-look-disabled)
Before:
After:

Vaccinations icon bug fix

---

src/components/Compare/HomepageSlider.style.tsx
src/components/Compare/HomepageSlider.tsx

homepageScope isn't a property on the underlying element, so use a `$` so it isn't propagated.  gets rid of a pesky warning.

Fix style on HomepageSlider

---

src/common/ccvi/index.ts
src/common/ccvi/renderRegionDescription.tsx
src/components/Analytics/utils.ts
src/components/Vulnurabilities/FooterLinks/FooterLinks.stories.tsx
src/components/Vulnurabilities/FooterLinks/FooterLinks.style.tsx
src/components/Vulnurabilities/FooterLinks/FooterLinks.tsx

Adds footer link block:
To test:
`yarn storybook`
'VulnerabilitiesFooterLinks' under 'Shared Components'
Also adds utils (`renderStateDescription`, `renderCountyDescription`) to get region score description text (per 'location page copy' section of [the copy doc](https://docs.google.com/document/d/1svP2I63M6JUGuNAM1QoAa6IOC8Vd7uYluenRi8wT_Zk/edit#))

Vulnerabilities footer links

---

src/common/ccvi/renderRegionDescription.tsx
src/components/InfoTooltip/Tooltip.style.tsx
src/components/VulnerabilitiesBlock/CcviThermometer/CcviThermometer.stories.tsx
src/components/VulnerabilitiesBlock/CcviThermometer/CcviThermometer.tsx
src/components/VulnerabilitiesBlock/ThemesBlock/ThemesBlock.tsx
src/components/VulnerabilitiesBlock/VulnerabilitiesBlock.style.tsx
src/components/VulnerabilitiesBlock/VulnerabilitiesBlock.tsx

- Ccvi thermometer: positions triangle in the middle of the level's color, not according to specific score
- Specific vulnerabilities table: sorts list from high->low
- Makes bold text black
- Adds region name to thermometer title+aria label
- Fixes punctuation in renderRegionDescription
- Changes default tooltip positioning from bottom->top

Vulnerabilities feedback items

---

src/components/Compare/Filters.tsx
src/components/Compare/ModalCompare.tsx

This PR removes the metro/non-metro dropdown from the compare table in both the homepage and location page, including in modal view. Some considerations below:
- All unused variables as a result of the deletion are currently commented out. Once @pnavarrc and @chasulin confirm the elements to be deleted, these variables can be removed.
- Leaving the "More Info" button at the bottom of the compare table as is for now, as we may simply be replacing the content inside the pop-up.

Remove metro/non-metro dropdown from compare table

---

src/components/InfoTooltip/Tooltip.style.tsx

Tooltip style fix

---

src/components/LocationPage/Notifications.tsx

Vulnerabilities hashlink scroll doesn't account for the header/searchbar height. This adds a scroll offset

Vulnerabilities scroll bug

---

src/common/metrics/vaccinations.tsx
src/components/Banner/VaccinationsBanner.style.tsx
src/components/Banner/VaccinationsBanner.tsx
src/components/Charts/MetricChart.tsx
src/components/SummaryStats/LocationHeaderStats.tsx

[Trello](https://trello.com/c/PugEl67z/1000-update-vaccinations-for-jj) - Update vaccination copy in preparation for Johnson & Johnson vaccines.
The ticket doesn't detail all the necessary updates, so I changed the copy following the same language. Make sure to check:
**Home page**
- Banner copy
- Compare: Table header name
**Location pages**
- Header
- Compare: Table header name
- Chart title
- Chart description
- Chart labels
The remaining mentions to 1st and 2nd shots are in Learn or the tooltips, and will be updated via the CMS.

update web copy for vaccination doses

---

src/common/fullstory.ts
src/components/Analytics/PageviewTracker.tsx
src/components/Analytics/utils.ts
src/components/InfoTooltip/InfoTooltip.tsx

- Cleanup `fullstory.ts` a bit (dynamic import and made the code follow a similar structure than `amplitude.ts`)
- Add tracking of events in FullStory when FS tracking is enabled
- Fixed the "open tooltip" event, it was being tracked multiple times (hover triggers multiple times when the user moves the mouse)
**Testing**
- In the Chrome console (in local dev), set the tracking flag in `localStorage` to `"true"` `localStorage.setItem('FULLSTORY_RECORD', 'true')` and reload the page
- Click around the app with the Network tab open, you should see some requests to FullStory
- Change the flag to `false` to disable recording `localStorage.setItem('FULLSTORY_RECORD', 'false')` and reload the page
- Click around the app, there shouldn't be more requests to FullStory

analytics: track events in FullStory

---

src/common/metric.tsx
src/common/metrics/vaccinations.tsx
src/components/Disclaimer/Disclaimer.tsx
src/components/LocationPage/ChartBlock.tsx

(Forgot to do this in the last PR that shipped provenance):
We don't have a fallback source for county-level vaccinations and so we were hiding the 'data source' half of the vaccinations chart disclaimer for non-state pages. Now that we have provenance for some county vaccinations, this un-hides that half of the disclaimer and allows it to render if there is vaccinations data provenance.
This also removes the `getMetricDisclaimer` util and calls `renderDisclaimer` directly in ChartBlock.tsx

Disclaimer cleanup, vaccinations provenance fix

---

src/cms-content/vaccines/email-alerts.ts

[Trello](https://trello.com/c/XnbCqZ2O/1053-revert-the-order-of-the-eligible-phases-in-the-vaccination-alerts-email) 
We want to reorder the vaccination phases to show the most recently eligible phase first, and past phases in reverse order. For most places, we don't have the date when the phase became eligible, so we rely on the order they were added in the CMS.

vaccination alerts: reorder phases (most recently eligible first)

---

src/components/Explore/Explore.tsx
src/components/Explore/utils.ts

We've deprecated the google slides source deck doc. Eventually we would like a similar "find where this data comes from" as we do for the metrics, but for now I'm removing the old links and just keeping it generic.

Removed Source Deck Link in Explore

---

src/components/Charts/BoxedAnnotation.tsx
src/components/Charts/ChartCaseDensity.tsx
src/components/Charts/Charts.style.ts
src/components/Charts/ZoneAnnotation.tsx
src/components/Charts/utils.ts

- Moves risk level labels to the left side of each metric chart
- Only renders active zone's label on mobile
- Removes padding on right side of x-axis that previously made room for labels

Chart label + bottom axis edits

---

src/components/Charts/utils.ts

Max-y currently defaults to whichever # is larger between 1.5 * upperLimit vs. the max value. This pr changes that 1.5 to 1.2 in order to use as little vertical space as is necessary.
Example before:
Example after:

Metric chart max-y edit

---

src/components/Charts/ChartICUCapacityUsed.tsx
src/components/Charts/ChartZones.tsx

ICU chart needs a bit more spacing for the y axis labels than the other metric charts
Before:
After:

ICU chart margin edit

---

public/admin/config.yml
src/cms-content/footer/index.ts

Adds fields to `config.yml` for the new footer's about-us paragraph + learn links

Footer content in CMS config

---

public/admin-vaccines/config.yml
src/cms-content/vaccines/phases.test.ts
src/cms-content/vaccines/phases.ts
src/cms-content/vaccines/state-vaccine-phases.json

[Trello](https://trello.com/c/Aus9dlOE/1027-update-the-data-type-for-emailalertversion-on-the-cms) - The UI to change numbers is error-prone, so it's easier for the team to enter values as strings. In this PR, I change the type in the CMS config and the JSON file, but leave the external interface of the vaccination phases info unchanged (the emailAlertVersion is exposed as a number)
- Updated the config to take strings
- Updated the vaccine information (phases) to be strings
- Added unit tests to ensure that `emailAlertVersion` is a number
- Add unit tests to ensure that there are no repeated states

cms vaccines: update the emailAlertVersion to be a string field

---

src/screens/HomePage/CriteriaExplanation/CriteriaExplanation.style.tsx
src/screens/HomePage/CriteriaExplanation/CriteriaExplanation.tsx

[Trello](https://trello.com/c/1P5daYqh/1024-remove-phrase-from-key-risk-metrics-section-of-homepage)

remove learn more under key metrics

---

src/common/theme/fonts.ts
src/common/theme/index.ts
src/components/Compare/ModalFaq.style.tsx
src/screens/AlertUnsubscribe/AlertUnsubscribe.style.tsx

Starts to centralize our font styles
Adds `common/theme` folder, currently with `fonts.ts` (later going to add `colors.ts` into it as well)
In `fonts.ts`, we are exporting each set of font styles (ie. roboto + bold) as a set of css properties, that can be called as `${fonts.regularBookBold}`

Fonts file

---

.github/workflows/vaccination-alerts.yml
scripts/vaccination_alerts/generate-users-to-email.ts

* Remove noisy logs that were for debugging.
* Fix logs to log location names instead of FIPS.
* Tweak github workflow to have a "send emails" option instead of "dry run"
option to be more similar to risk alerts.
https://trello.com/c/gS9cOyG3/1030-vaccine-emails-dryrun-state-abbr-instead-of-fips-in-summary

Clean up logging and dry run setting for vaccination emails.

---

src/components/Compare/ModalCompare.tsx
src/components/Compare/ModalFaq.tsx

This lets these things take a forwarded ref, they don't do anything with it, but it avoids some very long log messages from Mui components that clutter the error and warning stream.

ForwardRef for Mui complaints

---

src/cms-content/articles/index.ts
src/cms-content/articles/utils.ts
src/common/urls.ts
src/common/utils/index.ts
src/common/utils/model.ts
src/common/utils/time-utils.test.ts
src/common/utils/time-utils.ts
src/components/Charts/ChartCaseDensity.tsx
src/components/Charts/ChartRt.tsx
src/components/Charts/ChartVaccinations.tsx
src/components/Charts/ChartZones.tsx
src/components/Explore/MultipleLocationsChart.tsx
src/components/Explore/SingleLocationChart.tsx
src/components/Explore/utils.ts
src/components/Header/HomePageHeader.tsx
src/components/LocationPage/ShareButtons.tsx
src/screens/Learn/Faq/Faq.tsx
src/screens/Learn/Glossary/Glossary.tsx
src/screens/internal/ShareImage/ShareCardImage.tsx

This PR migrates all direct usages of `moment` for UTC conversion to using time utils instead.

Migrate UTC conversion instances to time utils

---

src/components/LocationPage/LocationPageHeader.tsx
src/components/LocationPage/Notifications.tsx

We don't need projections in the notification block, so use the region, which is already available.  This will help unblock deferred-loading of projection data on location pages, which should help FCP.

Use region instead of projections

---

src/components/LocationPage/ChartsHolder.tsx
src/components/LocationPage/LocationPageHeader.tsx
src/components/LocationPage/Notifications.tsx

We don't actually need the whole projections in the location page header, so pull it out and pass in or compute what we need (alarmLevel / isCounty).
This will also help defer loading of projection details for metrics charts below while still rendering a helpful header above the fold.

Pull `projections` out of LocationPageHeader

---

src/common/utils/time-utils.test.ts
src/common/utils/time-utils.ts

This PR creates time utils to add time to or subtract time from a given date object in specified units. Functions adding or subtracting time that are directly using `moment` will be replaced with these time utils. After that, we will switch these utils to use `Luxon` instead.

Add time manipulation utils

---

scripts/alert_emails/generate_daily_alerts.ts
src/common/utils/time-utils.test.ts
src/common/utils/time-utils.ts
src/components/Charts/utils.ts
src/components/NationalText/utils.tsx

This PR migrates time additions and subtractions to Luxon and adds a time util to parse time from Unix timestamp (in milliseconds).

Migrate time manipulation utils to Luxon

---

src/screens/internal/ShareImage/HomeShareCardImage.tsx
src/screens/internal/ShareImage/LocationShareCardImage.tsx
src/screens/internal/ShareImage/ShareImage.tsx

This resolves a todo by @mikelehen and also simplifies migration to next.js
I thought about making a component that takes {children} instead of copying the wrappers, but wasn't sure it was worth the hassle.  Feel free to press for that though, if you think it is.
It also became evident that the homepage does *not* include the `<ScreenshotReady>` component like the individual location-based share cards do.  Is that intentional, or a bug?  Let me know, I can fix it while I'm at it.

Split ShareCardImage into Home and Location versions

---

src/components/ShareBlock/ShareBlock.tsx
src/components/SocialLocationPreview/SocialLocationPreview.tsx
src/components/SocialLocationPreview/SocialLocationPreviewMap.tsx
src/screens/Embed/Embed.tsx
src/screens/internal/ShareImage/HomeShareCardImage.tsx
src/screens/internal/ShareImage/USMapImage.tsx

Split out the map-specific view, so that the location-specific version can have non-optional props, simplifies and smooths the way for next.js migration.
Depends on the ShareCardImage pull request (https://github.com/covid-projections/covid-projections/pull/3057) being landed first.  I'll have to clean up and rebase after that lands.

Split Map view from SocialLocationPreview

---

src/common/models/Projections.ts
src/components/LocationPage/ChartsHolder.tsx
src/components/LocationPage/LocationPageHeader.tsx
src/screens/LocationPage/LocationPage.tsx

This allows deferred loading of the projections needed for the other graphs below the fold.

Use summary for location page header

---

src/components/ExternalLink/ExternalLink.tsx
src/components/NewFooter/MenuContent.tsx

- The `ExternalLink` component was not passing additional link props to the underlying `a` element
- The link to the logo didn't have an alt-text (set to "Covid Act Now")

add missing aria-labels on the new footer

---

src/components/Compare/HomepageSlider.stories.tsx
src/components/Compare/HomepageSlider.tsx

[Trello](https://trello.com/c/HQ4EvlEY/1117-accessibility-add-aria-labels-to-slider-values) - The slider component was missing the `aria-label` attribute and the text version for the selected value. I also added the `getValueLabel` property which gives values its corresponding name.
Tested with VoiceOver, works well 
**Learn more**
- https://material-ui.com/components/slider/#accessibility
- https://material-ui.com/api/slider/

fix compare slider component

---

src/components/EmailAlertsForm/EmailAlertsForm.tsx

[Trello](https://trello.com/c/x7OlFWF6/1112-bug-placeholder-for-email-input-on-iphone-5-se-overlaps-the-sign-up-button) - Fix the email form placeholder for iPhone 5.
I just changed "Enter your email address" to "Enter your email" for viewports 320px and under.
**iPhone X (375px)**
**iPhone 5 (320px)**

change the email input label under 360px

---

src/components/NewFooter/Footer.tsx

Bug: new footer was rendering in embed. This removes. [Trello](https://trello.com/c/tDTgkBC5/1132-new-footer-shows-up-in-embeds)

Remove footer from embed

---

src/components/AppBar/NavBar.tsx

- Add aria-labels for the Logo and back links on the NavBar component.
- For logos and links that go to the home page, it's considered better to spell out the name of the website rather than having something more contextual like "Home" or "Back"

add aria-label to nav bar home and back links

---

public/index.html
src/screens/internal/ShareImage/HomeShareCardImage.tsx

- Preload the fonts. Lighthouse keeps saying that they are in the critical rendering path. I tested this branch and couldn't see an improvement, but no harm either, so probably worth trying.
- Remove extra semicolon in a JSX statement.
**Note**
The linter re-indented the `index.html` file, but the only changes are 
```html
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link
rel="preload"
as="style"
href="https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;700&family=Roboto:wght@400;500;700&display=swap"/>
```

performance: preload fonts

---

src/common/regions/types.ts
src/common/utils/compare.ts
src/common/utils/recommend.ts

Found out about this while investigating Next.js. `common/utils/compare` imports stuff from `common/regions`, and `common/regions` was importing `getAbbreviatedCounty` from `common/utils/compare`.
Webpack is smart enough (to a point) to handle this, but on one of my experiments this circular dependency was preventing the static HTML files from being generated, so I figured it might make sense to move the function.

circular dependency: move an utility function from compare → regions

---

public/admin/config.yml
src/cms-content/learn/landing.ts
src/cms-content/learn/learn-landing.json
src/screens/Learn/Landing/Landing.tsx

Moves editorial note to bottom of page of [learn landing page](https://covid-projections-git-casulin-learn-landing-update-covidactnow.vercel.app/learn)

Learn landing page update

---

src/cms-content/utils.ts

Noticed while [qa'ing this PR](https://github.com/covid-projections/covid-projections/pull/3087) that some share URLs weren't working properly because their IDs were entered into the CMS with trailing white space. This fixes

Trims FAQ ids

---

src/screens/Learn/Faq/Section.tsx

This PR experiments with adding share widgets to each FAQ. All props of `SmallShareButtons` are not implemented yet as this is simply an exploration.

Add share widgets to FAQ

---

src/components/Explore/utils.ts

This PR gets rid of floating point date values on Explore charts.

Fix date precision on explore

---

src/common/utils/compare.ts
src/components/Compare/CompareMain.tsx
src/components/Compare/CompareTable.tsx
src/components/Compare/Filters.tsx
src/components/Compare/ModalCompare.tsx

We [removed the metro/non-metro county filter](https://github.com/covid-projections/covid-projections/pull/2912) from compare. This removes all related code that supported that filter
Also adds stateCode to county share quotes

Compare cleanup: remove metro-filter-related code

---

src/common/metrics/case_density.tsx
src/common/metrics/case_growth.tsx
src/common/metrics/hospitalizations.tsx
src/common/metrics/positive_rate.tsx
src/common/metrics/vaccinations.tsx
src/components/Charts/Tooltip.style.ts
src/components/DataCoverageTable/DataCoverageTable.style.tsx
src/components/DataCoverageTable/DataCoverageTable.tsx
src/components/InfoTooltip/TextTooltip.tsx
src/components/InfoTooltip/Tooltip.style.tsx
src/components/InfoTooltip/index.tsx

Implements new styling for tooltip anchor text ([figma](https://www.figma.com/file/l4Lra5SwXH2NX6XtZdDVWd/Buttons-and-Links?node-id=66%3A607)), applies to data api table tooltips and chart disclaimer tooltips. Renames `DisclaimerTooltip` to `TextTooltip`
[Trello ticket](https://trello.com/c/jVsSBn7E/1068-implement-new-design-pattern-for-text-that-triggers-tooltips)

Text tooltips update

---

src/cms-content/tooltips/metric-calculation-tooltips.json

There were 2 links without text, probably added by mistake

remove empty links on info tooltips

---

src/components/Map/MapCounties.tsx
src/components/Map/USACountyMap.tsx
src/components/RegionMap/RegionMap.tsx

SVG paths with `role="img"` need to have labels. Adding `aria-label` for those elements! Also filter out geographies that are in the TopoJSON file but that we don't have in regions (American Samoa and Guam I think?)

accessibility: add aria labels to map elements with img role

---

src/components/SharedComponents/SwitchComponent.tsx

VoiceOver doesn't read the state of the checkbox using the labels, it still reads them as on/off, so I added that to the label for the checkbox.

accessibility: add label and aria-label for the county-state switch

---

public/covid-response-simulator-version.txt

[Trello](https://trello.com/c/qQ8H2TOH/1191-release-175-for-crs-fixing-api-change-issue-current-165-version-does-not-work-anymore-and-users-complained-https-docsgooglecom-s) - Update CRS version number and link

update the version and link of the CRS

---

src/common/models/Projection.ts
src/common/utils/time-utils.test.ts
src/common/utils/time-utils.ts

This reverts commit 53994c4153022d644dacf7c04d78823c7536fc0c.
It turns out this regressed some charts so that they were missing the last data point. Strangely not all places were affected (e.g. Washington and King County seem okay, but Monroe Metro, MI loses the last data point in the chart).
E.g.:

Revert "Switch from using moment to time utils in projection.ts (#3222)"

---

src/common/hooks/useGeolocation.ts
src/components/Experiment/Experiment.tsx
src/components/RegionItem/HomepageItems.tsx
src/screens/HomePage/HomePage.tsx

This PR adds a parameter to the `HomePageItems` component which enables one to select whether the component will show metro and county side by side or state and county side by side.
The default behavior is the page showing metro and county. However, if one passes `False` as the `showMetro` parameter to `HomePageItems`, then the page will show state and county instead. This shall enable A/B testing for showing metro and county side by side versus state and county side by side.

A/B testing: metro vs. state in geolocation cards

---

src/components/NewFooter/Menu.style.tsx

The browser's menu bar was covering the bottom of the mega menu. This increases the mega menu's bottom padding to account for this

Mega menu mobile bug fix

---

public/index.html

I'm not 100% sure where our old pixel code came from.  I've pinged Anya and Mike McDonald (who made the [original change](https://github.com/covid-projections/covid-projections/commit/b88c3517a453cc233632227603889e48f5bcf851) but is no longer on the team).  If I don't hear back from them, I'll just merge this tonight or tomorrow and we'll see if anything breaks / people complain. 😬

Update FB Pixel with one from Jess to track API ad conversions.

---

src/assets/theme/buttons.tsx
src/assets/theme/fontBlocks.ts
src/assets/theme/fonts.ts
src/assets/theme/index.tsx
src/common/theme/index.ts
src/components/AppBar/NavBar.style.ts
src/components/Compare/ModalFaq.style.tsx
src/components/LocationPage/Experiment/GetAlertsButton.style.tsx
src/components/MenuContent/Menu.style.tsx
src/components/Typography/Typography.style.ts
src/screens/AlertUnsubscribe/AlertUnsubscribe.style.tsx

- Moves font blocks into main theme + updates implementations to call fonts using props instead of directly importing from `fonts.tsx`
- Deletes typography font styles -- 2/3 of them were unused. Moved the one used set (`subtitle1`) into `Typography.style.ts`

Reorganize theme fonts

---

src/components/Analytics/amplitude.ts

Note that the utm params get set as user properties on the session and so only happens at the beginning of a session.  To test it I had to clear some stuff in localStorage / cookies to force a new session (which also accidentally logged me out of gmail, so be careful I guess).

Enable attribution tracking in amplitude.

---

src/components/Explore/Axes.tsx

[Trello](https://trello.com/c/u4gUsEyf/1232-explore-chart-hide-the-last-tick-mark-if-its-outside-the-charting-area) - Hide the last x-axis label if the date is outside the chart range
**Before**
**After**

hide the last x-axis label if the date is beyond the chart range

---

package.json

Sometimes we accidentally check in unused variables and it breaks our staging / prod deploys (e.g. https://github.com/covid-projections/covid-projections/actions/runs/731082728) even though CI doesn't complain.  This should fix that.  May want to do the same for the climate repo.

Make eslint fail on warnings.

---

src/components/ShareBlock/ShareModelBlock.tsx

The Region-derived classes do exactly what we need for this, so we can simplify this function and avoid reaching into the data members of those classes and duplicating the behavior.

cleanup getUrlAndShareQuote

---

scripts/prepare_regions_data/prepare-regions-data.ts
scripts/prepare_regions_data/regions_data.ts
src/common/regions/preprocessed_regions_data.ts
src/common/regions/types.ts
src/common/regions/utils.ts
src/common/utils/compare.ts
src/components/RegionMap/RegionMap.tsx
src/components/RegionVaccinationBlock/utils.ts
src/components/Search/utils.ts

This embeds the `statesByFips` lookup so that we can construct counties and metroareas that reference states directly from the FIPS that we store, making toJSON and fromJSON possible with no additional parameters.  To make this work, `statesByFips` must be constructed in the `regions/types.ts` package, to void a circular dependency.  I was worried this would smell too bad to actually use, but after trying it, it wasn't as bad as I thought.
To unlock this, metroAreas must not refer directly to county objects, so this diff stores countyFips directly instead.  In all cases but one this actually simplified things, since we were mapping across counties to get the FIPS code.  In the one case it didn't, we already imported the regions DB so a lookup was straightforward.
While doing this I …

clean up region classes some

---

src/common/regions/region_db.ts
src/common/regions/region_hooks.ts

These unblock a bunch other changes to defer loading the regions DB at build time.  This diff itself should not affect performance, as the functions aren't called anywhere yet.

add getRegionsDB and useRegionsDB utilities

---

src/cms-content/vaccines/phases.test.ts

We have a `stateByFips` lookup we can use now instead.

remove region DB load from vaccines phases test

---

src/common/location_summaries.ts

This re-fetches the snapshot every time.  We didn't notice when it was using the version provided by the bundle, but it's evident when using an override.
Setting the dependency to snapshot version should prevent re-fetching and object identity-based state update.

Make snapshot useEffect dependency to avoid continual fetching

---

src/components/NewLocationPage/RiskThermometer/DesktopThermometer.stories.tsx
src/components/NewLocationPage/RiskThermometer/DesktopThermometer.tsx
src/components/NewLocationPage/RiskThermometer/MobileThermometer.stories.tsx
src/components/NewLocationPage/RiskThermometer/MobileThermometer.tsx
src/components/NewLocationPage/RiskThermometer/RiskThermometer.style.tsx

[Location page redesign figma](https://www.figma.com/file/JGqemgZwlG9e5DQbZpdKgy/Redesign?node-id=1742%3A120358)
Keeps desktop + mobile separate. Desktop is just a single vertical div, mobile is horizontal and outlines the current risk level's color
(storybook only)

New risk thermometers

---

src/components/MenuContent/LearnSection.tsx
src/components/MenuContent/Menu.style.tsx
src/components/MenuContent/index.ts
src/components/NewLocationPage/Shared/LabelWithChevron.tsx
src/components/TextAndIconWithSpecialWrapping/TextAndIconWithSpecialWrapping.tsx

the correct font weight wasnt being applied to both spans. this fixes + moves the component out of the `MenuContent` folder, since it is now being used outside of the menu

Fix bug on TextAndIconWithSpecialWrapping

---

src/components/Compare/CompareTableRow.tsx

To clear the DOM validation warning.  Seems the most straightforward way, which preserves any styling on the links, and allows non-link areas of the row to be clickable to navigate.

Move <a> into cells, add onClick to navigate on row

---

src/components/LocationPage/LocationPageHeader.style.tsx
src/components/LocationPage/LocationPageHeader.tsx

The tooltip div in the header was inside a `<p>`, which is a no-no.  The fix is to move it outside the `<p>`, and change the style to `inline-block` so that it remains on the same line, instead of automatically being put on the next one.
Before: 
After:

Correct dom validation issue in location page header

---

src/components/LocationPage/ChartsHolder.tsx

This eliminates a react "key" warning.

move key on chart holder

---

src/common/hooks/useGeolocation.ts

It looks like we're making multiple geolocation requests.  Forcing the hook that fetches to be a singleton, that way, we'll only ever request it once.

Make geolocation fetch singleton

---

src/common/regions/utils.ts

this did an expensive search (scan through all counties to match by zip code) twice, this does it once and reuses the value, and uses a state code lookup table instead of a manual scan

improve getGeolocatedRegions

---

src/components/Compare/Compare.style.tsx
src/components/Compare/LocationTable.style.tsx
src/components/Compare/LocationTable.tsx

[Reorganizing compare row elements in this PR](https://github.com/covid-projections/covid-projections/pull/3408) made it so that the location name was no longer turning blue when hovering the row ([see here](https://covidactnow.org/?s=1783703) on prod when hovering a compare row). This fixes + also reorders some imports

Compare highlight fix

---

src/components/Explore/DateMarker.tsx
src/components/Explore/MultipleLocationsChart.tsx
src/components/Explore/SingleLocationChart.tsx

This PR sets midnight as the baseline for date comparison. This is a WIP as I am still testing it further.

Fix "days ago" display on chart

---

src/screens/HomePage/HomePage.tsx

some refactoring was merged last week that adds more lazy loading. as a result, links that scroll to a particular element using refs (rather than hashLinks) aren't scrolling to the right places. this is a quick fix for [the alerts signup link](http://covidactnow.org/alert_signup). adding a trello ticket to address the bug as a whole
using git bisect--[this looks like the PR](https://github.com/covid-projections/covid-projections/pull/3357) where the scroll bug originated

Quick fix to scroll issue

---

src/components/InfoTooltip/Tooltip.style.tsx
src/components/InfoTooltip/index.tsx
src/components/LocationPage/LocationPageHeader.style.tsx
src/components/NewLocationPage/OverallRiskBlock/OverallLevelText/OverallLevelText.stories.tsx
src/components/NewLocationPage/OverallRiskBlock/OverallLevelText/OverallLevelText.style.tsx
src/components/NewLocationPage/OverallRiskBlock/OverallLevelText/OverallLevelText.tsx
src/components/NewLocationPage/OverallRiskBlock/OverallRiskBlock.stories.tsx
src/components/NewLocationPage/OverallRiskBlock/OverallRiskBlock.style.tsx
src/components/NewLocationPage/OverallRiskBlock/OverallRiskBlock.tsx
src/components/NewLocationPage/RiskThermometer/RiskThermometer.tsx
src/components/NewLocationPage/RiskThermometer/index.ts
src/components/NewLocationPage/Shared/Shared.style.tsx
src/components/NewLocationPage/SummaryStatsBlock/MetricValue.tsx
src/components/NewLocationPage/SummaryStatsBlock/SummaryStat.tsx
src/components/NewLocationPage/SummaryStatsBlock/SummaryStatsBlock.style.tsx

[Figma mocks](https://www.figma.com/file/JGqemgZwlG9e5DQbZpdKgy/Redesign?node-id=1742%3A120358)
`Location page redesign/Overall risk block` in storybook
Mobile:
Desktop:

New overall risk block

---

src/App.tsx

We're going to point blog.covidactnow.org at the main website and turn off the WordPress blog.  These URL redirects were provided by Mikayla.

Redirect blog URLs to right places.

---

src/components/MenuContent/MenuContent.tsx
src/components/RegionItem/HomepageItems.tsx
src/screens/HomePage/HomePage.tsx

- Ends experiment testing state/county vs. metro/county geolocated items on the homepage
- Ships state/county combo to all users
- Ends experiment testing the placement of the data API link in the mega menu (first in list vs. last in list)
- Ships last in list to all users

Remove geolocated metro region, end API link experiment

---

src/components/NewLocationPage/NotesBlock/NotesBlock.stories.tsx
src/components/NewLocationPage/NotesBlock/NotesBlock.style.tsx
src/components/NewLocationPage/NotesBlock/NotesBlock.tsx

This moves `StyledBaseButton` inside of `SectionContainer` so `SectionContainer` is always the parent div of each location page module above the fold
(not yet on prod, just storybook- Location page redesign/Notes Block)

Move button inside of NotesBlock container

---

src/common/utils/time-utils.ts
src/components/InfoTooltip/Tooltip.style.tsx
src/components/NewLocationPage/LocationName/LocationName.style.tsx
src/components/NewLocationPage/LocationName/LocationName.tsx

This PR adds an "Updated on <DATE>" component below the region name in the new location page header.
We also add a new date-time format to enable usage of the new time util (time formatting as "8 AM PDT", which will be displayed in the tooltip.
All tooltip links site wide are also updated to have a dotted line underneath, not a dashed line underneath, as per new design.

Add updated date to location name header

---

src/components/Markdown/MarkdownLink.tsx

This PR adds timeout to correct the scrolling position. Unfortunately, I also tried 700, 800, and 900 milliseconds. They did not give reliable scroll behaviour. Also tried other scrolling methods (e.g. `scrollIntoView`, `scrollTo`, etc.) and the incorrect scrolling persisted. Adjusting the timeout to 1000 milliseconds seems to be the only reliable fix so far.

Add timeout to correct scrolling position

---

src/components/LocationPage/ChartsHolder.tsx
src/components/NewLocationPage/AboveTheFold/AboveTheFold.stories.tsx
src/components/NewLocationPage/AboveTheFold/AboveTheFold.style.tsx
src/components/NewLocationPage/AboveTheFold/AboveTheFold.tsx
src/components/NewLocationPage/HeaderButtons/HeaderButtons.tsx
src/components/NewLocationPage/HeaderButtons/ShareButton.stories.tsx
src/components/NewLocationPage/HeaderButtons/ShareButton.tsx
src/components/NewLocationPage/LocationName/LocationName.style.tsx
src/components/NewLocationPage/LocationOverview/LocationOverview.stories.tsx
src/components/NewLocationPage/LocationOverview/LocationOverview.style.tsx
src/components/NewLocationPage/LocationOverview/LocationOverview.tsx
src/components/NewLocationPage/NotesBlock/NotesBlock.stories.tsx
src/components/NewLocationPage/NotesBlock/VulnerabilityNote.tsx
src/components/NewLocationPage/Shared/Shared.style.tsx
src/components/NewLocationPage/SparkLineBlock/SparkLineSet.tsx
src/components/NewLocationPage/SummaryStat/SummaryStat.style.tsx

- Fixes order of top level metrics (swaps rt and pos test rate)
- Fixes order of spark lines (switches hospitalizations and deaths)
- Fixes scroll target for share button (was prev scrolling to alerts section) + mobile get alerts button (was prev not doing anything)
- Wires up region's location name to vulnerability note
- Makes alert section 2 columns wide when screen is between 600px and 800px

Some location page feedback/fixes

---

src/components/Banner/GetVaccinatedBanner.tsx

This PR removes the second sentence from the homepage banner to save space and minimize redundancy above the fold.

Remove second sentence from homepage banner

---

src/components/LocationPage/ChartsHolder.tsx
src/components/NewLocationPage/AboveTheFold/AboveTheFold.stories.tsx
src/components/NewLocationPage/AboveTheFold/AboveTheFold.tsx
src/components/NewLocationPage/LocationOverview/LocationOverview.style.tsx
src/components/NewLocationPage/LocationOverview/LocationOverview.tsx
src/components/NewLocationPage/NotesBlock/NotesBlock.style.tsx
src/components/NewLocationPage/OverallRiskBlock/OverallLevelText/OverallLevelText.style.tsx
src/components/NewLocationPage/Shared/LabelWithChevron.tsx
src/components/NewLocationPage/SparkLineBlock/SparkLineBlock.stories.tsx
src/components/NewLocationPage/SparkLineBlock/SparkLineBlock.style.tsx
src/components/NewLocationPage/SparkLineBlock/SparkLineBlock.tsx
src/components/NewLocationPage/SparkLineBlock/SparkLineSet.tsx
src/components/NewLocationPage/SparkLineBlock/utils.ts
src/components/NewLocationPage/SummaryStat/DesktopSummaryStat.tsx
src/components/NewLocationPage/SummaryStat/MetricValue.tsx
src/components/NewLocationPage/SummaryStat/MobileSummaryStat.tsx
src/components/NewLocationPage/SummaryStat/SummaryStat.style.tsx

- Uses ref instead of hash link + maps `SparkLineMetric` to `ExploreMetric`
- Fixes alignment of chevron icons in spark line and summary stat labels
- Makes vax progress bar clickable
- Remove grey circle icon from percent vaccinated summary stat
- Fixes line height of notes block title
- Drops font weight of overall risk level label to 1.4 rem on iphone5

Spark lines selecting correct explore tab

---

src/components/NewLocationPage/SparkLineBlock/SparkLineBlock.style.tsx
src/components/NewLocationPage/SparkLineBlock/SparkLineSet.tsx
src/components/NewLocationPage/SparkLineBlock/utils.ts

Spark lines were causing whole page to crash in the case of there being no data for any of the 3 metrics. This fixes
To test-
-  [Inyo county, CA is crashing in the main preview link](https://covid-projections-git-casulin-redesign-demo-covidactnow.vercel.app/us/california-ca/county/inyo_county?s=1793712)
- [this includes the fix](https://covid-projections-git-casulin-sparklines-fix-covidactnow.vercel.app/us/california-ca/county/inyo_county/?s=1793712)

Spark line fix

---

src/common/hooks/index.ts
src/common/hooks/useLogChanges.ts
src/screens/HomePage/HomePage.tsx
src/screens/HomePage/utils.ts

Basic issue was that `initialFipsList` property was being recomputed to a different (but identical) Array on every HomePage render and causing the explore chart component to think it had changed (since React only does shallow
comparisons it doesn't matter that the Array was identical).
* Removes no-longer-needed code for showing hospitalizations in the homepage explore chart, since it was causing `initialFipsList` to change on every render.
* Use `useMemo()` to memoize `exploreGeoLocations` to make sure it doesn't change on every render.
* Turns `getLargestMetroFipsForExplore()` function into a `largestMetroFipsForExplore` constant so that the resulting Array is `==` according to React.
* Also added a diagnostic useLogChanges() hook that can be used for future debugging.

Make sure explore doesn't reset the locations list on every Homepage render.

---

src/common/hooks/index.ts
src/common/hooks/useLogChanges.ts
src/components/Explore/Explore.tsx
src/components/NationalText/NationalText.tsx
src/components/NationalText/index.ts
src/screens/HomePage/HomePage.tsx
src/screens/HomePage/utils.ts

This builds on #3509 with some non-essential additional cleanup / optimization.
* Remove no-longer-needed `initialChartIndigenousPopulations` prop.
* Change `nationalSummaryText` to a boolean instead of a whole JSX.Element.

Some more explore cleanup which prevents it from re-rendering at all on homepage scroll.

---

src/components/Search/Homepage/HomepageSearchAutocomplete.tsx

This PR adds a condition to check whether the user clicks outside the location search dropdown on the homepage. This enables us to differentiate when to close the dropdown and when to leave it open. The dropdown should only close if the user clicks outside the dropdown.
Not sure whether this is the ideal solution but `Autocomplete` seems to generically recognize a click (whether inside or outside the dropdown) as an `onClose`. Hence the explicit check for a `placeholder` attribute, which is unique to the dropdown.

Stop input field from toggling open and closed

---

src/components/Explore/DateMarker.tsx
src/components/Explore/MultipleLocationsChart.tsx

* Have overlapping labels move upwards instead of down.
* Ensure we don't show a label for empty series (was showing up in the upper left at `(0, 0)`).
Fixes: 
* https://trello.com/c/Mgz6dgdr/1242-explore-chart-adjust-label-adjustment-function-to-go-up
* https://trello.com/c/ICgj0iIv/1322-imagepng
**Before:**
**After:**

Explore chart label tweaks.

---

src/components/Search/Homepage/HomepageSearchAutocomplete.tsx

This PR ensures the location dropdown closes when the user selects a location to navigate to.

Fix frozen location dropdown

---

src/common/hooks/useLocationSummariesForFips.tsx
src/common/location_summaries.ts

Fixes https://trello.com/c/Mu3twLii/1306-fix-issue-where-the-screen-flashes-our-bottom-banner-when-navigating-to-location-pages-from-homepage
Because we had a hook calling a hook, setting a state variable, I think we had at least 2 or 3 async roundtrips before the location page header could render, which was probably enough time for some other work to get queued onto the JS event loop, bogging things down enough that there was ~1/2 second of time where the footer rendered but not the location page header... at least for me. 🤷

Get location summaries synchronously from the main bundle if possible.

---

src/components/Analytics/amplitude.ts

[Trello](https://trello.com/c/gvTbTzxB/1291-add-current-path-to-all-amplitude-events-as-a-property) - Adds the pathname to the Amplitude events
```
{
"eventCategory": "Explore",
"eventAction": "Select",
"eventLabel": "Adding Location",
"eventValue": 2,
"path": "/us/wyoming-wy/"
}
```

send the path parameter to Amplitude

---

src/components/NavBar/MegaMenu/MegaMenu.tsx

The mobile mega menu is currently broken (links are not redirecting anywhere and menu is closing when clicking any of them). For some reason, adding the recently removed `Fade` wrapper back in fixes this bug. Pushing as a quick fix and going to investigate more

Mobile mega menu fix

---

src/components/NewLocationPage/LocationName/LocationName.stories.tsx
src/components/NewLocationPage/LocationName/LocationName.tsx
src/components/NewLocationPage/LocationName/utils.ts
src/components/SharedComponents/StyledRegionName/StyledRegionName.tsx

This PR addresses issues of location name bolding for the new location page. It implements a check to see whether a region contains a suffix which is likely to be more than one word (e.g. "City and Borough", "Census Area"). If yes, then it will bold the whole name and suffix, for the following reasons:
- There is a high chance the above examples are not the only possible multi-word suffixes out there. Better to bold the whole name and suffix than guess where the name ends and the suffix starts and potentially bold in the wrong place.
- Most multi-word suffixes have the word "and" or "census" as the second last word.
For regions where the last word is not a recognizable suffix (e.g. "District of **Columbia**"), also bold the whole name.
Implementing the above logic after reading "County …

Fix bolding of location name edge cases

---

src/cms-content/region-overrides/region-overrides.json

Blocking Manassas/Manassas-Park Vaccination Confusion.
https://trello.com/c/DfXi7QFD/1346-virginia-city-county-mismatch-leading-to-one-place-with-100

Update Region Overrides “regionOverrides”

---

src/components/LocationPage/ChartsHolder.tsx
src/screens/HomePage/HomePage.tsx

Chart/recommendations share URLs keep scrolling you back to the shared element. i.e. https://covidactnow.org/us/massachusetts-ma/chart/5 keeps jumping back to the daily new cases chart when you scroll away from it. This fix works, but there might be a better way?

Location page scroll bug

---

scripts/alert_emails/utils.ts
src/App.tsx
src/cms-content/vaccines/email-alerts.ts
src/screens/AlertUnsubscribe/AlertUnsubscribe.tsx
src/screens/Subscriptions/AfterSubscribe.tsx
src/screens/Subscriptions/AfterUnsubscribe.tsx
src/screens/Subscriptions/Subscriptions.style.tsx

* Add an "after unsubscribe" page that we'll tell Campaign Monitor to use when people unsubscribe from daily download or research rundown.
* Add an "After subscribe" page since the default campaign monitor one has a "click here to return to the site" link that just takes you back to our "after unsubscribe" page instead of the homepage.
* Make the alert unsubscribe button also go to the "after unsubscribe" page.
* Fix a bug (in a couple places) where we weren't properly escaping email addresses in links, leading to e.g. email addresses containing `+` not working properly.

Add "After unsubscribe" page to solicit people to sign up for new project announcements.

---

src/assets/theme/sizes.tsx
src/components/Compare/Compare.style.tsx
src/components/Explore/Explore.style.ts
src/components/Explore/Explore.tsx
src/components/LocationPage/ChartBlock.tsx
src/components/LocationPage/ChartsHolder.style.tsx
src/components/LocationPage/ChartsHolder.tsx
src/components/LocationPage/LocationPageBlock.style.ts
src/components/NewLocationPage/AboveTheFold/AboveTheFold.style.tsx
src/components/NewLocationPage/CountyMap/CountyMap.style.tsx
src/components/NewLocationPage/CountyMap/index.ts
src/components/Recommend/Recommend.style.tsx
src/components/Recommend/Recommend.tsx
src/components/VaccinationEligibilityBlock/VaccinationEligibilityBlock.style.ts
src/components/VaccinationEligibilityBlock/VaccinationEligibilityBlock.tsx
src/screens/HomePage/HomePage.style.tsx
src/screens/HomePage/HomePage.tsx
src/screens/LocationPage/LocationPage.tsx

Sections on the location page had inconsistent spacing--this unifies the spacing by removing top/bottom margin from inner elements (headers, footers, inner containers) and places it on the shared `LocationBlock` component. Also cleans up homepage spacing a little bit for compare+explore

Unify section spacing

---

src/components/NavBar/NavAllOtherPages/NavAllOtherPages.tsx
src/components/NavBar/NavLocationPage/NavLocationPage.tsx
src/components/NavBar/Search/Search.tsx
src/components/PageContent/PageContent.tsx
src/components/Search/SearchAutocomplete/SearchAutocomplete.stories.tsx
src/components/Search/SearchAutocomplete/SearchAutocomplete.tsx
src/screens/Donate/Donate.tsx
src/screens/HomePage/HomePage.tsx

`ClickAwayListener` was breaking the mega menu and causing it to close on mobile when attempting to click a link (and overall, on prod, if you click anywhere within the mega menu that isn't a link, the menu closes). This removes `ClickAwayListener` altogether, which was originally implemented to make sure that the mega menu and search bar were never open at the same time. Instead, we now call `setMenuOpen(false)` when clicking into the search bar.

Mega menu bug

---

src/components/ExpandableContainer/ExpandableContainer.tsx

@schamp discovered this bug (see [discussion on Slack](https://covidactnow.slack.com/archives/C01JP05V28G/p1621731934006700)), this just adds the event category to the expand/collapse action.

fix category for expand/collapse event

---

src/components/VulnerabilitiesBlock/VulnerabilitiesBlockInner.tsx

This PR restores CTAs in the vulnerability block on state and county location pages.

Restore CTAs in vulnerability block

---

src/components/PartnersSection/PartnersSection.tsx
src/screens/HomePage/Announcements/Announcements.style.tsx
src/screens/HomePage/Announcements/Announcements.tsx
src/screens/HomePage/HomePage.style.tsx
src/screens/HomePage/HomePage.tsx

Cleans up some style bugs + inconsistencies on the homepage:
- Explore and compare hit the sides of the screen (/had no padding) on desktop
- No border above announcements section
**Before (no padding around explore/compare, no border above announcements section):**
**After (incl. padding, border):**

Homepage style cleanup

---

package.json
public/admin-overrides/config.yml
src/cms-content/region-overrides/index.ts

Updates CMS schema to allow it, and override processor to handle it.
Does not combine any actual overrides though.

Support multiple comma-separated regions in overrides

---

src/common/regions/utils.ts
src/components/NavBar/NavLocationPage/NavLocationPage.tsx
src/components/NavBar/Search/Search.tsx
src/components/Search/SearchAutocomplete/SearchAutocomplete.tsx

The trello task says "state and metro" but state is a lot harder and I'm not certain it's worth the tradeoff, so this does the first half of it.
Because the items are converted to strings for searching, to make this work for states we'd need to:
1) get all counties which are part of the given state (which we don't have, so we'd have to scan all counties and filter by state) 
2) map all counties to zips by trying to look each one up by FIPS
3) store a string with all zipcodes for counties in a state
This seems like it would be costly, and the value (showing a state by zip) doesn't seem that valuable to me.

Add metro areas to zip-based search

---

src/components/AutocompleteRegions/AutocompleteRegions.style.ts
src/components/AutocompleteRegions/AutocompleteRegions.tsx
src/components/Explore/Dropdown/Dropdown.style.tsx
src/components/Explore/Explore.style.ts
src/components/Explore/Explore.tsx
src/components/Explore/ExploreChart.tsx
src/components/Explore/LocationSelector.style.ts
src/components/Explore/LocationSelector.tsx
src/components/Explore/MultipleLocationsChart.tsx
src/components/Explore/SingleLocationChart.tsx
src/components/Explore/utils.ts
src/components/RegionItem/RegionItemSkeleton.tsx
src/screens/HomePage/HomePage.style.tsx
src/screens/internal/ShareImage/ExploreChartExportImage.tsx
src/screens/internal/ShareImage/ExploreChartImage.tsx

- Sets maxY of percent vaccinated charts to 100%
- Makes location list in button semicolon separated instead of comma separated
- Fixes location selector modal (was opening upward on mobile and going off screen--now always opens downward)
- Misc. style edits
- Replaces uses of `gap` property with margins, as `gap` doesnt seem to work on phones

Explore feedback items

---

src/components/SharedComponents/StyledRegionName/StyledRegionName.tsx

Adds comma between county name and state code in searchbar menu ([explanation in trello](https://trello.com/c/OScl5U0A/1404-update-format-of-location-names-in-search-dropdown-menu-items))
Before: 
After:

Search location name format edit

---

src/components/LocationPage/ShareButtons.tsx

Previously, social icon sizes in the share button group for each chart weren't aligned with the rest of the site, as they were hardcoded. This PR aligns these icon sizes by implementing a mobile breakpoint, like how it's done with other share buttons throughout the site.

Align social icon sizes

---

src/common/hooks/useGeolocation.ts
src/components/RegionItem/RegionItem.style.tsx

This PR fixes the box shadow on geolocated cards on the homepage by ensuring there is enough margin around each card for the shadow to show. Additional notes:
- This PR also aligns box shadow styling to match the search bar.
- Ignore `useGeolocation.ts` for now. This will be reset back to its original version once the PR is approved.

Fix box shadow on geolocated cards

---

src/components/NewLocationPage/ChartTabs/ChartTab.stories.tsx
src/components/NewLocationPage/ChartTabs/ChartTab.style.tsx
src/components/NewLocationPage/ChartTabs/ChartTab.tsx
src/components/NewLocationPage/ChartTabs/ChartTabs.tsx

This PR creates standardized chart tabs. Some curious notes below:
- Some metric names don't seem to match what's on Figma 🤔 (e.g. vaccination metrics). This PR currently uses the same logic as `SummaryStat` to get the metric name and metric sub-label. If it's necessary that the metric names must match what's on Figma exactly, we may need to build in additional logic?
- This PR assumes both click and hover behaviour will trigger the metric name to be bolded and the bottom border to appear.

Create chart tabs

---

src/components/Charts/Charts.style.ts

Use the theme background color for chart labels in vaccination chart.
Before:
After:

Fix labels in vaccine chart share images.

---

src/components/Compare/CompareTableRow.tsx

This PR fixes the issue of the browser back button needing to be clicked twice to navigate back to the homepage (after the user clicks on a location on the compare table).

Ensure location URL doesn't get added to history stack twice

---

src/components/AutocompleteRegions/AutocompleteRegions.style.ts

This PR fixes the issue of the screen freezing after the user adds a new location on the explore chart. This only happens on mobile. Adjusting the font size to be at least 16 px / 1 rem prevents the screen from freezing.
Some forum discussion regarding the issue: https://stackoverflow.com/questions/2989263/disable-auto-zoom-in-input-text-tag-safari-on-iphone

Investigate frozen zoom on location input

---

scripts/update_location_summaries.ts
src/common/models/Projection.ts
src/common/utils/model.ts

Turn off caching of fetched Projections, don't retain actualTimeseries when we
don't need it, and only process one state worth of counties at a time.

Make update_location_summaries use less memory.

---

src/components/Explore/Explore.tsx
src/components/Explore/utils.ts

Single series, not normalized:
(menu):
Multiple series, normalized:
(menu):
This appears to be the only change needed to implement this, but if I'm missing something, please call it out and I'll add it.

Add 'per 100K' to the chart metric labels

---

src/components/Map/Legend.style.ts

fix wrap on legend

---

src/components/Explore/Explore.tsx

Location selection currently resets to `initialLocations` whenever a new explore metric is selected. This fixes + cleans up dependencies

Fix explore locations bug

---

src/common/utils/compare.ts
src/components/Compare/Compare.style.tsx
src/components/Compare/CompareTable.tsx
src/components/Compare/Filters.style.tsx
src/components/Compare/Filters.tsx
src/components/NewLocationPage/CompareLocationTabs/CompareLocationTabs.stories.tsx
src/components/NewLocationPage/CompareLocationTabs/CompareLocationTabs.style.tsx
src/components/NewLocationPage/CompareLocationTabs/CompareLocationTabs.tsx

This PR replaces the compare table sliders with location button group. Some notes:
- Once merged, some cleanup is required to get rid of no longer used slider code.
- Styling to match the appearance to Figma will be completed in a follow-up PR.

Replace compare table sliders

---

src/components/Explore/Legend.tsx

We are currently rendering the legend even if theres no data/no chart -- this fixes

Hide explore legend if no data

---

src/common/utils/makeChartShareQuote.ts
src/components/Charts/Redesign/Groupings.tsx
src/components/Charts/Redesign/NewChartBlock.tsx
src/components/Dialogs/utils.tsx
src/components/LocationPage/ChartsHolder.tsx
src/components/LocationPage/ShareButtons.tsx
src/components/NewLocationPage/ChartFooter/AddedMetricChartFooter.tsx
src/components/NewLocationPage/ChartFooter/ChartFooter.tsx
src/components/NewLocationPage/ChartFooter/MetricChartFooter.tsx
src/components/NewLocationPage/ChartFooter/utils.ts

i put this in a pr/branch separate of the [feature](https://github.com/covid-projections/covid-projections/pull/3817) because im not sure yet if this is the best solution
also includes some fixing of the share functionality (share quotes working for all charts, page-level share links (rather than chart level), page-level share images for newly added charts (still shares chart image for original key metric charts))

Scrolling to chart when clicking summary stat

---

.storybook/main.js

I noticed the build was hanging for a long time on "70% - sealing React Docgen Typescript Plugin" so I did some googling and found https://github.com/storybookjs/storybook/issues/12585#issuecomment-701292052 which has a workaround, though it breaks the "Docs" tab in StoryBook. 😞

Speed up storybook builds (From ~10s to ~2.5s).

---

src/components/RegionItem/RegionItem.style.tsx

Homepage region items' circle icon looks a bit off. This fixes
Before-
After-

Fix circle icon alignment

---

src/components/USMap/VaccineTooltip/VaccineTooltip.stories.tsx
src/components/USMap/VaccineTooltip/VaccineTooltip.style.ts
src/components/USMap/VaccineTooltip/VaccineTooltip.tsx

Adds a VaccineTooltip component for use by the vaccine map. Depends on https://github.com/covid-projections/covid-projections/pull/3851.  Can't be plumbed into the map until https://github.com/covid-projections/covid-projections/pull/3856 lands.  
Desktop version:
Mobile version:
Demo with map and tooltip integrated: https://covid-projections-git-mikelehen-vaccine-tooltip-covidactnow.vercel.app/?s=1957873

VaccineTooltip component.

---

src/components/Charts/ChartVaccinations.tsx

Tiny change to ensure "Fully vaccinated" doesn't wrap on the vaccination chart tooltip.

Increase vaccination chart tooltip width

---

src/components/Compare/CompareTable.tsx

Tiny change to update the compare table title to "Counties" on the location page.

Change compare table title on location page

---

src/components/HorizontalThermometer/VaccinationsThermometer/VaccinationsThermometer.tsx
src/components/ShareBlock/ShareBlock.tsx
src/components/SocialLocationPreview/Legend.style.ts
src/components/SocialLocationPreview/Legend.tsx
src/components/SocialLocationPreview/SocialLocationPreviewMap.tsx

I've left the risk map stuff around in case we want to switch back (I'm a bit nervous about switching people's embeds over without them opting-in).  Had to tweak css around a bit to get a legend heading in and looking decent.
Share card on homepage:
Share image:
Embed:

Switch share image / embeds to vaccination map.

---

scripts/alert_emails/template.html
src/common/metrics/vaccinations.tsx
src/components/LocationPage/ChartsHolder.tsx

* Remove vaccine eligibility component (per Igor).
* Add copy under vaccine chart that 12+ are eligible (and remove old distributed % text that's no longer relevant).
* Add "Note that risk is reduce for vaccinated indivudals." to risk alert template.
New risk alert email looks like this (see new text under thermometer image):

Remove vaccine eligibility component and minor copy tweaks.

---

src/screens/About/About.tsx

This PR moves the "Our climate work" section higher up on the page, immediately below "Our COVID work" section.

Reorder about sections

---

src/assets/theme/megaMenu.ts
src/cms-content/footer/footer.json
src/cms-content/footer/index.ts
src/components/MenuContent/AboutUsSection.tsx
src/components/MenuContent/LearnSection.tsx
src/components/MenuContent/Menu.style.tsx
src/components/MenuContent/MenuContent.tsx

This PR adjusts the content under the FAQ section of the mega-menu/footer. Specifically,
- Replace three shuffled FAQ questions with a paragraph about the learn section.
- Replace the "Vaccine FAQs" button with a "Learn more" button which directs the user to the "Learn" page.
- Clean up no longer needed code.
Note: Added comments throughout the PR for clarity.

Update learn menu and footer copy

---

src/components/MenuContent/LearnSection.tsx

This PR changes the heading of the Learn section in the mega-menu/footer from "Learn" to "Educational Resources".

Change learn heading to educational resources

---

src/components/NavBar/NavBar.style.ts

We accidentally set up our grid columns so that the search bar grid cell overlapped some of the other grid cells, which apparently worked fine until Chrome 93. But with Chrome 93, the search bar div ended up on top of the other elements and e.g. you couldn't click the back arrow / logo anymore.
https://trello.com/c/WLfmqTXd/244-can-site-back-arrow-stopped-working-in-chrome-93

Fix NavBar grid so that back arrow, etc. work on Chrome 93.

---

src/components/NavBar/NavBar.style.ts

We set up our grid columns so that the search bar grid cell overlapped the other grid cells to get the search bar perfectly centered.  This apparently worked fine until Chrome 93. But with Chrome 93, the search bar div ended up on top of the other elements and e.g. you couldn't click the back arrow / logo anymore.  I'm changing it so the search bar doesn't overlap the other grid cells so that there's no longer any z-order risk.

Deploy NavBar fix.

---

src/common/colors.ts

https://trello.com/c/ByaUenuI/292-can-round-vs-floor-inconsistency-in-vx-color

Round vaccination % before calculating color to make it match map / compare table.

---

src/common/colors.ts
src/components/HorizontalThermometer/VaccinationsThermometer/VaccinationsThermometer.tsx

We are updating the vaccination color thresholds now that more states (and Puerto Rico) are open 80%.
As part of that update, we are standardizing how we round/truncate percentages to make them the same.

Update Vaccination Color Thresholds

---

src/common/metrics/case_density.tsx
src/common/metrics/case_growth.tsx
src/common/metrics/hospitalizations.tsx
src/common/metrics/interfaces.ts
src/common/metrics/positive_rate.tsx
src/common/metrics/vaccinations.tsx

There was a TODO to delete renderDisclaimer() in src/common/metrics/interfaces.ts and indeed it is not used.  So deleting it to avoid confusion.

Remove unused renderDisclaimer() method per TODO.

---

src/components/Charts/MetricChart.tsx
src/components/NewLocationPage/ChartFooter/MetricChartFooter.tsx

Before this change, disclaimers only showed up if the metric wasn't blocked (in the metric footer). We also didn't support markdown (so couldn't embed links) in disclaimers.
**Before:**
**After:**

Show disclaimers for blocked metrics and enable markdown.

---

src/components/Charts/utils.ts
src/components/Explore/utils.ts

- Adjust x axis so the labels don't squish together.
- Adjust y axis so each label isn't too long.
Before:
After:

Adjust axis ticks

---

src/components/USMap/VaccineTooltip/VaccineTooltip.tsx
src/components/VaccineProgressBar/VaccineProgressBar.tsx

When we block data, our vaccination map will display 0% vaccination, which is incorrect. This PR
- Changes "0%" to "--" when there is no data.
- Greys out the vaccination progress bar when there is no data.
Before:
After:

Display -- instead of 0% in map tooltip

---

src/components/Explore/utils.ts

Fixes Y-axis for ICU hospitalizations so the numbers don't get truncated.
Before:
After:

ICU Y-axis fix

---

src/components/Charts/utils.ts
src/components/Explore/SingleLocationChart.tsx
src/components/Explore/utils.ts

The initial [fix](https://github.com/covid-projections/covid-projections/pull/4977) to fully display Y-axis labels ended up introducing a bug to small numbers for ICU hospitalization metric.
Attempts to fix:
- Tried playing around with `text` and `tspan` components within the `AxisLeft` component, but that messes with the rest of the graph as they're all nested in a generated SVG.
- Explored adding additional logic to display decimal depending on the range of values, but that seems pretty complicated for a white space fix.
Ended up just adjusting the left margin to accommodate the Y-axis labels and getting rid of white space on the X-axis.
Before:
After:

Fix decimal values for ICU metric

---

src/components/NewLocationPage/LocationName/LocationName.tsx

This reverts commit c1d0b28be1a4615394d37ff3c3183c895d85ceae.
I assume this is safe to remove now?

Revert "Add holiday data update notice. (#4853)"

---

src/cms-content/region-overrides/index.ts

This fixes the Idaho disclaimer.  We were accidentally looking up a different date-based override for Idaho rather than the block w/ disclaimer one.
The frontend doesn't do anything with date-restricted overrides so we can just ignore them.

Fix looking up of region overrides to ignore overrides with a start/end date.

---

src/components/Compare/columns.tsx

I think Mime copy/pasted the CCVI font size.  This fixes it to be consistent with the other columns.

Fix hospitalizations per 100k compare column font size.

---

scripts/update_location_summaries.ts
src/assets/data/site-summary.json
src/common/models/Projection.ts
src/components/Explore/Explore.tsx
src/components/NationalText/utils.tsx
src/screens/HomePage/HomePage.tsx

This PR does the following:
- Make hospitalizations per 100k the default metric in Trends section on the homepage.
- Add USA to the default view in Trends section.
For testing:
1. Use node v12! Otherwise, the generated file in the next step may be too large and the command will likely fail.
2. Run `yarn update-location-summaries`.
3. Test site as per usual.
Note: `site-summary.json` is only included in this PR for testing purposes. This will be removed once this PR is approved and ready to merge.

Make hospitalizations default trend

---

src/api/index.ts
src/screens/internal/CompareSnapshots/SnapshotVersions.tsx

We removed the covid-data-public repo sha from the `version.json` file in [covid-data-model](https://github.com/covid-projections/covid-data-model/pull/1229/files#diff-d31ce0453051853c17ba2a5225b3d1bfab548e095bab0967d6acfd1b3ce1b35dL164), breaking the compare tool.
This removes the covid-data-public data from the compare tool to match those updates.

Remove covid-data-public version from Snapshot Compare

---

src/screens/HomePage/HomePage.tsx

Currently USA fips code is added multiple times to the list feeding the Explore chart. This PR prevents this by ensuring USA fips code is only added if it doesn't exist in the list yet.
Before:
After:

Fix repetitive USA labels in Explore

---

src/cms-content/recommendations/index.ts
src/cms-content/recommendations/recommendations-main.json
src/common/utils/recommend.ts
src/components/Recommend/Recommend.tsx

This PR gets rid of icons as a separated list from recommendations, and add each icon to a recommendation item instead.

Move icons to be a part of recommendation

---

src/common/utils/recommend.ts
src/components/LocationPage/Recommendations.tsx

Update recommendations ordering and remove NYT source as per [request](https://actnowcoalition.slack.com/archives/C01DNUNLC56/p1646794084730719).

Update recommendations ordering

---

src/components/NewLocationPage/RiskThermometer/DesktopThermometer.tsx
src/components/NewLocationPage/RiskThermometer/MobileThermometer.tsx
src/components/NewLocationPage/RiskThermometer/RiskThermometer.style.tsx

Updates the above the fold thermometer to show only LOW, MEDIUM and HIGH levels.
**Before**
**After**

update above the fold thermometer

---

src/common/metrics/admissions_per_100k.tsx
src/common/metrics/weekly_new_cases_per_100k.tsx

`hospitalizations_per_100k` -> `admissions_per_100k`
`weekly_cases_per_100k` -> `weekly_new_cases_per_100k`

Rename metric files to more closely match API

---

package.json
scripts/alert_emails/firestore.ts
scripts/alert_emails_report/generate-report.ts
scripts/alert_emails_report/generate-subscriber-emails-file.ts

Create a script to export alert subscriber emails to a text file. Some notes below:
- Creating a separate script called `generate-subscriber-emails-file` in case we need to do something like this again in the future.
- Exporting to a text file instead of a CSV, since we only need one column.
- Currently outputting the text file to the repo's main folder. If there is somewhere better in the repo to output the file, let me know :)

Export subscribers emails to text file

---

scripts/alert_emails/send-test-email.ts
scripts/alert_emails/template.html
scripts/alert_emails/utils.ts

First pass at updating the email alerts copy and images (see [CAN 8.2 COPY](https://docs.google.com/document/d/1pITjM1gctulpwyqez5SFrQLFIYO4vndJArDjFPnVMG4/edit#heading=h.ny2rjkbn6e9s)). Screenshot of the email:
- Note that this email is generated with mocked data, so the date and current levels won't match current date/level.
- Also, Fai's PR updates the subject line and alt-text of the screenshot

update email alert body (1st pass)

---

scripts/alert_emails/utils.ts
src/common/metrics/admissions_per_100k.tsx
src/common/metrics/location_summary.tsx
src/common/metrics/ratio_beds_with_covid_patients.tsx
src/components/Charts/Groupings.tsx
src/components/EmailAlertsFooter/EmailAlertsFooter.tsx
src/components/Header/HomePageHeader.tsx
src/components/LocationPage/ChartsHolder.tsx
src/screens/HomePage/HomePage.tsx

First pass at updating some content for CAN-82, based on [this doc](https://docs.google.com/document/d/1pITjM1gctulpwyqez5SFrQLFIYO4vndJArDjFPnVMG4/edit#). I avoided updating the chart sections for the location page for now since they don't seem to be finalized yet.

CAN 8.2 content update first pass

---

src/screens/Learn/MetricExplainer/MetricExplainer.tsx

Fixes metric explainers page, which was crashing because introSection[0].questions was undefined

Fix learn/metric-explainers error

---

src/components/Explore/Explore.tsx
src/components/Explore/interfaces.ts
src/components/Explore/utils.ts
src/components/LocationPage/ChartsHolder.tsx

- Remove daily cases and deaths from Trends.
- Select "Weekly new cases per 100k" by default in Trends.
As per these two cards:
- https://trello.com/c/XaHrtmmV/549-trends-remove-daily-new-cases-daily-new-deaths
- https://trello.com/c/toG5398D/554-update-trends-add-weekly-new-deaths-minor-updates

Remove cases and deaths from trends

---

.github/workflows/send-alert-emails.yml
scripts/alert_emails/generate_daily_alerts.ts

Tested locally by running `yarn generate-daily-alerts 3207 true` and inspecting the output at scripts/alert_emails/alerts.jso to see that all locations are included and have an oldLevel of 4 (UNKNOWN).
We should further validate before actually sending email alerts by:
1. Doing a dev or staging run with the new option set to true.
2. Doing a prod dry-run with the new option set to true (this will tell us how many emails will be sent, etc.).

Wire up alert emails option so we can send them to everybody.

---

src/common/metrics/admissions_per_100k.tsx
src/common/metrics/hospitalizations.tsx
src/common/metrics/ratio_beds_with_covid_patients.tsx
src/common/models/Projection.ts
src/components/NewLocationPage/ChartFooter/utils.ts

And drive-by formatting to capitalize Health Service Area to match [Copy Doc](https://docs.google.com/document/d/1pITjM1gctulpwyqez5SFrQLFIYO4vndJArDjFPnVMG4/edit#). 
Continuing to use existing HSA name copy/style until copy updates are confirmed (see [slack thread](https://actnowcoalition.slack.com/archives/C02UQBS8X8W/p1649724516819879) for context)

Fix Weekly Covid Admissions chart copy value and update hospital chart copy for counties

---

src/common/metrics/admissions_per_100k.tsx

Reverse engineer actual weekly admissions for county-level locations (HSA-level data) to fix discrepancies between CDC metrics and HHS data.

Reverse engineer weekly admissions actual for counties

---

src/components/Explore/interfaces.ts
src/components/Explore/utils.ts
src/components/NationalText/utils.tsx

Small tweak to the national text under "Trends" on the homepage and re-ordering (again 😑 ) of the dropdown items in the Trends chart cos I re-ordered them based on variable names in our code instead of the metric names the user sees. Sorry!

Trends wording tweaks

---

src/common/metrics/admissions_per_100k.tsx

Per copy doc: 
```
Add “new” to copy: 
“Over the last week, [STATE/METRO/HSA] had [X] new COVID hospital admissions ([X] for every 100,000 residents). “
```

Add 'new' to Weekly Covid Admissions chart copy

---

src/components/DataCoverageTable/DataCoverageTable.tsx

This PR addresses https://trello.com/c/xehsRNjy/567-update-data-api-page-coverage-section
The `yarn update-data-coverage-summary` script already calculated coverage for these new metrics, so they just needed to be added to the DataCoverageTable component

Add new metrics to data coverage table

---

src/components/Explore/Explore.tsx

Per [Launch Checklist](https://www.dropbox.com/scl/fi/u23ob7sqtyqyo3e9n37bx/CAN-8.2-CDC%2B%2B-Launch-Checklist.paper?dl=0&oref=e&rlkey=ebmgo5rcj5i3mesd8bkeglac3):
```
Revert trends default to hospitalizations per 100k. 
Ideally we’d use weekly admissions, but not enough historical data.
```
If we end up using historical HHS data to backfill the hospital metrics we may want to update this again to be weekly covid admissions.

Revert trends default to hospitalizations per 100k

---

src/components/Dialogs/utils.tsx

Fixes item in launch list:
> How to get the “About the data” tooltip “Learn more” buttons to go to correct place in explainers. Not working for the 3 community level metrics.

Fix hash links

---

src/components/Header/HomePageHeader.tsx
src/components/NewLocationPage/LocationOverview/LocationOverview.style.tsx
src/components/NewLocationPage/SummaryStat/DesktopSummaryStat.tsx
src/components/NewLocationPage/SummaryStat/SummaryStat.style.tsx
src/components/SocialLocationPreview/SocialLocationPreview.style.tsx
src/components/SocialLocationPreview/SocialLocationPreview.tsx
src/components/SocialLocationPreview/SocialLocationPreviewMap.tsx
src/screens/HomePage/HomePage.tsx
src/screens/LocationPage/utils.ts

- Edits alignments/spacing of summary stats per [these figma mocks](https://www.figma.com/file/QPrDUez0XG8Be0UVW8qcm7/8.2%2B%2B?node-id=127%3A4032)
- Changes homepage h1 (and therefore meta tags, page title, social map header) per this item in the launch doc:

New homepage H1 + summary stat alignment edit

---

src/components/Charts/ChartAdmissionsPer100k.tsx

Updating the weekly admissions chart. This chart is an evolution from the old hospitalizations chart. In that chart, the "Low" level was too narrow, so we made the "Low" zone a bit taller by starting the chart at -6 instead of zero. This PR removes that custom logic.
**Before**
**After**

adjust y-axis of admissions chart

---

src/common/utils/provenance.tsx

Allows for multiple sources in `About this data` dialog
On county and metro pages, adds second metric for `RATIO_BEDS_WITH_COVID` and `ADMISSIONS_PER_100K` under `Data source` section

Multiple sources in 'about this data' dialog

---

src/components/Banner/Can82Banner.tsx
src/components/Search/utils.ts

Colors indicator by community risk level instead of vaccinations, per this item in launch doc-

Menu items icon color + banner link

---

src/components/NewLocationPage/LocationOverview/LocationOverview.style.tsx
src/components/NewLocationPage/SummaryStat/MobileSummaryStat.tsx

I edited the placement of the chevron icon but didn't make the same edit in its hover state, so hovering a summary stat makes the chevron animate diagonally (see here by hovering a summary stat). This pr fixes

Summary stat hover fix

---

src/common/location_summaries.ts
src/common/models/Projections.ts

Should fix crash Sean noticed (see https://github.com/covid-projections/covid-projections/runs/6068853288?check_suite_focus=true).
It also just removes extra stuff we don't need from the summaries file which will speed up page loads.
Run with this branch: https://github.com/covid-projections/covid-projections/runs/6068807801?check_suite_focus=true

Remove extra fields from summaries file.

---

src/common/models/Projections.ts

Metric tabs were empty/missing due to metrics being removed from `summaries.json` file during cleanup. 
before (prod):
after:

Add percent positivity and infection rate to `summaries.json` file

---

.github/workflows/update-snapshot.yml

Fixes out of memory issue reintroduced in #5619 for the snapshot updater action
Solution from https://stackoverflow.com/questions/53230823/fatal-error-ineffective-mark-compacts-near-heap-limit-allocation-failed-javas

Increase `--max-old-space-size` to fix " Update to new data snapshot" action

---

scripts/alert_emails_report/generate-subscriber-emails-file.ts

Minor updates to the `scripts/alert_emails_report/generate-subscriber-emails-file.ts` script. 
- Remove `lodash` import (it wasn't being used)  
- I filter out invalid emails when generating the list (the `isValidEmail` function is not very robust, but better than nothing)
- The emails are added in rows instead of columns (separating them by newlines `\n` instead of comma `,`)
- Added instructions on how to run it.
To test, make sure that you have a `google-service-account.json` file under `scripts/common/firebase` for the `covidactnow-dev` environment and then run
```sh
yarn generate-subscriber-emails-file
``` 
This will generate the `subscriber-emails.csv` file, which should have one email per line.

update script to generate the list of alert subscribers

---

src/screens/internal/ShareImage/ChartShareImage.style.ts

Updating the style of the title for the share cards to ensure that the title doesn't overlap with itself when shown in 2 lines.
[Before](https://covidactnow.org/internal/share-image/states/washington-wa/chart/9) / [After](https://covid-projections-git-pablo-share-images-title-fix-covidactnow.vercel.app/internal/share-image/states/washington-wa/chart/9)
[Before](https://covidactnow.org/internal/share-image/states/washington-wa/chart/8) / [After](https://covid-projections-git-pablo-share-images-title-fix-covidactnow.vercel.app/internal/share-image/states/washington-wa/chart/8)
[Before](https://covidactnow.org/internal/share-image/states/washington-wa/chart/7) / [After](https://covid-projections-git-pablo-share-images-title-fix-covidactnow.vercel.app/internal/share-image/states/washington-wa/ …

adjust style of title (metric share image)

---

src/components/ShareBlock/ShareBlock.style.tsx
src/screens/Donate/Donate.tsx

I think `<ShareModelBlock>` was restored and misplaced, where the CSS of other containing components messed with the arrow appearance and caused the whole get alerts block to not be centered.
Before:
After:

Fix dropdown arrow bug

---

src/components/RegionItem/RegionItem.tsx

Update geolocated cards on the homepage to display community level instead of vaccination metric, as per [card](https://trello.com/c/OEUhP0m1/598-geolocation-cards-should-probably-show-community-level-color-not-vaccine).

Update geolocated cards

---

src/components/Charts/Groupings.tsx
src/components/NewLocationPage/ChartTabs/ChartTab.tsx

Add color dot indicators to chart tabs, as per [card](https://trello.com/c/yD9uJhYw/606-add-color-dot-indicators-to-community-levels-section).

Add color dot indicators to chart tabs

---

src/components/Charts/ChartRatioBedsWithCovidPatients.tsx

Addresses https://trello.com/c/qJQcto7M/612-optimize-the-y-axis-limit-to-show-only-part-of-the-high-band-in-community-level-components
Limits the height of the Patients w/ Covid chart to the maximum value plus 5% extra padding. The ticket is a little vague on whether the limit should be dynamic or fixed (e.g. something like the old percent positivity chart that capped at 40%) so I can rework this if need be.

Optimize the y-axis limit of Patients w/ Covid chart

---

src/screens/Learn/MetricExplainer/MetricExplainer.tsx

Moved thermometer block up in the metric explainer intro. This matches the content flow of other metrics in the metric explainer page.
**Note:** The [card](https://trello.com/c/5UN69VKf/614-move-position-of-thermometer-for-community-level-explainer-above-the-final-paragraph) says to only move the thermometer up by one paragraph. This is a bit tricky since that paragraph is part of one big CMS text block. To separate that paragraph, we might need to isolate it from the rest of the section intro (i.e. text beginning with "A state or county’s community level..." and text beginning with "Covid Act Now’s former COVID risk framework..." would be separate CMS sections), which I'm not sure is worth the effort.

Move thermometer block up in explainer intro

---

src/components/Explore/Explore.tsx
src/screens/internal/ShareImage/ExploreChartExportImage.tsx
src/screens/internal/ShareImage/ExploreChartImage.tsx

Currently in the Trends section, when the user selects a non-default time period and click share, the share link will save the selected metric and location/s, but not time period. This PR adds time period to shared parameters so the shared link will "remember" the selected time period too.
Addresses this [card](https://trello.com/c/DRB2OtuR/609-trends-sharing-doesnt-respect-past-of-days-setting).

Add time period to shared component params

---

src/screens/Learn/MetricExplainer/MetricExplainer.tsx

Turns out we don't need move the thermometer up. Mikayla just separated the copy into two sections in the CMS and that enabled the thermometer to sit where it ideally should.
Reverts covid-projections/covid-projections#5656

Revert "Move thermometer block up in explainer intro"

---

src/components/Charts/ChartBlock.tsx
src/components/Charts/Groupings.tsx
src/components/LocationPage/ChartsHolder.tsx

Trello: https://trello.com/c/VJ1QU320/603-share-links-dont-navigate-the-user-to-the-corresponding-metric
For QA:
[Not a share URL](https://covid-projections-git-casulin-chart-scrolling-covidactnow.vercel.app/us/new_york-ny/?s=32582081)
[Invalid share URL](https://covid-projections-git-casulin-chart-scrolling-covidactnow.vercel.app/us/new_york-ny/chart/17?s=32582081)
[Weekly new cases](https://covid-projections-git-casulin-chart-scrolling-covidactnow.vercel.app/us/new_york-ny/chart/9?s=32582081)
[Weekly covid admissions](https://covid-projections-git-casulin-chart-scrolling-covidactnow.vercel.app/us/new_york-ny/chart/8?s=32582081)
[Patients w/ covid](https://covid-projections-git-casulin-chart-scrolling-covidactnow.vercel.app/us/new_york-ny/chart/7?s=32582081)
[Daily new …

Fix share link scrolling functionality 

---

src/common/hooks/index.ts
src/common/hooks/useDefaultTrendsPeriod.ts
src/components/Explore/Explore.tsx

Trello: https://trello.com/c/7COWZXOf/613-change-the-trend-defaults-on-mobile-to-180-days
Defaults trends view to 180-days on mobile

Trends default time period update

---

src/App.tsx
src/common/metric.tsx
src/screens/internal/Anomalies/Anomalies.tsx
src/screens/internal/Anomalies/AnomaliesSelector.tsx
src/screens/internal/Anomalies/utils.ts
src/screens/internal/CompareSnapshots/OptionsSelector.tsx
src/screens/internal/CompareSnapshots/SnapshotVersions.tsx

Creates an internal page for viewing county-level data anomalies.
Preview: https://covid-projections-n9nq7lcr5-covidactnow.vercel.app/internal/anomalies
This is helpful for tracking down anomalies or looking at what anomalies exist for a specific location, but it isn't so helpful for identifying what anomalies were introduced in a given snapshot. We might want to extend this to have an option to list all of the anomalies for a given metric in reverse chronological order, or something similar.

Add internal county data anomaly tracker

---

src/components/Charts/Groupings.tsx

As a result of implementing abbreviated metric names above the fold (in summary stats) ([in this PR](https://github.com/covid-projections/covid-projections/commit/888ed6e51e6aa1e8ed766d0b878c238ff0bb8572#diff-ad0bea4234c14136dcbf94867550df9b205da399f1c021520778035df7b28b1aR20)), metric names in chart tabs were updated -- unintentionally. This reverts the chart tabs to their original metric name copy
So- abbreviated names remain implemented in summary stats (cases, patients, admissions), but the longer names are used in the corresponding chart tabs
Before:
After:

Fix chart tab renaming bug

---

src/components/NewLocationPage/LocationName/LocationName.style.tsx
src/components/NewLocationPage/LocationName/LocationName.tsx

Trello: https://trello.com/c/CfyHZ21J/631-add-hyperlink-to-state-abbreviation
[Example](https://covid-projections-git-casulin-hyperlink-statecode-covidactnow.vercel.app/us/new_york-ny/county/kings_county/?s=33202135)

Hyperlink state code in county location page header

---

public/index.html

This PR adds a new GA4 property to our Google Analytics, which starts tracking our user data along side our UA property. Note that UA is currently not affected whatsoever. So our current tracking data is not affected.
This is part of our migration from UA to GA4, which involves the following:
- Create a new GA4 property from the UA property, as per instructions in [this documentation](https://support.google.com/analytics/answer/10312255).
- Add the property to our code in the same manner as what we implemented for Google Ads [here](https://github.com/covid-projections/covid-projections/blob/a146d7166c8cbc8956fcf0bf176bc2d82b31c634/public/index.html#L142-L154), as per "tagging instructions" (found through Google Analytics --> Admin --> Data Steams --> CoVidActNow - G4 --> Tagging …

Add CAN GA4 property

---

src/components/LocationPage/ChartsHolder.tsx
src/components/NewLocationPage/SparkLineBlock/utils.ts

When clicking spark lines, the page now scrolls to the corresponding metric's chart instead of to explore.
**Test on mobile** (the spark line block is now an independent component only on mobile -- desktop combines spark lines into summary stats)

Re-route sparkline click

---

package.json
src/components/Analytics/gtag.ts
src/components/Analytics/utils.ts
src/components/SharedComponents/ShareButtons.tsx
src/screens/AlertUnsubscribe/AlertUnsubscribe.tsx
yarn.lock

This PR adds event tracking to our new GA4 property. This change _does not_ affect out current event tracking whatsoever. It merely tracks events _alongside_ our current tracking in UA. Once merged, we'll be able to compare numbers between UA and GA4.
Data models are different between UA and GA4. While UA tracks activities with event action, event category, event label, and event value, these do not translate directly to GA4. Instead, "event action" in UA is _automatically_ converted to "event name" in GA4, and the rest need to be translated to custom parameters in GA4. These custom parameters can be created through the UI, as done so [here](https://analytics.google.com/analytics/web/#/p313668181/customdefinitions/hub?params=_u..nav%3Dmaui%26_u..pageSize%3D25). Then the code needs to be …

Add event tracking to GA4

---

.github/workflows/chromatic.yml

Pull requests created by Dependabot are treated as if they were opened from a repository fork, which means that organization or repository secrets are not accessible by the workflows triggered by the PR. See https://github.com/covid-projections/covid-projections/pull/5894 for an example.
This PR disables the Chromatic workflow (which needs the `CHROMATIC_PROJECT_TOKEN` to publish to Chromatic) to prevent PRs created by Dependabot to fail the Chromatic check.
Once this is merged we can rebase https://github.com/covid-projections/covid-projections/pull/5894 and check that the Chromatic workflow is actually skipped.
See https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/

Skip chromatic for dependabot PRs

---

src/common/models/Projection.ts

Fixes https://trello.com/c/A4Gbquur/669-daily-new-cases-in-explore-is-inconsistent-with-weekly-new-cases-per-100k-metric-doesnt-handle-irregular-reporting-as-well
Rather than calculating `smoothedDailyCases` directly from `rawDailyCases`, we base it on the `caseDensity` metric which benefits from various smoothing done on the backend.
This is most notable for Florida explore metrics where the biweekly reporting causes issues.
**Before:**
**After:**

Fix smoothed cases in explore to match official case metric from backend.

---

src/components/Analytics/utils.ts

This PR ensures each word for the event label is capitalized, matching how event labels were recorded in UA. Also, since GA4 is now automatically sharing data with UA, we no longer need to send data to both.

Fix casing for event labels

---

.github/workflows/chromatic.yml

We don't really need to publish Chromatic for daily deploys. I also updated the `actions/checkout` action to v3 (they are compatible).

Skip chromatic daily deploys

---

src/components/Analytics/utils.ts

Currently buttons in our footer are broken due to the new way our event labels are parsed. Historically, we allowed event labels to be empty (by using `words` in `toTitleCase` function, which can return an empty string). But now that we're _not_ using `words` and are parsing event labels by simpler string manipulation (rationale was to ensure UA and GA4 event labels match up), our new `toTitleCaseWithSpecialCharacters` function was not allowing `undefined` as an argument although it should have. This causes our site to throw an error when the user clicks on a button inside the footer (where event labels are `undefined`).
This PR fixes the footer button bug by allowing `undefined` to be passed to `toTitleCaseWithSpecialCharacters`.

Fix footer button bug

---

src/common/utils/provenance.tsx

Updates "About this data" sources for state-level hospitalization metrics to point to the source HHS dataset (instead of the CDC data tracker, which is not technically used for state-level data)

Update state hospital metric provenance

---

scripts/alert_emails/template.html
scripts/alert_emails/utils.ts

Establish a way to split alert email recipients into two groups. So we can send one group content linking to the GiveButter donation page and the other group content linking to the GiveMomentum donation page.

Split email recipient groups

---

scripts/alert_emails/template.html

Currently the donate link in our alert email is too wide on smaller screen sizes and would wrap. This PR adjusts the font size for smaller screen sizes so the button would not wrap.
**Note:** Since handlebars aren't aware of user screen sizes and since styling in `template.html` is inline, adding a media tag to inline styling is challenging (if even possible, [more info](https://stackoverflow.com/questions/9808233/is-it-possible-to-put-css-media-rules-inline)). So I added the style tag in the document head to handle different screen sizes.
Before:
After:

Fix donate button bug in alert email

---

.github/workflows/ci.yml

The CI threw the following error due to Ubuntu 18 being deprecated:
See this run https://github.com/covid-projections/covid-projections/actions/runs/2904542192 for more context

Bump CI github action runner from 18.04 -> 20.04

---

src/cms-content/recommendations/recommendations-main.json

Federal free tests program is suspended due to lack of funding. I'm updating the CTA text and changing the link to a federal resource that should be more evergreen.

Changing Tests CTA in Recommends Component

---

src/components/Charts/ChartVaccinations.tsx
src/components/Charts/ChartWeeklyNewCasesPer100k.tsx

Y-axis ticks on 2 charts (`% Vaccinated`, `Weekly New Reported Cases`) were getting cut off. This PR adjusts `marginLeft` for both charts to fix
**Before:**
**After:**

Fix chart margins

---

scripts/alert_emails/create_lists_to_email.ts
scripts/alert_emails/misc/.gitignore
scripts/alert_emails/misc/delete-historical-docs.ts
scripts/alert_emails/misc/generate-historical-stats.ts
scripts/alert_emails/readme.md
scripts/alert_emails/send_emails.ts

This PR reduces the amount of data we will store long-term for past email alerts. We will:
* Add a `deleteAt` field to the docs written to Firestore that will trigger a TTL policy to delete alert docs after 2 weeks.
* Write stats after sending emails since we'll no longer be able to calculate them once the docs are deleted. We write per-snapshot stats to `/alert-stats/[snapshot]` and global stats to `/info/alert-stats`.
* I'm also checking in a couple scripts I'm using to generate historical stats and delete historical documents. These will only be run once, but I'm checking them in for future reference.
I've tested everything on the [covidactnow-dev Firestore instance](https://console.firebase.google.com/project/covidactnow-dev/firestore/data/) (except the fact that the TTL policy runs, …

Reduce storage / billing costs for email alerts.

---

src/api/schema/Actuals.d.ts
src/api/schema/ActualsTimeseriesRow.d.ts
src/api/schema/AggregateFlattenedTimeseries.d.ts
src/api/schema/AggregateRegionSummary.d.ts
src/api/schema/AggregateRegionSummaryWithTimeseries.d.ts
src/api/schema/Metrics.d.ts
src/api/schema/MetricsTimeseriesRow.d.ts
src/api/schema/RegionSummary.d.ts
src/api/schema/RegionSummaryWithTimeseries.d.ts
src/screens/HomePage/HomePage.tsx

Removes Vx map and pulls in bivalent vaccination types from backend API
From roadmap in [CAN cleanup sprint planner](https://docs.google.com/document/d/1kN9Gn7hYzD70SRgXk4IdVkMR5F9GpDpmQIZUwjHBOO0/edit): This was lower in the priority list, but it was a quick change and will remove some extra potential complexity when adding new bivalent booster data and changing the priority/focus from 1+ to bivalent. 
This leaves the Vx map components and tooltips intact, just removes them from the homepage. There's a world in which we remove them entirely, but a) maybe we'll want these components in the future and b) it would require a fair amount of cleanup. I'm open to arguments that we should do that cleanup now, though

Remove Vx Map from homepage and update API types

---

src/api/schema/Actuals.d.ts
src/api/schema/ActualsTimeseriesRow.d.ts
src/api/schema/AggregateFlattenedTimeseries.d.ts
src/api/schema/AggregateRegionSummary.d.ts
src/api/schema/AggregateRegionSummaryWithTimeseries.d.ts
src/api/schema/Metrics.d.ts
src/api/schema/MetricsTimeseriesRow.d.ts
src/api/schema/RegionSummary.d.ts
src/api/schema/RegionSummaryWithTimeseries.d.ts
src/screens/HomePage/HomePage.tsx

This reverts commit 8a0aa10adf7aa450412de2fcf50b9f8ac2df0e4d. 
We're waiting to ship all the CAN update changes at once (and send out a newsletter etc) so I shouldn't have merged this change. 
I've reopened https://github.com/act-now-coalition/covid-act-now-website/pull/7149 for when we do, eventually, want to merge this

Revert "Remove Vx Map from homepage and update API types (#7142)"

---

src/components/LearnDisclaimer/LearnDisclaimer.stories.tsx
src/components/LearnDisclaimer/LearnDisclaimer.tsx
src/screens/Learn/Alerts/Alerts.tsx
src/screens/Learn/Articles/Article.tsx
src/screens/Learn/Articles/ArticlesLanding.tsx
src/screens/Learn/Faq/Faq.tsx
src/screens/Learn/Glossary/Glossary.tsx

Added to: FAQ, Glossary, Research Rundown, COVID Explained Homepage, COVID Explained articles.
Example:

Add disclaimer per CAN Copy Audit '23 Q1 doc.

---

public/admin-overrides/config.yml

Looks like this got modified incorrectly when updating repo paths yesterday and I missed it in the review.
https://github.com/act-now-coalition/covid-act-now-website/pull/7146/files#diff-04f8ec328361d433b1387fda9541b137c12d2d577163b9f8e76c702face9eb29L9

Fix override CMS github URL.

---

src/components/NewLocationPage/CountyMap/CountyMap.tsx

Addresses page load/map selection bug due to local storage variable change: https://sentry.io/organizations/covidactnow/issues/3874968796/?project=5444052&referrer=issue-stream
Reverts the `COUNTY_MAP_TYPE` local storage variable value change, and safeguards the map selection such that, if an invalid value is found in the browser's local storage the map will default to the community risk level map. 
Once the user toggles the map/makes a selection, the variable will be updated to the expected value. 
**To Test:**
1. Visit the [preview link](https://covid-projections-git-smcclure17-map-hotfix-covidactnow.vercel.app/?s=44833229),
2. View the browser's local storage in dev-tools (on chrome: hit `f12` > go to `Application` tab > storage > local storage). 
3. Navigate to any location page and …

BUG: Fix map type info local storage error

---

.github/workflows/update-snapshot.yml

Update preview and compare link URLs.
This is a follow-up to
- Updating Vercel project name from `covid-projections` to `covid-act-now-website`.
- [This comment](https://github.com/act-now-coalition/covid-act-now-website/pull/7146#discussion_r1066253405).

Update preview and compare link urls

---

.github/workflows/update-snapshot.yml

We just changed our team name from `Covidactnow` to `act-now-coalition` on Vercel. This causes our preview and compare links to not work. This PR adjusts these URLs accordingly.

Update compare and preview url after team name change

---

.github/workflows/update-snapshot.yml

This PR shortens preview and compare URLs. It turns out if the number of characters preceding `.vercel.app` exceeds 65, Vercel will automatically truncate our URL and generate a SHA-256 hash instead, which will be trickier to fetch than simply shortening our project name to accommodate.
More info: https://vercel.com/docs/concepts/deployments/generated-urls#truncation

Shorten preview and compare urls

---

src/common/utils/provenance.tsx

These sources aren't automatically compiled from the API data, so we must update them manually. 
This modifies the text in the "About this data" modal:

Add new CDC source for cases data

---

src/components/Charts/Groupings.tsx
src/components/Compare/columns.tsx
src/components/NewLocationPage/LocationOverview/LocationOverview.tsx

Reorder the community level metrics so cases are shown last
Before:
After:

Prioritize hospital metrics above and below the fold, and in compare
